SOAR-6687 fix metasploit plugin
rapid7/insightconnect-plugins pull request #1008
Opened 2021-09-16 17:58 UTC by pmara-r7

## Proposed Changes
Fix Argument passing for the login method for the API
Add try/catch in case of bad server response in search for exploit
Fixed JSON field references in trigger as the name had changed
Add integration test files for the future
[TODO] Updated plugin spec and help to be up to date

### Description

Describe the proposed changes:

  - See Proposed changes

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing
Ran integration tests, output below in comments. 

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2021-09-24 20:34 UTC, mberezin-r7 submitted a review, later dismissed
LGTM

2021-09-27 20:44 UTC, mrinehart-r7 requested changes

2021-09-27 20:44 UTC, mrinehart-r7 commented on plugins/rapid7_metasploit/komand_rapid7_metasploit/actions/search_for_exploit/action.py
> +    def do_section(self, client, search_term, results, list_in: list, list_name: str, dictionary_key: str):
Can you typehint `client`, `search_term`, and `results`?

2021-09-27 20:45 UTC, mrinehart-r7 commented
@pmara-r7 can you post screenshots of in-product testing?

2021-09-28 14:59 UTC, pmara-r7 commented on plugins/rapid7_metasploit/komand_rapid7_metasploit/actions/search_for_exploit/action.py
> +    def do_section(self, client, search_term, results, list_in: list, list_name: str, dictionary_key: str):
Done!

2021-09-28 17:53 UTC, pmara-r7 commented
## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\n{'credentials': {'password': 'redacted', 'username': 'redacted'}, 'port': 3790, 'server': 'https://example.com', 'ssl': True, 'uri': '/api/'}\nClient connection established\nrapid7/Rapid7 https://example.com Step name: execute_exploit\n",
    "meta": {},
    "output": {
      "console_output": [
        "No payload configured, defaulting to java/meterpreter/reverse_tcp",
        "[https://example.com] Started reverse TCP handler on https://example.com ",
        "[https://example.com] https://example.com - Using URL: https://example.com",
        "[https://example.com] https://example.com - Local IP: https://example.com",
        "[https://example.com] https://example.com - Server started.",
        "[https://example.com] https://example.com - Server stopped.",
        "Exploit completed, but no session was created."
      ],
      "session_information": {}
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i pj-test/rapid7_metasploit:3.0.0 run < tests/execute_exploit.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\n{'credentials': {'password': 'redacted', 'username': 'redacted'}, 'port': 3790, 'server': 'https://example.com', 'ssl': True, 'uri': '/api/'}\nClient connection established\nrapid7/Rapid7 https://example.com Step name: search_for_exploit\nSkipping exploit linux/misc/saltstack_salt_unauth_rce due to connection error\nSkipping exploit linux/smtp/haraka due to connection error\nSkipping auxiliary admin/2wire/xslt_password_reset due to connection error\nSkipping auxiliary admin/http/cisco_7937g_ssh_privesc due to connection error\nSkipping auxiliary admin/http/grafana_auth_bypass due to connection error\nSkipping auxiliary admin/teradata/teradata_odbc_sql due to connection error\nSkipping auxiliary dos/cisco/cisco_7937g_dos due to connection error\nSkipping auxiliary dos/cisco/cisco_7937g_dos_reboot due to connection error\nSkipping auxiliary dos/http/slowloris due to connection error\nSkipping auxiliary dos/smb/smb_loris due to connection error\nSkipping auxiliary dos/tcp/claymore_dos due to connection error\nSkipping auxiliary gather/get_user_spns due to connection error\nSkipping auxiliary gather/mikrotik_winbox_fileread due to connection error\nSkipping auxiliary gather/office365userenum due to connection error\nSkipping auxiliary scanner/http/onion_omega2_login due to connection error\nSkipping auxiliary scanner/http/rdp_web_login due to connection error\nSkipping auxiliary scanner/msmail/exchange_enum due to connection error\nSkipping auxiliary scanner/msmail/host_id due to connection error\nSkipping auxiliary scanner/msmail/onprem_enum due to connection error\nSkipping auxiliary scanner/smb/impacket/dcomexec due to connection error\nSkipping auxiliary scanner/smb/impacket/secretsdump due to connection error\nSkipping auxiliary scanner/smb/impacket/wmiexec due to connection error\nSkipping auxiliary scanner/ssl/bleichenbacher_oracle due to connection error\nSkipping auxiliary scanner/teradata/teradata_odbc_login due to connection error\nSkipping auxiliary scanner/wproxy/att_open_proxy due to connection error\nSkipping post aix/hashdump due to connection error\n",
    "meta": {},
    "output": {
      "auxiliaries": [
        "admin/hp/hp_ilo_create_admin_account",
        "admin/http/linksys_tmunblock_admin_reset_bof",
        "admin/http/netgear_r6700_pass_reset",
        "admin/http/netgear_r7000_backup_cgi_heap_overflow_rce",
        "dos/http/cable_haunt_websocket_dos",
        "dos/http/rails_json_float_dos",
        "dos/scada/yokogawa_logsvr",
        "dos/ssl/dtls_fragment_overflow",
        "dos/windows/smb/ms05_047_pnp",
        "gather/qnap_backtrace_admin_hash",
        "scanner/http/smt_ipmi_cgi_scanner"
      ],
      "exploits": [
        "aix/rpc_cmsd_opcode21",
        "aix/rpc_ttdbserverd_realpath",
        "apple_ios/browser/safari_libtiff",
        "apple_ios/email/mobilemail_libtiff",
        "bsd/finger/morris_fingerd_bof",
        "bsdi/softcart/mercantec_softcart",
        "dialup/multi/login/manyargs",
        "freebsd/ftp/proftp_telnet_iac",
        "freebsd/samba/trans2open",
        "freebsd/tacacs/xtacacsd_report",
        "freebsd/telnet/telnet_encrypt_keyid",
        "hpux/lpd/cleanup_exec",
        "linux/ftp/proftp_sreplace",
        "linux/ftp/proftp_telnet_iac",
        "linux/http/airties_login_cgi_bof",
        "linux/http/belkin_login_bof",
        "linux/http/dlink_authentication_cgi_bof",
        "linux/http/dlink_dspw215_info_cgi_bof",
        "linux/http/dlink_hnap_bof",
        "linux/http/dlink_hnap_login_bof",
        "linux/http/linksys_apply_cgi",
        "linux/http/netgear_wnr2000_rce",
        "linux/http/nginx_chunked_size",
        "linux/http/peercast_url",
        "linux/http/smt_ipmi_close_window_bof",
        "linux/ids/snortbopre",
        "linux/imap/imap_uw_lsub",
        "linux/local/hp_smhstart",
        "linux/local/sudo_baron_samedit",
        "linux/misc/gld_postfix",
        "linux/misc/hikvision_rtsp_bof",
        "linux/misc/hp_nnmi_pmd_bof",
        "linux/misc/hp_vsa_login_bof",
        "linux/misc/ib_inet_connect",
        "linux/misc/ib_jrd8_create_database",
        "linux/misc/ib_open_marker_file",
        "linux/misc/ib_pwd_db_aliased",
        "linux/misc/netsupport_manager_agent",
        "linux/misc/novell_edirectory_ncp_bof",
        "linux/misc/quest_pmmasterd_bof",
        "linux/mysql/mysql_yassl_getname",
        "linux/mysql/mysql_yassl_hello",
        "linux/samba/trans2open",
        "linux/smtp/exim_gethostbyname_bof",
        "linux/telnet/telnet_encrypt_keyid",
        "linux/upnp/miniupnpd_soap_bof",
        "multi/browser/adobe_flash_nellymoser_bof",
        "multi/browser/adobe_flash_pixel_bender_bof",
        "multi/browser/adobe_flash_shader_job_overflow",
        "multi/browser/itms_overflow",
        "multi/http/sun_jsws_dav_options",
        "multi/ids/snort_dce_rpc",
        "multi/misc/wireshark_lwres_getaddrbyname",
        "multi/misc/wireshark_lwres_getaddrbyname_loop",
        "multi/ntp/ntp_overflow",
        "multi/realserver/describe",
        "multi/samba/nttrans",
        "multi/upnp/libupnp_ssdp_overflow",
        "multi/vpn/tincd_bof",
        "netware/smb/lsass_cifs",
        "netware/sunrpc/pkernel_callit",
        "osx/afp/loginext",
        "osx/arkeia/type77",
        "osx/ftp/webstar_ftp_user",
        "osx/http/evocam_webserver",
        "osx/local/nfs_mount_root",
        "osx/mdns/upnp_location",
        "osx/misc/ufo_ai",
        "osx/rtsp/quicktime_rtsp_content_type",
        "osx/samba/trans2open",
        "solaris/samba/trans2open",
        "solaris/ssh/pam_username_bof",
        "solaris/sunrpc/sadmind_adm_build_path",
        "solaris/telnet/ttyprompt",
        "unix/smtp/exim4_string_format",
        "windows/antivirus/symantec_iao",
        "windows/antivirus/symantec_rtvscan",
        "windows/antivirus/trendmicro_serverprotect",
        "windows/antivirus/trendmicro_serverprotect_createbinding",
        "windows/antivirus/trendmicro_serverprotect_earthagent",
        "windows/arkeia/type77",
        "windows/backupexec/remote_agent",
        "windows/brightstor/ca_arcserve_342",
        "windows/brightstor/discovery_udp",
        "windows/brightstor/etrust_itm_alert",
        "windows/brightstor/hsmserver",
        "windows/brightstor/lgserver",
        "windows/brightstor/lgserver_multi",
        "windows/brightstor/lgserver_rxrlogin",
        "windows/brightstor/lgserver_rxssetdatagrowthscheduleandfilter",
        "windows/brightstor/lgserver_rxsuselicenseini",
        "windows/brightstor/license_gcr",
        "windows/brightstor/mediasrv_sunrpc",
        "windows/brightstor/message_engine",
        "windows/brightstor/message_engine_72",
        "windows/brightstor/tape_engine",
        "windows/brightstor/tape_engine_ [...]

2021-09-28 17:53 UTC, pmara-r7 commented
## Assessment
### Run

<details>

```
null

```

<summary>
docker run --rm -i pj-test/rapid7_metasploit:3.0.0 --debug run < tests/new_modules.json
</summary>
</details>

### UI

Screenshots of the plugin being used in Komand for validating use go below this line.

#### Workflow Builder


#### Job


#### Artifact

2021-09-28 17:58 UTC, pmara-r7 commented
The output for new_modules works, but the first time it runs it gets every single module and sends it (since everything appears to be new at this point). Posting a snippet of one of the items that it sends from the "test" module.

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\n{'credentials': {'password': 'redacted', 'username': 'redacted'}, 'port': 3790, 'server': 'https://example.com', 'ssl': True, 'uri': '/api/'}\nClient connection established\nrapid7/Rapid7 https://example.com Step name: new_modules\nRun: Got or created cache file: \https://example.com name='/var/cache/metasploit_modules' mode='r+' encoding='UTF-8'\u003e\n",
    "meta": {},
    "output": {
      "success": "true"
    },
    "status": "ok"
  },
  "type": "trigger_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i pj-test/rapid7_metasploit:3.0.0 --debug test < tests/new_modules.json
</summary>

2021-09-28 17:59 UTC, pmara-r7 commented
Here is an example of one of the new modules that output when tested:
{"body": {"meta": {}, "output": {"module": {"name": "Kerberos Domain User Enumeration", "fullname": "auxiliary/gather/kerberos_enumusers", "aliases": [], "rank": 300, "type": "auxiliary", "author": ["Matt Byrne <attackdebris@gmail.com>"], "description": "This module will enumerate valid Domain Users via Kerberos from an unauthenticated perspective. It utilizes\n        the different responses returned by the service for valid and invalid users.", "references": ["URL-https://nmap.org/nsedoc/scripts/krb5-enum-users.html"], "rport": 88, "autofilter_ports": [], "autofilter_services": [], "mod_time": "2019-11-05 18:32:45 +0000", "path": "/modules/auxiliary/gather/kerberos_enumusers.rb", "is_install_path": true, "ref_name": "gather/kerberos_enumusers", "check": false, "post_auth": false, "default_credential": false, "notes": {}, "session_types": false, "needs_cleanup": false}}, "log": ""}, "type": "trigger_event", "version": "v1"}

2021-09-29 15:07 UTC, mrinehart-r7 commented
> @mrinehart-r7 Is testing above sufficient? Or are there some other specific tests you would like to see?

Should be good!

2021-09-29 15:07 UTC, mrinehart-r7 approved these changes

2021-09-29 16:52 UTC, mberezin-r7 approved these changes

2021-09-29 16:53 UTC, merged