WIP: IntSights plugin
rapid7/insightconnect-plugins pull request #1009
Opened 2021-09-17 20:55 UTC by r7-mgorny

## Proposed Changes

### Description

Describe the proposed changes:

 - Init new plugin: IntSights
 - Add action Get Indicator by Value

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2021-09-20 17:43 UTC, jrose-r7 requested changes

2021-09-20 17:43 UTC, jrose-r7 commented on plugins/intsights/plugin.spec.yaml
> +      descirption: Name
```suggestion
      description: Name
```

2021-10-05 15:03 UTC, jrose-r7 commented
Looks like there's a few failing validators because of the help.md
<img width="1171" alt="Screen Shot 2021-10-05 at 10 59 42 AM" src="https://user-images.githubusercontent.com/87443773/136048803-10dec13b-0800-4578-843f-ad703a858250.png">
It might prefer using example.com instead of example.com instead of https://example.com

2021-10-06 20:24 UTC, mrinehart-r7 commented on plugins/intsights/icon_intsights/actions/get_indicator_by_value/action.py
> +                Output.GEO_LOCATION: response.get("Geolocation"),
Do any of these need to be defaulted?

2021-10-06 20:25 UTC, mrinehart-r7 commented on plugins/intsights/icon_intsights/actions/takedown_request/action.py
> +        return clean({Output.STATUS: True})
```suggestion
        return {Output.STATUS: True}
```
No need for clean here if this is always True.

2021-10-06 20:26 UTC, mrinehart-r7 commented on plugins/intsights/icon_intsights/connection/connection.py
> +from insightconnect_plugin_runtime.exceptions import PluginException, ConnectionTestException
```suggestion
from .schema import ConnectionSchema, Input

# Custom imports below
from typing import Optional
from icon_intsights.util.api import IntSightAPI
from insightconnect_plugin_runtime.exceptions import PluginException, ConnectionTestException
```

2021-10-06 20:31 UTC, mrinehart-r7 commented on plugins/intsights/icon_intsights/util/api.py
> +class IntSightAPI:
```suggestion
class IntSightsAPI:
```

2021-10-06 20:34 UTC, mrinehart-r7 commented on plugins/intsights/icon_intsights/util/api.py
> +                    cause="There is an error in response.", assistance=f"{json_response.get('FailedReason')}."
```suggestion
                    cause="IntSights returned an error response: ", assistance=f"{json_response.get('FailedReason')}."
```

2021-10-29 14:58 UTC, mrinehart-r7 submitted a review, later dismissed

2021-10-29 20:04 UTC, mberezin-r7 approved these changes
Aside from the potential infinite loop PJ commented on, this looks good to me.

2021-11-01 18:00 UTC, mberezin-r7 approved these changes

2021-11-01 18:03 UTC, jrose-r7 submitted a review, later dismissed

2021-11-02 14:53 UTC, mrinehart-r7 requested changes

2021-11-02 14:53 UTC, mrinehart-r7 commented on plugins/rapid7_intsights/help.md
> +  "images": "[{\"Type\": \"jpeg\",\"Data\": \"UmFwaWQ3IEluc2lnaHRDb25uZWN0Cg==\"}]",
```suggestion
  "images": [{
    "Type": "jpeg",
    "Data": "UmFwaWQ3IEluc2lnaHRDb25uZWN0Cg=="
  }],
```

2021-11-02 14:55 UTC, mrinehart-r7 approved these changes

2021-11-02 15:03 UTC, mberezin-r7 approved these changes

2021-11-02 20:59 UTC, r7-mgorny commented
## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: enrich_indicator\n",
    "meta": {},
    "output": {
      "data": {
        "DnsRecords": [
          {
            "Count": 16523,
            "FirstResolved": "https://example.com",
            "LastResolved": "https://example.com",
            "Type": "NS",
            "Value": "https://example.com"
          },
          {
            "Count": 16523,
            "FirstResolved": "https://example.com",
            "LastResolved": "https://example.com",
            "Type": "NS",
            "Value": "https://example.com"
          },
          {
            "Count": 646,
            "FirstResolved": "https://example.com",
            "LastResolved": "https://example.com",
            "Type": "NS",
            "Value": "https://example.com"
          }
        ],
        "IsKnownIoc": false,
        "RelatedCampaigns": [],
        "RelatedHashes": {
          "communicating": [
            "22n708a98wxww6p76lif8r7rn1a7422012l579m82i222e68957u4603510y4228"
          ],
          "downloaded": [
            "22n708a98wxww6p76lif8r7rn1a7422012l579m82i222e68957u4603510y4228"
          ],
          "referencing": []
        },
        "RelatedMalwares": [],
        "RelatedThreatActors": [],
        "Resolutions": [
          {
            "ASN": 16276,
            "FirstResolved": "https://example.com",
            "LastResolved": "https://example.com",
            "Location": "DE",
            "Operator": "OVH SAS",
            "ReportingSources": [
              "Farsight",
              "VirusTotal"
            ],
            "ResolvedIpAddress": "https://example.com"
          },
          {
            "ASN": 16276,
            "FirstResolved": "https://example.com",
            "LastResolved": "https://example.com",
            "Location": "FR",
            "Operator": "OVH SAS",
            "ReportingSources": [
              "Farsight",
              "VirusTotal"
            ],
            "ResolvedIpAddress": "https://example.com"
          }
        ],
        "Severity": {
          "Score": 20,
          "Value": "Low"
        },
        "Sources": [],
        "Subdomains": [
          "https://example.com",
          "metami",
          "test829"
        ],
        "SystemTags": [],
        "Tags": [],
        "Type": "Domains",
        "Value": "https://example.com",
        "Whitelisted": false,
        "Whois": {
          "Current": {
            "RegistrantDetails": [],
            "RegistrationDetails": {
              "CreatedDate": "https://example.com",
              "ExpiresDate": "https://example.com",
              "NameServers": [
                "https://example.com",
                "https://example.com"
              ],
              "Statuses": [],
              "UpdatedDate": "https://example.com"
            }
          },
          "History": [
            {
              "RegistrantDetails": [],
              "RegistrationDetails": {
                "CreatedDate": "https://example.com",
                "ExpiresDate": "https://example.com",
                "NameServers": [
                  "https://example.com",
                  "https://example.com"
                ],
                "Statuses": [],
                "UpdatedDate": "https://example.com"
              }
            }
          ]
        }
      },
      "original_value": "https://example.com",
      "status": "Done"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:1.0.0 --debug run < tests/enrich_indicator.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: get_alerts\n",
    "meta": {},
    "output": {
      "alert_ids": [
        "3396n3b4z9s2b77964e1fp4e",
        "3599v148818t995862708l85",
        "4618302j551a6s3749un5gq5"
      ]
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:1.0.0 --debug run < tests/get_alerts.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: get_complete_alert_by_id\n",
    "meta": {},
    "output": {
      "assets": [],
      "assignees": [],
      "details": {
        "Description": "Alert description",
        "Images": [],
        "Severity": "High",
        "Source": {
          "NetworkType": "ClearWeb",
          "Type": "Application Store",
          "URL": "https://example.com"
        },
        "SubType": "SuspiciousEmailAddress",
        "Tags": [],
        "Title": "Alert test 4",
        "Type": "Phishing"
      },
      "found_date": "https://example.com",
      "id": "29899f708d7j6a1628ck5p50",
      "is_closed": false,
      "is_flagged": false,
      "takedown_status": "NotSent",
      "update_date": "https://example.com"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:1.0.0 --debug run < tests/get_complete_alert_by_id.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: get_indicator_by_value\n",
    "meta": {},
    "output": {
      "first_seen": "https://example.com",
      "last_seen": "https://example.com",
      "last_update": "https://example.com",
      "related_campaigns": [],
      "related_malware": [],
      "related_threat_actors": [],
      "score": 10,
      "severity": "Low",
      "sources": [
        {
          "ConfidenceLevel": 2,
          "Name": "Cyber Threat Alliance"
        }
      ],
      "system_tags": [],
      "tags": [],
      "type": "Domains",
      "value": "https://example.com",
      "whitelist": true
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:1.0.0 --debug run < tests/get_indicator_by_value.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: rescan_indicator\n",
    "meta": {},
    "output": {
      "status": "Queued",
      "task_id": "4328n08s02j33e0f27oe1h8p"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:1.0.0 --debug run < tests/rescan_indicator.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: get_indicator_scan_status\n",
    "meta": {},
    "output": {
      "status": "Done",
      "task_id": "55638xdla173d41713aabh14"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:1.0.0 --debug run < tests/get_indicator_scan_status.json
</summary>
</details>

<details>

```
{
  "body": {
    "error": "An error occurred during plugin execution!\n\nInvalid API key provided. Verify your API key configured in your connection is correct. Response was: RemediationLimitExceeded",
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com Step name: takedown_request\nAn error occurred during plugin execution!\n\nInvalid API key provided. Verify your API key configured in your connection is correct. Response was: RemediationLimitExceeded\nTraceback (most recent call last):\n  File \"/usr/local/lib/https://example.com\", line 326, in handle_step\n    output = https://example.com\n  File \"/usr/local/lib/https://example.com\", line 476, in start_step\n    output = func(params)\n  File \"/usr/local/lib/https://example.com\", line 17, in run\n    https://example.com, https://example.com\n  File \"/usr/local/lib/https://example.com\", line 131, in takedown_request\n    return https://example.com\n  F [...]

2021-11-02 21:01 UTC, mrinehart-r7 approved these changes

2021-11-02 21:02 UTC, mberezin-r7 approved these changes

2021-11-02 21:02 UTC, merged