MC-912 Add new CVE actions to Rapid7 Intsights plugin
rapid7/insightconnect-plugins pull request #1125
Opened 2022-02-17 11:07 UTC by mgrandys-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Implement `get_cve_list`, `add_cve` and `delete_cve` actions with unit tests.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com/ Step name: add_cve\n",
    "meta": {},
    "output": {
      "failure": [
        {
          "cveId": "CVE-213-ffsd2",
          "failReason": "Invalid CVE format"
        },
        {
          "cveId": "CVE-2020-7065",
          "failReason": "CVE already associated to account"
        }
      ],
      "success_amount": 3
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:3.1.0 run < tests/add_cve.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com/ Step name: delete_cve\n",
    "meta": {},
    "output": {
      "failure": [
        {
          "cveId": "CVE-1999-0006",
          "failReason": "CVEs are not associated to account"
        }
      ],
      "success_amount": 2
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_intsights:3.1.0 run < tests/delete_cve.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Rapid7 https://example.com/ Step name: get_cve_list\n",
    "meta": {},
    "output": {
      "content": [
        {
          "cpe": [],
          "cveId": "CVE-2020-20795",
          "exploitAvailability": false,
          "firstMentionDate": "https://example.com/",
          "intsightsScore": 1,
          "lastMentionDate": "https://example.com/",
          "mentionsAmount": 1,
          "mentionsPerSource": {
            "ClearWebCyberBlogs": 0,
            "CodeRepositories": 0,
            "DarkWeb": 0,
            "Exploit": 0,
            "HackingForum": 0,
            "InstantMessage": 0,
            "PasteSite": 0,
            "SocialMedia": 1
          },
          "publishedDate": "https://example.com/",
          "relatedCampaigns": [],
          "relatedMalware": [],
          "relatedThreatActors": [],
          "severity": "Low",
          "updateDate": "https://example.com/",
          "vulnerabilityOrigin": [
            "API"
          ]
        },
        {
          "cpe": [
            {
              "Range": {
                "VersionEndExcluding": "2017-08-25"
              },
              "Title": "Voten",
              "Value": "https://example.com/*:*:*:*:*:*:*:*",
              "VendorProduct": "Voten Voten"
            }
          ],
          "cveId": "CVE-2018-7663",
          "cvssScore": https://example.com/,
          "exploitAvailability": false,
          "firstMentionDate": "https://example.com/",
          "intsightsScore": 28,
          "lastMentionDate": "https://example.com/",
          "mentionsAmount": 20,
          "mentionsPerSource": {
            "ClearWebCyberBlogs": 0,
            "CodeRepositories": 1,
            "DarkWeb": 0,
            "Exploit": 0,
            "HackingForum": 0,
            "InstantMessage": 0,
            "PasteSite": 0,
            "SocialMedia": 19
          },
          "publishedDate": "https://example.com/",
          "relatedCampaigns": [],
          "relatedMalware": [],
          "relatedThreatActors": [],
          "severity": "Low",
          "updateDate": "https://example.com/",
          "vulnerabilityOrigin": [
            "API"
          ]
        },
        {
          "cpe": [
            {
              "Range": {
                "VersionEndExcluding": "https://example.com/",
                "VersionStartIncluding": "https://example.com/"
              },
              "Title": "Paloaltonetworks Bridgecrew Checkov",
              "Value": "https://example.com/*:*:*:*:*:*:*:*",
              "VendorProduct": "Paloaltonetworks Bridgecrew Checkov"
            }
          ],
          "cveId": "CVE-2021-3035",
          "cvssScore": https://example.com/,
          "exploitAvailability": false,
          "firstMentionDate": "https://example.com/",
          "intsightsScore": 28,
          "lastMentionDate": "https://example.com/",
          "mentionsAmount": 11,
          "mentionsPerSource": {
            "ClearWebCyberBlogs": 0,
            "CodeRepositories": 0,
            "DarkWeb": 0,
            "Exploit": 0,
            "HackingForum": 0,
            "InstantMessage": 0,
            "PasteSite": 0,
            "SocialMedia": 11
          },
          "publishedDate": "https://example.com/",
          "relatedCampaigns": [],
          "relatedMalware": [],
          "relatedThreatActors": [],
          "severity": "Low",
          "updateDate": "https://example.com/",
          "vulnerabilityOrigin": [
            "API"
          ]
        },
        {
          "cpe": [
            {
              "Range": {},
              "Title": "Google Android",
              "Value": "https://example.com/*:*:*:*:*:*:*",
              "VendorProduct": "G [...]

2022-02-18 19:00 UTC, mrinehart-r7 submitted a review, later dismissed

2022-02-28 13:23 UTC, dsliwinski-r7 requested changes

2022-02-28 13:23 UTC, dsliwinski-r7 commented on plugins/rapid7_intsights/help.md
> +* 3.1.0 - Add new actions Add CVE and Delete CVE
```suggestion
* 3.1.0 - Add new actions Add CVEs, Delete CVEs and Get CVE List
```

2022-03-02 16:22 UTC, dsliwinski-r7 approved these changes

2022-03-15 12:03 UTC, mgrandys-r7 commented
@mrinehart-r7 Could you please approve this PR or suggest additional changes?

2022-03-15 17:17 UTC, mrinehart-r7 commented
> @mrinehart-r7 Could you please approve this PR or suggest additional changes?

@mgrandys-r7 please request a review from @mberezin-r7 for this :)

2022-03-15 19:08 UTC, mberezin-r7 approved these changes

2022-03-15 19:16 UTC, merged