SOAR [8441] - Fix issue with REST/HTTP patch method
rapid7/insightconnect-plugins pull request #1133
Opened 2022-02-23 15:21 UTC by igorski-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Fix the issue with PATCH method in REST/HTTP plugin

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [x] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [x] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [x] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [x] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [x] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [x] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [x] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [x] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [x] Work fully completed
- [x] Functional
  - [x] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [x] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [x] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [x] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [x] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

### Validators

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator CloudReadyValidator
[*] Executing validator SupportedVersionValidator
[*] Executing validator UnapprovedKeywordsValidator
WARNING: Unsupported keywords found: request, rpc, microservices. The following keywords will not be searchable by the Extension Library. Please remove or update the invalid keywords from the keywords array in the plugin.spec.yaml file.
[*] Executing validator HelpExampleValidator
[*] Executing validator Version Increment Validator
[*] Executing validator ExceptionValidator
[*] Executing validator CredentialsValidator
[*] Executing validator PasswordValidator
[*] Executing validator PrintValidator
[*] Executing validator ConfidentialValidator
[*] Executing validator DockerValidator
[*] Executing validator URLValidator
WARNING: URLs found that return a 4xx code. Verify they are publicly accessible and if not, update with a working URL.
violation: help.md[153]: https://httpbin.org/put\
violation: help.md[77]: https://us.api.insight.rapid7.com
violation: help.md[226]: https://httpbin.org/post
violation: help.md[228]: https://httpbin.org/post
violation: help.md[151]: https://httpbin.org/put
violation: help.md[153]: https://httpbin.org/put
violation: help.md[29]: https://httpbin.org/|
violation: help.md[423]: https://httpbin.org/delete
violation: help.md[425]: https://httpbin.org/delete
violation: help.md[298]: https://httpbin.org/patch
violation: help.md[300]: https://httpbin.org/patch
violation: help.md[29]: httpbin.org
violation: help.md[41]: httpbin.org
violation: help.md[59]: httpbin.org
violation: help.md[143]: httpbin.org
violation: help.md[151]: httpbin.org
violation: help.md[153]: httpbin.org
violation: help.md[218]: httpbin.org
violation: help.md[226]: httpbin.org
violation: help.md[228]: httpbin.org
violation: help.md[292]: httpbin.org
violation: help.md[298]: httpbin.org
violation: help.md[300]: httpbin.org
violation: help.md[417]: httpbin.org
violation: help.md[423]: httpbin.org
violation: help.md[425]: httpbin.org
violation: help.md[300]: https://httpbin.org/patch\
violation: help.md[425]: https://httpbin.org/delete\
violation: help.md[228]: https://httpbin.org/post\
[*] Plugin failed validation! The following validation errors occurred:

Validator "HelpExampleValidator" failed! 
        Cause: Invalid JSON example identified in Example input of action titled PUT. Please correct the JSON example in help.md.
        Improperly formatted JSON example identified in Example input of action titled PUT. Please updated the JSON example in help.md with 2 space indentation.
        Invalid JSON example identified in Example input of action titled Input. Please correct the JSON example in help.md.
        Improperly formatted JSON example identified in Example input of action titled Input. Please updated the JSON example in help.md with 2 space indentation.
        Invalid JSON example identified in Example input of action titled Input. Please correct the JSON example in help.md.
        Improperly formatted JSON example identified in Example input of action titled Input. Please updated the JSON example in help.md with 2 space indentation.
        Invalid JSON example identified in Example input of action titled Input. Please correct the JSON example in help.md.
        Invalid JSON example identified in Example input of action titled Input. Please correct the JSON example in help.md.
        Improperly formatted JSON example identified in Example input of action titled Input. Please updated the JSON example in help.md with 2 space indentation.
```

<summary>
icon-validate --all .
</summary>
</details>

2022-02-23 23:40 UTC, mrinehart-r7 reviewed
This code looks sound, but does it actually fix the issue logged in the ticket? Admittedly the payload they provided in the ticket is difficult to read, but I'm not sure how this fixes it?

2022-02-28 19:59 UTC, blaxminarayan-r7 requested changes

2022-02-28 19:59 UTC, blaxminarayan-r7 commented on plugins/rest/help.md
> +* 5.0.2 - Fix issue with JSON data parser
```suggestion
* 5.0.2 - Fix issue with JSON data parser for PATCH request
```

2022-03-02 12:45 UTC, cmcnally-r7 approved these changes

2022-03-03 12:43 UTC, blaxminarayan-r7 approved these changes

2022-03-03 12:43 UTC, merged