[SOAR-8703] Fix for dl get
rapid7/insightconnect-plugins pull request #1153
Opened 2022-03-04 14:03 UTC by cmcnally-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Changed dlGet to only retrieve 'data' from result

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2022-03-04 17:19 UTC, blaxminarayan-r7 approved these changes

2022-03-04 21:35 UTC, mrinehart-r7 requested changes
Two things to address here:
1. Make sure to bump the version in the plugin.spec.yaml and regenerate :)
2. We have a function that does the same thing as `return_non_empty` in the plugin runtime code - `clean`. You can use it like `from insightconnect_plugin_runtime.helper import clean`. I would suggest using that.

2022-03-04 21:35 UTC, mrinehart-r7 commented on plugins/cisco_umbrella_destinations/plugin.spec.yaml
> +    title: Add a destination to a Destination List
```suggestion
    title: Add Destination to Destination List
```

2022-03-07 12:38 UTC, blaxminarayan-r7 requested changes

2022-03-07 12:38 UTC, blaxminarayan-r7 commented on plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
> +Version = "1.0.1"
This should be 1.0.0, It is not released yet

2022-03-07 12:38 UTC, blaxminarayan-r7 commented on plugins/cisco_umbrella_destinations/help.md
> +This action is used to add a destination to a destination list.
```suggestion
This action is used to add a destination to the destination list.
```

2022-03-07 12:38 UTC, blaxminarayan-r7 commented on plugins/cisco_umbrella_destinations/help.md
> +* 1.0.1 - Updated action title (dAdd) and included an icon runtime helper function
You dont need this as, 1.0.0 is not released yet.

2022-03-07 12:38 UTC, blaxminarayan-r7 commented on plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dAdd/schema.py
> +    DESCRIPTION = "Add a destination to a destination list"
```suggestion
    DESCRIPTION = "Add a destination to the destination list"
```

2022-03-07 12:38 UTC, blaxminarayan-r7 commented on plugins/cisco_umbrella_destinations/plugin.spec.yaml
> +version: 1.0.1
No version bump is needed.

2022-03-07 12:38 UTC, blaxminarayan-r7 commented on plugins/cisco_umbrella_destinations/setup.py
> +      version="1.0.1",
No version bump is needed

2022-03-07 14:01 UTC, merged