[SOAR-8240] Add Uninstall Sensor action, upgrade to insightconnect-plugin-runtime for Carbon Black Response plugin
rapid7/insightconnect-plugins pull request #1162
Opened 2022-03-08 21:06 UTC by tcheng-r7

## Proposed Changes

### Description

Describe the proposed changes:

  -Added Uninstall Sensor action for the Carbon Black Response (EDR) plugin which sends a POST request to change the uninstall flag in the sensor data, given a sensor ID, with unit tests
  -Upgraded to the insightconnect-plugin-runtime library from the older komand library

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2022-03-10 12:47 UTC, jkaluza-rapid7 commented on plugins/carbon_black_response/help.md
> +```
Empty example output. Please provide an example

2022-03-10 12:47 UTC, jkaluza-rapid7 commented on plugins/carbon_black_response/help.md
> +```
Empty example input

2022-03-10 12:47 UTC, jkaluza-rapid7 commented on plugins/carbon_black_response/icon_carbon_black_response/actions/list_sensors/action.py
> +        sensorId = params.get("id", "")
please use snake case instead of camel case for local variables.
```suggestion
        sensor_id = params.get("id", "")
```

2022-03-10 12:47 UTC, jkaluza-rapid7 commented on plugins/carbon_black_response/icon_carbon_black_response/actions/uninstall_sensor/action.py
> +# Custom imports below
please delete this comment. Since we use `black` this separation does not make sense.

2022-03-10 12:47 UTC, jkaluza-rapid7 commented on plugins/carbon_black_response/icon_carbon_black_response/actions/uninstall_sensor/action.py
> +        sensorId = params.get("id", "")
Please use snake case

2022-03-10 12:47 UTC, jkaluza-rapid7 commented on plugins/carbon_black_response/icon_carbon_black_response/actions/uninstall_sensor/action.py
> +                ) from None
I think ```from None``` clause is not necessary

2022-03-29 11:08 UTC, ablakley-r7 commented on plugins/carbon_black_response/unit_test/test_uninstall_sensor.py
> +        test_action = UninstallSensor()
Could possibly move action and connection instantiation to a setup method, but just a suggestion :)


```
def setUpClass(self) -> None:
    self.log = logging.getLogger("Test")
    self.test_action = UninstallSensor()
    self.test_action.connection = MockConnection()
    self.test_action.logger = self.log
```

2022-03-29 16:12 UTC, tcheng-r7 commented on plugins/carbon_black_response/Dockerfile
> +FROM rapid7/insightconnect-python-3-38-plugin:latest
slim cannot be used as there are apt calls being made in the Dockerfile, which the slim image does not support.

2022-03-30 09:30 UTC, ablakley-r7 approved these changes

2022-03-30 09:30 UTC, ablakley-r7 commented on plugins/carbon_black_response/plugin.spec.yaml
> +        description: 'Unique ID of the alert. '
Just noticed a small trailing space, but happy to approve.

```suggestion
        description: 'Unique ID of the alert.'
```

2022-03-30 15:34 UTC, ablakley-r7 approved these changes

2022-04-05 14:33 UTC, blaxminarayan-r7 requested changes

2022-04-05 18:11 UTC, tcheng-r7 commented on plugins/carbon_black_response/help.md
> +_There are no supported product versions listed._
I added the specific version numbers instead as the API is not a SaaS

2022-04-26 16:38 UTC, blaxminarayan-r7 requested changes

2022-04-26 19:01 UTC, blaxminarayan-r7 approved these changes

2022-04-26 19:02 UTC, merged