[SOAR-8686] Microsoft Log Analytics plugin
rapid7/insightconnect-plugins pull request #1182
Opened 2022-03-18 15:01 UTC by igorski-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Send Log Data
  - Get Log Data

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [X] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [X] Screenshot of job output with the plugin changes
- [X] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [X] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [X] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [X] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [X] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [X] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [X] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [X] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [X] Work fully completed
- [X] Functional
  - [X] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [X] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [X] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [X] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [X] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

### Test

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nUpdating auth token...\nAuthentication Token: ****************j-m6A\nGetting shared key...\nShared Key: ****************BHQ==\nGetting workspace ID...\nWorkspace ID: ****************\nrapid7/Microsoft Log Analytics:1.0.0. Step name: get_log_data\nUpdating auth token...\nAuthentication Token: ****************\nGetting shared key...\nShared Key: ****************\nGetting workspace ID...\nWorkspace ID: ****************d2a2a\n",
    "status": "ok",
    "meta": {},
    "output": {
      "success": true
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i rapid7/microsoft_log_analytics:1.0.0 test < tests/get_log_data.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nUpdating auth token...\nAuthentication Token: ****************j-m6A\nGetting shared key...\nShared Key: ****************BHQ==\nGetting workspace ID...\nWorkspace ID: ****************\nrapid7/Microsoft Log Analytics:1.0.0. Step name: get_log_data\nUpdating auth token...\nAuthentication Token: ****************\nGetting shared key...\nShared Key: ****************\nGetting workspace ID...\nWorkspace ID: ****************d2a2a\n",
    "status": "ok",
    "meta": {},
    "output": {
      "success": true
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i rapid7/microsoft_log_analytics:1.0.0 test < tests/send_log_data.json
</summary>
</details>

### Run

<details>

```
{
  "tables": [
    {
      "name": "PrimaryResult",
      "columns": [
        {
          "name": "parameter_1_s",
          "type": "string"
        }
      ],
      "rows": [
        {
          "parameter_1_s": "Test8"
        },
        {
          "parameter_1_s": "Test6"
        },
        {
          "parameter_1_s": "Test7"
        },
        {
          "parameter_1_s": "Test2"
        },
        {
          "parameter_1_s": "Test5"
        },
        {
          "parameter_1_s": "Test4"
        },
        {
          "parameter_1_s": "Test3"
        }
      ]
    }
  ]
}
```

<summary>
docker run --rm -i rapid7/microsoft_log_analytics:1.0.0 run < tests/get_log_data.json
</summary>
</details>

<details>

```
{
  "message": "Log data has been added",
  "log_data": [
    {
      "parameter_1": "Test1"
    }
  ]
}
```

<summary>
docker run --rm -i rapid7/microsoft_log_analytics:1.0.0 run < tests/send_log_data.json
</summary>
</details>

### Icon-validate

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator CloudReadyValidator
[*] Executing validator SupportedVersionValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator HelpExampleValidator
[*] Executing validator Version Increment Validator
[*] Executing validator ExceptionValidator
[*] Executing validator CredentialsValidator
[*] Executing validator PasswordValidator
[*] Executing validator PrintValidator
[*] Executing validator ConfidentialValidator
[*] Executing validator DockerValidator
[*] Executing validator URLValidator
[*] Plugin failed validation! The following validation errors occurred:

Validator "IconValidator" failed! 
        Cause: icon.png file not included in plugin.

Validator "HelpExampleValida [...]

2022-03-21 12:51 UTC, jkaluza-rapid7 approved these changes

2022-03-21 12:51 UTC, jkaluza-rapid7 commented on plugins/microsoft_log_analytics/icon_microsoft_log_analytics/util/api.py
> +        try:
I got 409 once using azure API would it be possible in your case?

2022-03-21 12:51 UTC, jkaluza-rapid7 commented on plugins/microsoft_log_analytics/icon_microsoft_log_analytics/util/tools.py
> +    :param attempt: Current attempt value in retry cuntion
```suggestion
    :param attempt: Current attempt value in retry funtion
``` ???

2022-03-21 12:51 UTC, jkaluza-rapid7 commented on plugins/microsoft_log_analytics/plugin.spec.yaml
> +    description: This is active directory ID
```suggestion
    description: This is an Active Directory ID
```
I think proper names are spelled with capital letters?

2022-03-25 14:00 UTC, blaxminarayan-r7 requested changes

2022-03-30 14:35 UTC, blaxminarayan-r7 approved these changes

2022-03-30 14:36 UTC, merged