[SOAR-5536] InsightVM Tag Assets new action
rapid7/insightconnect-plugins pull request #1251
Opened 2022-05-18 13:44 UTC by ablakley-r7

## Proposed Changes

### Description

Describe the proposed changes:

  -

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2022-05-19 12:31 UTC, igorski-r7 requested changes
Looks great! 😃  Posted some comments there, but it's up to you. Let me know if you want to make those changes or not.

2022-05-19 12:31 UTC, igorski-r7 commented on plugins/rapid7_insightvm/komand_rapid7_insightvm/util/endpoints.py
> +    def tag_assets(console_url, tag_id):
Great to see docstring here! 😃  Would you like to add type hints as well?

2022-05-19 12:31 UTC, igorski-r7 commented on plugins/rapid7_insightvm/unit_test/test_tag_assets.py
> +        self.assertEqual(data, e.exception.data)
Well personally I don't like single letter variables, but it's up to you 😃 
```suggestion
        with self.assertRaises(PluginException) as error:
            self.action.run(self.params)
        self.assertEqual(cause, error.exception.cause)
        self.assertEqual(assistance, error.exception.assistance)
        self.assertEqual(data, error.exception.data)
```

2022-05-19 12:31 UTC, igorski-r7 commented on plugins/rapid7_insightvm/unit_test/test_tag_assets.py
> +        self.assertEqual(data, e.exception.data)
Same here
```suggestion
        with self.assertRaises(PluginException) as error:
            self.action.run(self.params)
        self.assertEqual(cause, error.exception.cause)
        self.assertEqual(assistance, error.exception.assistance)
        self.assertEqual(data, error.exception.data)
```

2022-05-19 12:31 UTC, igorski-r7 commented on plugins/rapid7_insightvm/unit_test/test_tag_assets.py
> +        self.assertEqual(data, e.exception.data)
```suggestion
        with self.assertRaises(PluginException) as error:
            self.action.run(self.params)
        self.assertEqual(cause, error.exception.cause)
        self.assertEqual(assistance, error.exception.assistance)
        self.assertEqual(data, error.exception.data)
```

2022-05-19 12:31 UTC, igorski-r7 commented on plugins/rapid7_insightvm/unit_test/test_tag_assets.py
> +        self.assertEqual(data, e.exception.data)
```suggestion
        with self.assertRaises(PluginException) as error:
            self.action.run(self.params)
        self.assertEqual(cause, error.exception.cause)
        self.assertEqual(assistance, error.exception.assistance)
        self.assertEqual(data, error.exception.data)
```

2022-05-19 12:44 UTC, jkaluza-rapid7 approved these changes

2022-05-19 14:14 UTC, igorski-r7 approved these changes

2022-05-20 11:01 UTC, cmcnally-r7 approved these changes

2022-05-23 16:18 UTC, merged