[SOAR-9449] AWS EC2 - Bump Python to 3 and update to insightconnect r…
rapid7/insightconnect-plugins pull request #1260
Opened 2022-05-24 12:26 UTC by jkaluza-rapid7

### Description

  - Update python version
  - update runtime version

### Testing

#### Unit Tests

No unit-tests. We will have a separate PR for them.

2022-05-25 09:36 UTC, igorski-r7 commented on plugins/aws_ec2/help.md
> +
Kindly please `make regenerate` to fit `supported_versions` field form plugin.spec.yaml file 😃

2022-05-25 11:19 UTC, igorski-r7 requested changes

2022-05-25 11:19 UTC, igorski-r7 commented on plugins/aws_ec2/help.md
> +}
Same comment for all `Example inputs` 😃 . Wouldn't it look much better this way?
```suggestion
{
  "dry_run": true,
  "group_id": "sg-123456",
  "group_name": "groupname",
  "ip_permissions": [
    {
      "from_port": 8080,
      "ip_protocol": "tcp",
      "ip_ranges": [
        {
          "cidr_ip": "10.20.0.0/27",
          "description": "Blah"
        }
      ],
      "to_port": 8090
    }
  ]
}
```

2022-05-25 11:26 UTC, cmcnally-r7 approved these changes

2022-05-25 12:31 UTC, igorski-r7 approved these changes

2022-05-25 15:47 UTC, mberezin-r7 requested changes

2022-05-25 15:47 UTC, mberezin-r7 commented on plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_egress/action.py
>  from .schema import AuthorizeSecurityGroupEgressInput, AuthorizeSecurityGroupEgressOutput
For each action, please add

```suggestion
from .schema import AuthorizeSecurityGroupEgressInput, AuthorizeSecurityGroupEgressOutput, Component
```
...

2022-05-25 15:47 UTC, mberezin-r7 commented on plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_egress/action.py
>              description="[EC2-VPC only] Adds one or more egress rules to a security group for use with a VPC",
...
and please add
```suggestion
            description=Component.DESCRIPTION
```

2022-05-26 10:58 UTC, jkaluza-rapid7 commented on plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_egress/action.py
>  from .schema import AuthorizeSecurityGroupEgressInput, AuthorizeSecurityGroupEgressOutput
Thanks, good catch 👍

2022-06-06 18:06 UTC, closed without merging