[SOAR-10500] CSV Update help.md
rapid7/insightconnect-plugins pull request #1366
Opened 2022-07-26 11:23 UTC by TKuzas-R7

## Proposed Changes

### Description

Describe the proposed changes:

  - Updated Input/output examples in help.md file to make sure the example input actually returns the example output.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2022-07-29 15:28 UTC, cmcnally-r7 approved these changes

2022-07-29 15:28 UTC, TKuzas-R7 reviewed
you did great

2022-08-01 12:06 UTC, igorski-r7 approved these changes

2022-08-01 13:17 UTC, ablakley-r7 requested changes
Changes look good, as long as the change is also reflected in the plugin.spec.yaml file it looks great to me. This should help solve the validator failure as well.

2022-08-01 13:17 UTC, ablakley-r7 commented on plugins/csv/help.md
> +|fields|string|None|True|Fields to filter|None|f1, f2|
This change should be reflected in the plugin.spec.yaml file. If you complete it in that file and regenerate it should fill this in as well. Just be careful the regeneration doesn't undo anything you already have.

2022-08-01 13:17 UTC, ablakley-r7 commented on plugins/csv/help.md
>  |csv|string|None|True|CSV string|None|column1, column2\nvalue1, value2|
If this can be updated in the plugin.spec.yaml file and here to include the 'csv' example from the new below Example input section.

2022-08-01 13:17 UTC, ablakley-r7 commented on plugins/csv/help.md
> +|fields|string|None|True|Fields to filter|None|f1, f2-f3|
This should match plugin.spec.yaml entry as well.

2022-08-03 11:43 UTC, ablakley-r7 approved these changes

2022-08-15 14:48 UTC, blaxminarayan-r7 approved these changes

2022-08-15 19:39 UTC, merged