[SOAR-10321] - Splunk - Add more logging for search action
rapid7/insightconnect-plugins pull request #1383
Opened 2022-08-11 14:28 UTC by jkaluza-rapid7

## Proposed Changes

### Description

Describe the proposed changes:

  - Improve logging for search action

2022-08-12 09:46 UTC, igorski-r7 approved these changes

2022-08-15 14:06 UTC, ablakley-r7 requested changes
Looks great. Just noticed an apostrophe in the version history and happy to approve when removed.

2022-08-15 14:06 UTC, ablakley-r7 commented on plugins/splunk/help.md
> +* 3.0.4 - Add `more logging for search action
```suggestion
* 3.0.4 - Add more logging for Search action
```

2022-08-26 15:21 UTC, cmcnally-r7 approved these changes

2022-10-31 13:55 UTC, closed without merging