[MC-1279] CrowdStrike Falcon Intelligence plugin with 7 actions
rapid7/insightconnect-plugins pull request #1513
Opened 2022-11-30 13:09 UTC by mgrandys-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Initial plugin | Check Analysis Status, Download Artifact, Get Full Report, Get Reports IDs, Get Short Report, Get Submissions IDs, Submit Analysis

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/CrowdStrike Falcon https://example.com Step name: checkAnalysisStatus\nChecking analysis status of IDs: ['9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0', '9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0', '9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0', '9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0', '9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0']...\nGetting authentication token...\n",
    "meta": {},
    "output": {
      "submissions": [
        {
          "cid": "9de5069c5afe602b2ea0a04b66beb2c0",
          "created_timestamp": "2022-08-30T10:06:44Z",
          "id": "9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0",
          "origin": "uiproxy",
          "sandbox": [
            {
              "environment_id": 160,
              "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
              "submit_name": "https://example.com"
            }
          ],
          "state": "error",
          "user_id": "9de5069c5afe602b2ea0a04b66beb2c0",
          "user_name": "https://example.com",
          "user_uuid": "a149764d-21ee-42af-ac9f-023f5d23ab81"
        },
        {
          "cid": "9de5069c5afe602b2ea0a04b66beb2c0",
          "created_timestamp": "2022-08-30T09:25:35Z",
          "id": "9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0",
          "origin": "uiproxy",
          "sandbox": [
            {
              "environment_id": 300,
              "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
              "submit_name": "https://example.com"
            }
          ],
          "state": "error",
          "user_id": "9de5069c5afe602b2ea0a04b66beb2c0",
          "user_name": "https://example.com",
          "user_uuid": "a149764d-21ee-42af-ac9f-023f5d23ab81"
        },
        {
          "cid": "9de5069c5afe602b2ea0a04b66beb2c0",
          "created_timestamp": "2022-08-30T09:21:00Z",
          "id": "9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0",
          "origin": "uiproxy",
          "sandbox": [
            {
              "environment_id": 100,
              "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
              "submit_name": "https://example.com"
            }
          ],
          "state": "error",
          "user_id": "9de5069c5afe602b2ea0a04b66beb2c0",
          "user_name": "https://example.com",
          "user_uuid": "a149764d-21ee-42af-ac9f-023f5d23ab81"
        },
        {
          "cid": "9de5069c5afe602b2ea0a04b66beb2c0",
          "created_timestamp": "2022-11-04T13:56:17Z",
          "id": "9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0",
          "origin": "apigateway",
          "sandbox": [
            {
              "action_script": "default_randomfiles",
              "environment_id": 100,
              "network_settings": "offline",
              "submit_name": "my_submit_name",
              "system_date": "2022-09-22",
              "system_time": "12:55",
              "url": "hxxps://https://example.com"
            }
          ],
          "state": "error",
          "user_tags": [
            "example"
          ]
        },
        {
          "cid": "9de5069c5afe602b2ea0a04b66beb2c0",
          "created_timestamp": "2022-11-10T15:15:59Z",
          "id": "9de5069c5afe602b2ea0a04b66beb2c0_9de5069c5afe602b2ea0a04b66beb2c0",
          "origin": "uiproxy",
          "sandbox": [
            {
              "environment_id": 100,
              "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
              "submit_name": "https://example.com"
            }
          ],
          "state": "error",
          "user_id": "9de5069c5afe602b2ea0a04b66beb2c0",
          "user_name": "https://example.com",
          "user_uuid": "a149764d-21ee-42af-ac9f-023f5d23ab81"
        }
      ]
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/crowdstrike_falcon_intelligence:1.0.0 run < tests/checkAnalysisStatus.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/CrowdStrike Falcon https://example.com Step name: downloadArtifact\nDownloading an artifact for ID: 30f800f97aeaa8d62bdf3a6fb2b0681179a360c12e127f07038f8521461e5050...\nGetting authentication token...\n",
    "meta": {},
    "output": {
      "artifacts": [
        {
          "ioc": "44d88612fea8a8f36de82e1278abb02f",
          "source": "extracted",
          "type": "md5"
        },
        {
          "ioc": "44d88612fea8a8f36de82e1278abb02f",
          "source": "extracted",
     [...]

2022-12-01 10:08 UTC, dsliwinski-r7 approved these changes

2022-12-02 13:20 UTC, jkaluza-rapid7 approved these changes

2022-12-02 13:20 UTC, jkaluza-rapid7 commented on plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/actions/getSubmissionsIDs/action.py
> +        if limit > 5000:
You could move `5000` to a constant

2022-12-02 13:20 UTC, jkaluza-rapid7 commented on plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/actions/getSubmissionsIDs/action.py
> +            )
I think that way of handling the limit could potentially confuse the customer. Maybe we should throw an error, or use some paging if its available in their API?

2022-12-02 14:57 UTC, igorski-r7 requested changes
In general it looks great! 😃 I think some minor changes are needed. Left small comments.

2022-12-02 14:57 UTC, igorski-r7 commented on plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/actions/getReportsIDs/action.py
> +            )
Please move that `5000` to const variable

2022-12-02 14:57 UTC, igorski-r7 commented on plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/actions/getSubmissionsIDs/action.py
> +            )
Same here. Please move that `5000` to the const variable 😃

2022-12-02 14:57 UTC, igorski-r7 commented on plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/util/api.py
> +            raise PluginException(preset=PluginException.Preset.INVALID_JSON, data=e)
Just to stay with one concept. Kindly please do not use single variable names 😄 
```suggestion
        except json.decoder.JSONDecodeError as error:
            raise PluginException(preset=PluginException.Preset.INVALID_JSON, data=error)
```

2022-12-07 07:36 UTC, igorski-r7 approved these changes

2022-12-08 12:25 UTC, dlaverty-r7 commented
@mgrandys-r7 , do you mind checking the pluginValidator failure (it may just be the known timestamp issue) and resolve the conflict in the plugins/azure_ad_admin/icon_azure_ad_admin/actions/change_user_password/action.py and we can get this one merged?

2022-12-08 14:42 UTC, mgrandys-r7 commented
> @mgrandys-r7 , do you mind checking the pluginValidator failure (it may just be the known timestamp issue) and resolve the conflict in the plugins/azure_ad_admin/icon_azure_ad_admin/actions/change_user_password/action.py and we can get this one merged?

@dlaverty-r7 I've just rebased this branch so it's ready to be merged. As you mentioned the PluginValidator fails because of (in)correct date format.

2022-12-08 14:49 UTC, merged