added action to spec file and regenerated, added endpoint
rapid7/insightconnect-plugins pull request #1536
Opened 2022-12-13 13:59 UTC by TKuzas-R7

## Proposed Changes

### Description

Describe the proposed changes:

  - Create new action for Replace indicators for a Community Threat

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2023-01-04 15:08 UTC, cmcnally-r7 requested changes

2023-01-04 15:08 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/help.md
> +```
Could we get an example output put in here?

2023-01-04 15:08 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/help.md
> +* 4.2.0 - Add new action 'Replace Indicators'
Just a possible suggestion
```suggestion
* 4.2.0 - New action added: Replace Indicators
```

2023-01-04 15:08 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/replace_indicators/action.py
> +        response = request.resource_request(endpoint, "post", params={"format": "json"}, payload=params)
We'll come back to this

2023-01-04 15:08 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
> +    def replace_indicators(console_url: str, key: str):
I understand none of the rest of them have this included, maybe worth doing in another PR or including it in this one for this method and all other ones doing the same thing
```suggestion
    def replace_indicators(console_url: str, key: str) -> str:
```

2023-01-04 15:08 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/unit_test/mock.py
> +        # This should be a 400, my test requires this to be withing 200-299
Can we move this comment above the return

2023-01-05 10:00 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/unit_test/mock.py
> +        # This should be a 400, my test requires this to be withing 200-299
Just noticed something..
```suggestion
        # This should be a 400, my test requires this to be within 200-299
```

2023-01-05 10:00 UTC, cmcnally-r7 reviewed
One small thing :)

2023-01-05 10:14 UTC, cmcnally-r7 approved these changes

2023-01-05 13:50 UTC, ablakley-r7 requested changes
Looks great, just a couple of comments.

2023-01-05 13:50 UTC, ablakley-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/replace_indicators/action.py
> +            Output.REJECTED_INDICATORS: result["rejected_indicators"],
Can we use .get here and below in case of key error?

2023-01-05 13:50 UTC, ablakley-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/replace_indicators/action.py
> +            result = json.loads(response["resource"])
Can we use .get here in case of key error?

2023-01-06 11:32 UTC, ablakley-r7 approved these changes

2023-01-09 10:54 UTC, dlaverty-r7 approved these changes

2023-01-09 11:00 UTC, merged