[PLGN-97] Insight IDR - Add most_recent_first_param to Query
rapid7/insightconnect-plugins pull request #1602
Opened 2023-01-27 15:30 UTC by hpwilson-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Add the most_recent_param to the action Query

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2023-01-30 13:59 UTC, cmcnally-r7 requested changes
Just some things while you're working on it :)

2023-01-30 13:59 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/help.md
> +* 4.3.1 - Add new parameter to Query : most_recent_first
```suggestion
* 4.3.1 - `Query`: Add new parameter `most_recent_first`
```

2023-01-30 13:59 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/help.md
> + |most_recent_first|boolean|False|Order most recent first|None| true|
```suggestion
|most_recent_first|boolean|False|Order most recent first|None| true|
```

2023-01-30 13:59 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
> +Version = "4.3.1"
```suggestion
Version = "4.3.0"
```

2023-02-01 11:23 UTC, cmcnally-r7 requested changes

2023-02-01 11:23 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/help.md
> +|----|----|-----|--------|----------|----|-------|
I think this line here got modified somehow?

2023-02-01 11:23 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/action.py
> +                    # event["message"] = json.loads(event["message"].replace("\n", "\\n"))
I think we'd want to take out the print statement & comment before final version

2023-02-01 11:23 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/unit_test/mock.py
> +            == f"{Util.STUB_URL_API}/idr/v2/investigations/{STUB_INVESTIGATION_IDENTIFIER}/disposition/{STUB_DISPOSITION}"
Was this black formattings fault or has it just be indented a lot? If possible bring it back but if it's due to `black` then leave it as is

2023-02-01 13:48 UTC, cmcnally-r7 requested changes
Getting there 👍

2023-02-01 13:48 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/util/formatting.py
> +    return new_message
Add your return type hint and add a doc string for this function
```suggestion
def refactor_message(message: dict) -> return type:
    """
    <x,y,z>
    :param <>: ...
    :return: ...
    """
    new_message = json.loads(str(message).replace("\n", "\\n").replace("'", '"'))
    return new_message
```

2023-02-01 13:48 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/unit_test/test_query.py
> +    @classmethod
Can you run coverage to find out what percentage of the code is being tested here?

2023-02-01 13:48 UTC, cmcnally-r7 commented on plugins/rapid7_insightidr/help.md
> +|Name|Type| Default |Required| Description |Enum|Example|
Seems the formatting for this line has now gone off, try and use the comparison git shows to fix it up 😄

2023-02-01 14:30 UTC, igorski-r7 requested changes
In general looks fine 😄 Some comments left.

2023-02-01 14:30 UTC, igorski-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/action.py
> +        twenty_fourth_november = 1669248000
Could you please move that variables as a constants?

2023-02-01 14:30 UTC, igorski-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/action.py
> +            from_var = twenty_fourth_november
What in the case we set `most_recent_first` to `False`? It will still count for less than 3 months 😄

2023-02-01 14:30 UTC, igorski-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/util/formatting.py
> +def refactor_message(message: dict):
Please add the `Dict` type from `typing` i.e. `Dict[str, str]` and the return typehint. Kindly please add the doc-string as well 😄

2023-02-01 14:30 UTC, igorski-r7 commented on plugins/rapid7_insightidr/unit_test/test_query.py
> +        }
```suggestion
    def setUpClass(cls) -> None:
        cls.params = {
            "id": "1b1a111d-d1fb-1a12-1651-eb1ff61a651a",
            "not_found_id": "22b2b22b-222b-222b-2222-b2bb2bbb2b2b",
            "most_recent_first_true": True,
            "most_recent_first_false": False,
        }
        cls.connection_params = {
            ConnectionInput.REGION: "United States 1",
            ConnectionInput.API_KEY: {"secretKey": "api_key"},
        }
```

2023-02-02 12:17 UTC, igorski-r7 requested changes

2023-02-02 12:17 UTC, igorski-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/action.py
> +        if most_recent_first and (time_now - three_months_seconds) < twenty_fourth_november:
```suggestion
        if most_recent_first and from_var < twenty_fourth_november:
```

2023-02-02 12:17 UTC, igorski-r7 commented on plugins/rapid7_insightidr/komand_rapid7_insightidr/util/constants.py
> +twenty_fourth_november = 1669248000
In general constants are written capitalized
```suggestion
TWENTY_FOURTH_NOVEMBER = 1669248000
```

2023-02-02 13:17 UTC, igorski-r7 approved these changes

2023-02-02 14:19 UTC, cmcnally-r7 approved these changes

2023-02-02 14:21 UTC, llaszuk-r7 approved these changes

2023-02-02 14:21 UTC, merged