[PLGN-166] RDAP - Domain Lookup, IP Address Lookup, ASN Lookup: Updated action outputs, refactored and prettified
rapid7/insightconnect-plugins pull request #1668
Opened 2023-03-13 09:31 UTC by igorski-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - `Domain Lookup`, `IP Address Lookup`, `ASN Lookup`: Updated action outputs, refactored and prettified

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [X] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [X] Screenshot of job output with the plugin changes
- [X] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [X] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [X] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [X] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [X] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [X] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [X] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [X] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [X] Work fully completed
- [X] Functional
  - [X] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [X] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [X] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [X] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [X] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

### Run

<details>

```
{
  "entities": [
    {
      "fullname": "RESERVED-Internet Assigned Numbers Authority",
      "handle": "376",
      "roles": [
        "registrar"
      ]
    }
  ],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "1995-08-14T04:00:00Z"
    },
    {
      "eventAction": "expiration",
      "eventDate": "2023-08-13T04:00:00Z"
    },
    {
      "eventAction": "last changed",
      "eventDate": "2022-08-14T07:01:31Z"
    },
    {
      "eventAction": "last update of RDAP database",
      "eventDate": "2023-03-13T09:13:12Z"
    }
  ],
  "name": "EXAMPLE.COM",
  "nameservers": [
    "A.IANA-SERVERS.NET",
    "B.IANA-SERVERS.NET"
  ],
  "publicIds": [
    {
      "identifier": "376",
      "type": "IANA Registrar ID"
    }
  ],
  "registryDomainId": "2336799_DOMAIN_COM-VRSN",
  "secureDns": {
    "delegationSigned": true,
    "dsData": [
      {
        "algorithm": 8,
        "digest": "F78CF3344F72137235098ECBBD08947C2C9001C7F6A085A17F518B5D8F6B916D",
        "digestType": 2,
        "keyTag": 31406
      },
      {
        "algorithm": 8,
        "digest": "CDE0D742D6998AA554A92D890F8184C698CFAC8A26FA59875A990C03E576343C",
        "digestType": 2,
        "keyTag": 31589
      },
      {
        "algorithm": 8,
        "digest": "B6225AB2CC613E0DCA7962BDC2342EA4F1B56083",
        "digestType": 1,
        "keyTag": 43547
      },
      {
        "algorithm": 8,
        "digest": "615A64233543F66F44D68933625B17497C89A70E858ED76A2145997EDF96A918",
        "digestType": 2,
        "keyTag": 43547
      },
      {
        "algorithm": 8,
        "digest": "3490A6806D47F17A34C29E2CE80E8A999FFBE4BE",
        "digestType": 1,
        "keyTag": 31589
      },
      {
        "algorithm": 8,
        "digest": "189968811E6EBA862DD6C209F75623D8D9ED9142",
        "digestType": 1,
        "keyTag": 31406
      }
    ]
  },
  "status": [
    "client delete prohibited",
    "client transfer prohibited",
    "client update prohibited"
  ]
}
```

<summary>
docker run --rm -i rapid7/rdap:2.0.0 run < tests/domainLookup.json
</summary>
</details>

<details>

```
{
  "ansCountryCode": "US",
  "ansRegistry": "ripencc",
  "asn": "15133",
  "asnCidr": "192.168.0.0/24",
  "asnDate": "2008-06-02",
  "asnDescription": "EDGECAST, US",
  "country": "EU",
  "endAddress": "93.184.216.255",
  "entities": [
    {
      "email": "user@example.com",
      "fullname": "Abuse-C Role",
      "handle": "AR111111",
      "kind": "group",
      "roles": [
        "abuse"
      ]
    },
    {
      "handle": "MNT-EDGECAST",
      "roles": [
        "registrant"
      ]
    },
    {
      "handle": "MNT-EDGECAST",
      "roles": [
        "registrant"
      ]
    },
    {
      "handle": "DS7892-RIPE",
      "roles": [
        "technical",
        "administrative"
      ]
    }
  ],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "2012-06-22T21:48:41Z"
    },
    {
      "eventAction": "last changed",
      "eventDate": "2012-06-22T21:48:41Z"
    }
  ],
  "handle": "",
  "ipVersion": "v4",
  "name": "EDGECAST-NETBLK-03",
  "parentHandle": "",
  "port43": "whois.ripe.net",
  "startAddress": "",
  "status": [
    "active"
  ],
  "type": "ASSIGNED PA"
}
```

<summary>
docker run --rm -i rapid7/rdap:2.0.0 run < tests/ipLookup.json
</summary>
</details>

<details>

```
{
  "endAutnum": 15133,
  "entities": [
    {
      "fullname": "Edgecast Inc.",
      "handle": "EDGEC-25",
      "kind": "org",
      "roles": [
        "registrant"
      ]
    },
    {
      "email": "user@example.com",
      "fullname": "Abuse",
      "handle": "ABUSE8588-ARIN",
      "kind": "group",
      "organization": "Abuse",
      "phone": "+1-111-110-1100",
      "roles": [
        "abuse"
      ]
    },
    {
      "email": "user2@example.com",
      "fullname": "Network Operations Center",
      "handle": "NOC2475-ARIN",
      "kind": "group",
      "organization": "Network Operations Center",
      "phone": "+1-111-111-1111",
      "roles": [
        "administrative",
        "routing",
        "technical",
        "noc",
        "dns"
      ]
    }
  ],
  "events": [
    {
      "eventAction": "last changed",
      "eventDate": "2022-05-27T12:21:34-04:00"
    },
    {
      "eventAction": "registration",
      "eventDate": "2007-03-19T15:41:06-04:00"
    }
  ],
  "handle": "AS15133",
  "name": "EDGECAST",
  "port43": "whois.arin.net",
  "startAutnum": 15133,
  "status": [
    "active"
  ]
} [...]

2023-03-13 11:30 UTC, dlaverty-r7 approved these changes
@igorski-r7 , Lgtm, just a couple of re-wording suggestions.

2023-03-13 11:30 UTC, dlaverty-r7 commented on plugins/rdap/help.md
> +* 2.0.0 - `Domain Lookup`, `IP Address Lookup`, `ASN Lookup`: Updated action outputs, refactored and prettified
Reword 'Updated action outputs, refactored and prettified' -> 'Updated action outputs and refactored.

2023-03-13 11:30 UTC, dlaverty-r7 commented on plugins/rdap/unit_test/test_domainLookup.py
> +    def test_domain_lockup_raise_exception(
Rename lockup->lookup

2023-03-13 12:19 UTC, llaszuk-r7 requested changes
just few questions

2023-03-13 12:19 UTC, llaszuk-r7 commented on plugins/rdap/icon_rdap/util/helpers.py
> +            "country_name": vcard_address[6],
can we meet IndexError here?
can you prevent from IndexError just in case?

2023-03-13 12:19 UTC, llaszuk-r7 commented on plugins/rdap/icon_rdap/util/helpers.py
> +_VCARD_ADDRESS_KEY_NAME = "address"
to consider: change variables name to without underscore

2023-03-14 09:11 UTC, dlaverty-r7 approved these changes

2023-03-14 09:52 UTC, llaszuk-r7 approved these changes

2023-03-14 10:00 UTC, merged