[PLGN-141] Ivanti Service Manager Update
rapid7/insightconnect-plugins pull request #1702
Opened 2023-04-03 16:54 UTC by hpwilson-r7

## Proposed Changes

### Description

Describe the proposed changes:
The updates for this ticket were the following enhancements:

New Functionality Added to Plugin
Added Search Incidents action
Added Get Incident action
Added trigger New Incident

Testing
Added unit tests for all pre-existing and new actions
Added unit test for new trigger

Defects Fixed:
Issue: Misleading error for multiple templates
Root cause: Wrong error returned
Solution: Replace with "Multiple service request templates found"

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2023-04-04 10:43 UTC, cmcnally-r7 commented on plugins/ivanti_service_manager/icon_ivanti_service_manager/util/api.py
> +            f"try again.",
Did you mean to split this up?

2023-04-04 12:09 UTC, igorski-r7 requested changes

2023-04-04 12:09 UTC, igorski-r7 commented on plugins/ivanti_service_manager/unit_test/test_add_note.py
> +        }
I suggest moving that parameters to a const variable instead of putting that to `setUpClass`

2023-04-04 12:09 UTC, igorski-r7 commented on plugins/ivanti_service_manager/unit_test/test_create_incident.py
> +        }
Same here

2023-04-04 12:09 UTC, igorski-r7 commented on plugins/ivanti_service_manager/unit_test/test_create_incident.py
> +        self.assertEqual(exception.exception.cause, cause)
Kindly please use `parameterized` to parametrise that tests 😄

2023-04-04 12:09 UTC, igorski-r7 commented on plugins/ivanti_service_manager/unit_test/test_create_service_request.py
> +            self.assertEqual(exception.exception.cause, cause)
Please use `parameterized` here 😄

2023-04-05 07:59 UTC, igorski-r7 commented on plugins/ivanti_service_manager/help.md
Still seems no to be pretty printed with 2 indentation 😄

2023-04-05 09:34 UTC, igorski-r7 commented on plugins/ivanti_service_manager/help.md
> +}
Is it pretty printed? 😄

2023-04-05 09:36 UTC, TKuzas-R7 approved these changes

2023-04-05 09:47 UTC, igorski-r7 approved these changes

2023-04-05 11:23 UTC, cmcnally-r7 approved these changes

2023-04-05 13:25 UTC, merged