Armorblox plugin
rapid7/insightconnect-plugins pull request #1713
Opened 2023-04-14 16:32 UTC by urajat

## Proposed Changes

### Description

Describe the proposed changes:

  - Armorblox plugin for InsightConnect

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2023-04-14 16:38 UTC, urajat commented
cc @SamhithaTatipalli @absanjay2022

2023-04-18 16:11 UTC, cmcnally-r7 requested changes

2023-04-18 16:11 UTC, cmcnally-r7 commented on plugins/armorblox/icon_armorblox/util/api.py
> +        params = {
```suggestion
    def get_incidents(self, from_date: str = None, to_date: str = None):
        """
        <description>
        
        :param from_date: <description>
        :param to_date: <description>
        
        :return: <description>
        """
        params = {
```

2023-04-18 16:11 UTC, cmcnally-r7 commented on plugins/armorblox/unit_test/payloads/get_remediation_action.json
> +}
```suggestion
}

```

2023-04-19 08:27 UTC, igorski-r7 requested changes
In general looks good. A few minor changes required.

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/.CHECKSUM
Kindly, please add new empty line at the end of file

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/icon_armorblox/connection/connection.py
> +        self.logger.info(params)
We shouldn't be logging or connection parameters 😄 Please remove it

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/icon_armorblox/connection/connection.py
> +            logger=self.logger,
```suggestion
            api_key = params.get(Input.API_KEY, {}).get('secretKey'),
            tenant_name = params.get(Input.TENANT_NAME),
            logger=self.logger,
```

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/icon_armorblox/connection/connection.py
> +        return result
```suggestion
        try:
            self.api.test_api()
            return {"success": True}
        except PluginException as error:
            raise ConnectionTestException(
                cause=error.cause, assistance=error.assistance, data=error.data
            )
```

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/icon_armorblox/triggers/get_incidents/trigger.py
> +        fetch_interval = int(params.get(Input.INTERVAL))
I suggest adding the default value 
```suggestion
        fetch_interval = params.get(Input.INTERVAL, DEFAULT_INTERVAL_VALUE)
```

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/icon_armorblox/triggers/get_incidents/trigger.py
> +            self.send({Output.INCIDENTS: events})
Should we send data if there are no events at all? 😄 
```suggestion
            events = self.connection.api.get_incidents(from_date=last_fetch_time, to_date=current_time)
            if events:
                self.send({Output.INCIDENTS: events})
            else:
                self.logger.info(f"No events retrieved. Sleeping for {fetch_interval} seconds....")
```

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/icon_armorblox/util/api.py
> +            print('Exception has occurred for incorrect credentials. ' + str(credentials_exp))
I don't think printing is a good practise here. Kindly, please raise `PluginException` instead.

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/plugin.spec.yaml
Newline at the end of file please 😄

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/unit_test/test_get_remediation_action.py
Please add newline at the end of file 😄

2023-04-19 08:27 UTC, igorski-r7 commented on plugins/armorblox/unit_test/test_get_remediation_action.py
> +        self.assertEqual(actual, expected)
Could you please add some more tests for catching the `PluginExceptions`?

2023-05-19 13:10 UTC, dlaverty-r7 commented
@urajat / @SamhithaTatipalli , would you mind closing this PR out if the newer PR supercedes it?

2023-06-15 13:55 UTC, closed without merging

2023-06-15 13:55 UTC, dlaverty-r7 commented
Closing out as superseded by newer PR.