Cybereason output fix
rapid7/insightconnect-plugins pull request #1727
Opened 2023-04-25 15:26 UTC by TKuzas-R7

### The updates for this ticket were the following refactored files:
**Files Refactored:**
- Output for plugin in plugin spec file and files effected by regenerating
  
**Testing**
- icon test
insert picture

2023-04-26 14:15 UTC, hpwilson-r7 approved these changes

2023-04-27 09:12 UTC, cmcnally-r7 approved these changes

2023-04-27 09:37 UTC, igorski-r7 requested changes

2023-04-27 09:37 UTC, igorski-r7 commented on plugins/cybereason/help.md
> +  "$success": true,
I don't think we need to include that here 😄 
```suggestion
```

2023-04-27 09:37 UTC, igorski-r7 commented on plugins/cybereason/help.md
> +    "hasMoreResults": false,
What about the pagination? Do we handle it anywhere? 😄

2023-04-27 11:07 UTC, igorski-r7 approved these changes

2023-04-27 12:49 UTC, merged