[PLGN-222] Servicenow - Updated the vulnerability source from Application Vulnerability Item to Vulnerability Item
rapid7/insightconnect-plugins pull request #1775
Opened 2023-05-16 11:58 UTC by igorski-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Updated the vulnerability source from Application Vulnerability Item to Vulnerability Item

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [X] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [X] Screenshot of job output with the plugin changes
- [X] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [X] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [X] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [X] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [X] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [X] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [X] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [X] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [X] Work fully completed
- [X] Functional
  - [X] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [X] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [X] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [X] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [X] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2023-05-16 12:37 UTC, hpwilson-r7 approved these changes

2023-05-16 13:57 UTC, ablakley-r7 requested changes
Changes look great! I hope you don't mind, I have suggested rephrasing some of the output/input descriptions.

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The reference of vulnerability found
```suggestion
        description: The reference of the found vulnerability
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The IP address of source the vulnerability was found
```suggestion
        description: The IP address of the source where the vulnerability was found
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The name of source DNS the vulnerability was found
```suggestion
        description: The name of source DNS where the vulnerability was found
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The time that represents the vulnerability was last found, in ISO format
```suggestion
        description: The time that represents when the vulnerability was last found, in ISO format
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The reference of vulnerability found
```suggestion
        description: The reference of the found vulnerability
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The IP address of source the vulnerability was found
```suggestion
        description: The IP address of the source where the vulnerability was found
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The name of source DNS the vulnerability was found
```suggestion
        description: The name of the source DNS where the vulnerability was found
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: The time that represents the vulnerability was last found, in ISO format
```suggestion
        description: The time that represents when the vulnerability was last found, in ISO format
```

2023-05-16 13:57 UTC, ablakley-r7 commented on plugins/servicenow/plugin.spec.yaml
> +        description: List of JSON object containing system ID of updated vulnerability and representing changed fields (map of field name to previous and current values)
```suggestion
        description: List of JSON objects containing the system ID of the updated vulnerability and representation of the changed fields (map of field name from previous to current values)
```

2023-05-16 14:52 UTC, cmcnally-r7 reviewed
Should the plugin version also be increased?

2023-05-17 09:32 UTC, igorski-r7 commented
> Should the plugin version also be increased?

It was bumped in the previous PR. This is the continuation 😄

2023-05-17 10:04 UTC, cmcnally-r7 approved these changes

2023-05-17 15:03 UTC, merged