Trend Micro Vision One InsightConnect Plugin 1.0.2. Update
rapid7/insightconnect-plugins pull request #1953
Opened 2023-08-23 14:47 UTC by pedro-securo

## Proposed Changes

### Description

Describe the proposed changes:

  - This update entails a general refactoring of many of the actions that take arrays of inputs.
  - Resulting in a reduced number of API calls needed to produce the same results.
  - Enabled Array of inputs for the Get Endpoint Data where before it accepted just one.
  - Minor cosmetic and bug fixes.
  - Enhanced help.md

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``rapid7/insightconnect-python-3-38-slim-plugin:{sdk-version-num}`` and ``rapid7/insightconnect-python-3-38-plugin:{sdk-version-num}``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``insight-plugin validate`` which calls ``icon_validate`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `insight-plugin samples`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `insight-plugin validate` and make sure everything passes
2. Run the assessment tool: `insight-plugin run -A`. For single action validation: `insight-plugin run tests/{file}.json -A`
3. Copy (`insight-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2023-08-25 14:29 UTC, pedro-securo commented
trendmicro_visionone % icon-plugin run -T all
INFO[0000] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/add_alert_note.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:00 [info     ] Connect: Connecting...
2023-08-25 14:23:00 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:00 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: add_alert_note
2023-08-25 14:23:00 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:00 [info     ] Making API Call...
2023-08-25 14:23:01 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0007] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0007] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/add_to_block_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:08 [info     ] Connect: Connecting...
2023-08-25 14:23:08 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:08 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: add_to_block_list
2023-08-25 14:23:08 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:08 [info     ] Making API Call...
2023-08-25 14:23:08 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0015] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0015] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/add_to_exception_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:16 [info     ] Connect: Connecting...
2023-08-25 14:23:16 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:16 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: add_to_exception_list
2023-08-25 14:23:16 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:16 [info     ] Making API Call...
2023-08-25 14:23:16 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0023] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0023] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/add_to_suspicious_list.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:24 [info     ] Connect: Connecting...
2023-08-25 14:23:24 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:24 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: add_to_suspicious_list
2023-08-25 14:23:24 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:24 [info     ] Making API Call...
2023-08-25 14:23:24 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0031] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0031] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/collect_file.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:32 [info     ] Connect: Connecting...
2023-08-25 14:23:32 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:32 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: collect_file
2023-08-25 14:23:32 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:32 [info     ] Making API Call...
2023-08-25 14:23:32 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0039] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0039] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/delete_email_message.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:40 [info     ] Connect: Connecting...
2023-08-25 14:23:40 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:40 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: delete_email_message
2023-08-25 14:23:40 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:40 [info     ] Making API Call...
2023-08-25 14:23:40 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0047] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0047] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/disable_account.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:48 [info     ] Connect: Connecting...
2023-08-25 14:23:48 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:48 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: disable_account
2023-08-25 14:23:48 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:48 [info     ] Making API Call...
2023-08-25 14:23:49 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0056] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0056] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/download_sandbox_analysis_result.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:23:56 [info     ] Connect: Connecting...
2023-08-25 14:23:57 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:57 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: download_sandbox_analysis_result
2023-08-25 14:23:57 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:23:57 [info     ] Making API Call...
2023-08-25 14:23:57 [info     ] Connection Successfully Established...
{"body": {"log": "", "status": "ok", "meta": {}, "output": "SUCCESS"}, "version": "v1", "type": "action_event"}
ERRO[0064] Pretty Print JSON Unmarshal json: cannot unmarshal string into Go value of type map[string]interface {} Value: "SUCCESS" 
INFO[0064] Running command:  docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 test < tests/download_sandbox_investigation_package.json 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-08-25 14:24:05 [info     ] Connect: Connecting...
2023-08-25 14:24:05 [info     ] Initializing PYTMV1 Client...
2023-08-25 14:24:05 [info     ] trendmicro/Trend Micro Vision One:1.0.2. Step name: download_sandbox_investigation_package
 [...]

2023-08-29 14:43 UTC, pedro-securo commented
Get Task Results now give job/action specific results that are more extensive.
![extended results](https://github.com/rapid7/insightconnect-plugins/assets/131287358/1a896f43-ebab-44d2-82c6-c2e3c0fe6b89)

2023-08-29 18:23 UTC, pedro-securo commented
Get Endpoint Data now takes array of inputs.
![get endpoint data array of inputs](https://github.com/rapid7/insightconnect-plugins/assets/131287358/dc34bb72-1ee5-48c8-b32a-8b0750f036bb)

2023-10-18 12:12 UTC, cmcnally-r7 commented
Hi @pedro-securo, I will start reviewing the PR - while I do this, kindly rebase your branch.

Also, when copying and pasting docker run commands into comments in your PR, try following the steps found in the 'Assessment' section of the `help.md` above. It will require you to install & use the new tooling that replaces `icon-plugin`. 

```
Run the assessment tool: insight-plugin run -A. 
For single action validation: insight-plugin run tests/{file}.json -A
Copy (insight-plugin ... | pbcopy) and paste the output in a new post on this PR
```
This will make the outputs much more readable for everyone 😃

2023-10-18 12:37 UTC, pedro-securo commented
> Hi @pedro-securo, I will start reviewing the PR - while I do this, kindly rebase your branch.
> 
> Also, when copying and pasting docker run commands into comments in your PR, try following the steps found in the 'Assessment' section of the `help.md` above. It will require you to install & use the new tooling that replaces `icon-plugin`.
> 
> ```
> Run the assessment tool: insight-plugin run -A. 
> For single action validation: insight-plugin run tests/{file}.json -A
> Copy (insight-plugin ... | pbcopy) and paste the output in a new post on this PR
> ```
> 
> This will make the outputs much more readable for everyone 😃

Has this new tool also been released for Apple Silicon based machines?
As I am not having luck following the instructions.
<img width="1233" alt="Screenshot 2023-10-18 at 14 33 16" src="https://github.com/rapid7/insightconnect-plugins/assets/131287358/326e87d1-337e-419d-9ac2-3d36052c3976">

2023-10-18 12:50 UTC, cmcnally-r7 commented
> > Hi @pedro-securo, I will start reviewing the PR - while I do this, kindly rebase your branch.
> > Also, when copying and pasting docker run commands into comments in your PR, try following the steps found in the 'Assessment' section of the `help.md` above. It will require you to install & use the new tooling that replaces `icon-plugin`.
> > ```
> > Run the assessment tool: insight-plugin run -A. 
> > For single action validation: insight-plugin run tests/{file}.json -A
> > Copy (insight-plugin ... | pbcopy) and paste the output in a new post on this PR
> > ```
> > 
> > 
> > This will make the outputs much more readable for everyone 😃
> 
> Has this new tool also been released for Apple Silicon based machines? As I am not having luck following the instructions. <img alt="Screenshot 2023-10-18 at 14 33 16" width="1233" src="https://user-images.githubusercontent.com/131287358/276247964-326e87d1-337e-419d-9ac2-3d36052c3976.png">

https://pypi.org/project/insight-plugin/

2023-10-18 13:59 UTC, pedro-securo commented
> > > Hi @pedro-securo, I will start reviewing the PR - while I do this, kindly rebase your branch.
> > > Also, when copying and pasting docker run commands into comments in your PR, try following the steps found in the 'Assessment' section of the `help.md` above. It will require you to install & use the new tooling that replaces `icon-plugin`.
> > > ```
> > > Run the assessment tool: insight-plugin run -A. 
> > > For single action validation: insight-plugin run tests/{file}.json -A
> > > Copy (insight-plugin ... | pbcopy) and paste the output in a new post on this PR
> > > ```
> > > 
> > > 
> > > This will make the outputs much more readable for everyone 😃
> > 
> > 
> > Has this new tool also been released for Apple Silicon based machines? As I am not having luck following the instructions. <img alt="Screenshot 2023-10-18 at 14 33 16" width="1233" src="https://user-images.githubusercontent.com/131287358/276247964-326e87d1-337e-419d-9ac2-3d36052c3976.png">
> > Currently only available as a Python module install but which then runs on CLI just fine.
> 
> https://pypi.org/project/insight-plugin/
> 
> However for convenience you can also do this with `icon-plugin`, checkout the help for the `run` command: `icon-plugin run --help`
> 
> ```
> -A, --assessment         Create PR assessment around the given -T/-R options.
> ```
> 
> Looking at the command you have run, you just simply need to append an `-A` flag in your command and pipe it to `pbcopy` like so `icon-plugin run -T -A all | pbcopy`

I'm trying to figure out how to use the python plugin in a similar fashion, 
as icon-plugin seems to give some weird response.

<img width="778" alt="Screenshot 2023-10-18 at 15 44 28" src="https://github.com/rapid7/insightconnect-plugins/assets/131287358/16394c13-c0c3-485e-833f-8448587f6924">

2023-10-18 15:17 UTC, cmcnally-r7 commented
> > > > Hi @pedro-securo, I will start reviewing the PR - while I do this, kindly rebase your branch.
> > > > Also, when copying and pasting docker run commands into comments in your PR, try following the steps found in the 'Assessment' section of the `help.md` above. It will require you to install & use the new tooling that replaces `icon-plugin`.
> > > > ```
> > > > Run the assessment tool: insight-plugin run -A. 
> > > > For single action validation: insight-plugin run tests/{file}.json -A
> > > > Copy (insight-plugin ... | pbcopy) and paste the output in a new post on this PR
> > > > ```
> > > > 
> > > > 
> > > > This will make the outputs much more readable for everyone 😃
> > > 
> > > 
> > > Has this new tool also been released for Apple Silicon based machines? As I am not having luck following the instructions. <img alt="Screenshot 2023-10-18 at 14 33 16" width="1233" src="https://user-images.githubusercontent.com/131287358/276247964-326e87d1-337e-419d-9ac2-3d36052c3976.png">
> > > Currently only available as a Python module install but which then runs on CLI just fine.
> > 
> > 
> > https://pypi.org/project/insight-plugin/
> > However for convenience you can also do this with `icon-plugin`, checkout the help for the `run` command: `icon-plugin run --help`
> > ```
> > -A, --assessment         Create PR assessment around the given -T/-R options.
> > ```
> > 
> > 
> > Looking at the command you have run, you just simply need to append an `-A` flag in your command and pipe it to `pbcopy` like so `icon-plugin run -T -A all | pbcopy`
> 
> I'm trying to figure out how to use the python plugin in a similar fashion, as icon-plugin seems to give some weird response.
> 
> <img alt="Screenshot 2023-10-18 at 15 44 28" width="778" src="https://user-images.githubusercontent.com/131287358/276278309-16394c13-c0c3-485e-833f-8448587f6924.png">
> To use the Python plugin, simply pip install then use it in the CLI the same way as you would use `icon-plugin`.
> 
> ## The response you are getting is in markdown, but if you were to add ` | pbcopy` to your command and paste it into the `help.md` it will display in a nicely formatted drop-down menu.
> Right. So do you intend me to pbcopy and paste here those few lines of markdown? Since the -T flag doesn't seem to be defined and the pip installed insight-plugin doesn't seem to accept the same flags or command format.

Yes if you could it would be great. It will make the results you posted above much more readable. Here is an example I used on our IDR plugin:

## Assessment

### Run

<details>

```
{
  "body": {
    "log": "",
    "status": "ok",
    "meta": {},
    "output": {
      "saved_query": {
        "id": "00000000-0000-8f6e-0000-000000000000",
        "name": "Saved Query",
        "leql": {
          "statement": "where("aaaaa-aaaaaa-aaaaa">=800)",
          "during": {}
        },
        "logs": [
          "aaaaa-aaaaaa-aaaaa",
          "aaaaa-aaaaaa-aaaaa",
          "aaaaa-aaaaaa-aaaaa",
          "aaaaa-aaaaaa-aaaaa",
          "aaaaa-aaaaaa-aaaaa"
        ]
      }
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i rapid7/rapid7_insightidr:5.1.2 --debug run < tests/get_a_saved_query.json
</summary>
</details>






### UI

Screenshots of the plugin being used in InsightConnect workflows (for validating functionality in the UI) go below this line.

#### Workflow Builder


#### Job


#### Artifact

2023-10-19 12:47 UTC, cmcnally-r7 requested changes
One last thing but other than that LGTM 😄 

I tried to rebase from my end but do not have access to push to your repository

2023-10-19 12:48 UTC, pedro-securo commented
> insight-plugin run tests/get_a_saved_query.json -A | pbcopy



## Assessment

### Run

<details>

```
{
  "body": {
    "log": "",
    "status": "ok",
    "meta": {},
    "output": {
      "action": "isolate",
      "account": "test",
      "created_date_time": "2023-10-19T12:45:10Z",
      "agent_guid": "SANITIZED",
      "id": "00000004",
      "last_action_date_time": "2023-10-19T12:45:10Z",
      "resource_location": "",
      "status": "succeeded",
      "description": "task description",
      "endpoint_name": "trend-host-1",
      "expired_date_time": "",
      "file_path": "",
      "file_sha1": "",
      "file_sha256": "",
      "file_size": 0,
      "filename": "",
      "image_path": "",
      "password": "",
      "pid": 0,
      "sandbox_task_id": "",
      "tasks": [],
      "url": ""
    }
  },
  "version": "v1",
  "type": "action_event"
}
```

<summary>
docker run --rm -i trendmicro/trendmicro_visionone:1.0.2 --debug run < tests/get_task_result.json
</summary>
</details>






### UI

Screenshots of the plugin being used in InsightConnect workflows (for validating functionality in the UI) go below this line.

#### Workflow Builder


#### Job


#### Artifact

2023-10-19 12:59 UTC, pedro-securo commented
> One last thing but other than that LGTM 😄
> 
> I tried to rebase from my end but do not have access to push to your repository

Okay I will try to do another rebase right now then.

2023-10-19 13:43 UTC, igorski-r7 reviewed
LGTM, but please rebase your branch with ours latest develop 😄

2023-10-19 14:00 UTC, pedro-securo commented
> LGTM, but please rebase your branch with ours latest develop 😄

I seem to be on the latest already. 

<img width="1040" alt="Screenshot 2023-10-19 at 15 56 54" src="https://github.com/rapid7/insightconnect-plugins/assets/131287358/dd93e83c-828a-455b-8cb6-d998fbf7e82d">

2023-10-24 08:26 UTC, cmcnally-r7 approved these changes

2023-10-24 08:39 UTC, merged