soar_17161 Removing deprecated fields and adding help.md
rapid7/insightconnect-plugins pull request #2600
Opened 2024-06-26 11:14 UTC by rmurray-r7

## Proposed Changes

### Description

Due to [Duo API change](https://duo.com/docs/adminapi#create-user) the `"firstname"` and `"lastname" `fields are no longer needed to I have updated the following:

https://rapid7.atlassian.net/browse/SOAR-17161
-   Changed the Schema's which contained firstname and lastname
-    SDK has been bumped to 5.5.5
-    Changed the Unit Test's which contained firstname and lastname

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [x] Unit tests written for any new or updated code
I have ran Unit Test's locally and have updated tests accordingly to reflect new changes

#### In-Product Tests

I have tested locally using the Docker container (Postman)

Add user Test:
![image](https://github.com/rapid7/insightconnect-plugins/assets/171815685/b92edb5f-67f3-4831-8058-829801c1ec55)

Retrieving User via ID:
![image](https://github.com/rapid7/insightconnect-plugins/assets/171815685/bfd60b91-3729-4282-a7c9-bd6146f209fe)

Modifying a User:
![image](https://github.com/rapid7/insightconnect-plugins/assets/171815685/6f7fae7b-2594-4d91-afbc-379719fe55ce)

Retrieve a User via Username:
![image](https://github.com/rapid7/insightconnect-plugins/assets/171815685/6cf28d47-e1d1-4766-96f2-1989a05315d1)

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [x] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [x] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``rapid7/insightconnect-python-3-38-slim-plugin:{sdk-version-num}`` and ``rapid7/insightconnect-python-3-38-plugin:{sdk-version-num}``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [x] For docs, validate markdown with ``insight-plugin validate`` which calls ``icon_validate`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [x] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `insight-plugin samples`
  - [x] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [x] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `insight-plugin validate` and make sure everything passes
2. Run the assessment tool: `insight-plugin run -A`. For single action validation: `insight-plugin run tests/{file}.json -A`
3. Copy (`insight-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2024-06-26 11:21 UTC, rbowden-r7 commented on plugins/duo_admin/help.md
> +  "user": {}
This example looks to have been removed during the refresh

2024-06-26 11:21 UTC, rbowden-r7 commented on plugins/duo_admin/help.md
> +* The following information are required for using `Duo Admin` plugin:
I don't think this first line needed to be a buller point

2024-06-27 07:56 UTC, ablakley-r7 approved these changes

2024-06-27 09:38 UTC, dlaverty-r7 approved these changes

2024-06-27 09:40 UTC, cmcnally-r7 requested changes

2024-06-27 09:40 UTC, cmcnally-r7 commented on plugins/duo_admin/plugin.spec.yaml
> +- "[Duo Admin API](https://duo.com/docs/adminapi)"
```suggestion
links:
- "[Duo Security](https://duo.com/)"
references:
- "[Duo Admin API](https://duo.com/docs/adminapi)"
```

2024-06-27 10:01 UTC, cmcnally-r7 approved these changes

2024-06-27 10:23 UTC, merged