Soar 17274 html
rapid7/insightconnect-plugins pull request #2653
Opened 2024-07-23 14:52 UTC by rmurray-r7

## Proposed Changes

### Description

Describe the proposed changes:

  -

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``rapid7/insightconnect-python-3-38-slim-plugin:{sdk-version-num}`` and ``rapid7/insightconnect-python-3-38-plugin:{sdk-version-num}``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``insight-plugin validate`` which calls ``icon_validate`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `insight-plugin samples`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `insight-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `insight-plugin validate` and make sure everything passes
2. Run the assessment tool: `insight-plugin run -A`. For single action validation: `insight-plugin run tests/{file}.json -A`
3. Copy (`insight-plugin ... | pbcopy`) and paste the output in **a new post** on this PR
4. Add required screenshots from the In-Product Tests section

2024-07-25 12:57 UTC, cmcnally-r7 requested changes

2024-07-25 12:57 UTC, cmcnally-r7 commented on plugins/html/Dockerfile
> -RUN apt-get update && apt-get install -y pandoc texlive lmodern --no-install-recommends
and this

2024-07-25 12:57 UTC, cmcnally-r7 commented on plugins/html/Dockerfile
> -USER root
if this is needed for SSL then maybe we should keep this

2024-07-25 12:57 UTC, cmcnally-r7 commented on plugins/html/help.md
> +* 1.2.6 - SDK Bump | Addressing Snyk vulnerabilities (bumping setuptools to 70.0.0) | Fixing Unit Test (pypandoc convert method deprecated)
You can omit the bracketed details
```suggestion
* 1.2.6 - SDK Bump | Addressing Snyk vulnerabilities | Fix Unit Tests 
```

2024-07-25 14:03 UTC, cmcnally-r7 commented on plugins/html/Dockerfile
> -ENV REQUESTS_CA_BUNDLE  /etc/ssl/certs/ca-certificates.crt
After looking, these are fine to delete since there is no connection

2024-07-25 14:03 UTC, cmcnally-r7 commented on plugins/html/Dockerfile
> -RUN apt-get update && apt-get install -y pandoc texlive lmodern --no-install-recommends
Keep this though its important

2024-07-25 14:04 UTC, cmcnally-r7 commented on plugins/html/Dockerfile
> -USER root
yep keep this as nobody, safe to change since theres no connection.
Not sure why this was root or the SSL comment was there to begin with

2024-07-25 14:26 UTC, rmurray-r7 commented
Validator is failing as the plugin contains:   `10 RUN apt-get update && apt-get install -y pandoc texlive lmodern --no-install-recommends` in the Dockerfile and since the plugin spec has:  `10 cloud_ready: true`, it is failing. 

As the unit tests uses `pypandoc`, it is dependant on `pandoc` so the install is required: https://pypi.org/project/pypandoc/

2024-07-25 14:33 UTC, cmcnally-r7 approved these changes
lgtm

2024-07-26 08:32 UTC, ekelly-r7 approved these changes

2024-07-26 08:38 UTC, merged