[SI-25434] Abnormal Security - Case ID
rapid7/insightconnect-plugins pull request #2751
Opened 2024-08-29 17:26 UTC by rmurray-r7

## Proposed Changes

### Description

A customer is currently experiencing an issue with the `caseId` being returned as an int and not a string (which is what it is meant to be : https://app.swaggerhub.com/apis/abnormal-security/abx/1.4.3#/Cases/get_cases). 

As the `caseId` is not an input from the user (otherwise we could change the datatype) but an output value generated within the action, this is a possible solution to format it to a string when outputted. 

SI Ticket: https://rapid7.atlassian.net/browse/SI-25434

Describe the proposed changes:

  - Format the `caseId` to a string when outputted from the action

2024-08-30 12:50 UTC, igorski-r7 approved these changes

2024-10-04 09:22 UTC, ablakley-r7 approved these changes

2024-10-04 10:26 UTC, cmcnally-r7 requested changes

2024-10-04 10:26 UTC, cmcnally-r7 commented on plugins/abnormal_security/plugin.spec.yaml
> +troubleshooting: "There is no troubleshooting for this plugin."
There should be some key features
Remove requirements and troubleshooting from spec if there is none

2024-10-04 10:26 UTC, cmcnally-r7 commented on plugins/abnormal_security/plugin.spec.yaml
> +links:
Links should be this, references should point to API docs that are relevant to the plugin actions

2024-10-04 10:48 UTC, cmcnally-r7 commented on plugins/abnormal_security/icon_abnormal_security/actions/get_case_details/action.py
> +        response = self.connection.api.get_case_details(case_id)
```suggestion
        response = self.connection.api.get_case_details(params.get(Input.CASE_ID, ""))
```

2024-10-04 10:52 UTC, merged