Sentinelone threat file
rapid7/insightconnect-plugins pull request #678
Opened 2020-09-17 20:17 UTC by r7-mgorny

## Proposed Changes
Sentinelone threat file

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://komand.github.io/python/style.html)

- [ ] For dependencies, pin [OS package](https://komand.github.io/python/style.html#dockerfile) and [Python package](https://komand.github.io/python/style.html#requirements-txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://komand.github.io/python/sdk.html#sdk-versions) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://komand.github.io/python/error_handling.html#plugin-exceptions) and [ConnectionTestException](https://komand.github.io/python/error_handling.html#connection-exceptions)
- [ ] For logging, use [self.logger](https://komand.github.io/python/sdk.html#logging)
- [ ] For docs, use [changelog style](https://komand.github.io/python/style.html#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://komand.github.io/python/style.html#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nToken: *************16c03\nrapid7/SentinelOne:3.1.0. Step name: threats_fetch_file\n",
    "meta": {},
    "output": {
      "file": {
        "content": "W3siaW5jbHVkZWQiOnRydWUsInBhdGgiOiJcXERldmljZVxcSGFyZGRpc2tWb2x1bWUyXFxVc2Vyc1xcQWRtaW5pc3RyYXRvclxcRGVza3RvcFxcdGVzdC50eHQiLCJyZWFzb24iOiIiLCJzaGExIjoiYTIxMzhmMjFlYTk2ZDk3Y2UwMGNkNTE5NzE2OTZmNzQ2NGU1ZGI4OSIsInNoYTI1NiI6IjY4Mjk2YTM3MTg4ZWUwMzA1NjY5YTIzYWNhZGUxNDg2MDVkZjMwYjgyM2Y5NTJmZDRmMzFjMGE4NTQ1NThmOTAiLCJzaXplIjo2OX1d",
        "filename": "test.txt"
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/sentinelone:3.1.0 --debug run < tests/threats_fetch_file.json
</summary>
</details>

<details>

```
{
  "body": {
    "error": "An error occurred during plugin execution!\n\nWrong password. Password must have more than 10 characters and cannot contain whitespace.",
    "log": "Connect: Connecting...\nToken: *************16c03\nrapid7/SentinelOne:3.1.0. Step name: threats_fetch_file\nAn error occurred during plugin execution!\n\nWrong password. Password must have more than 10 characters and cannot contain whitespace.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/komand-1.0.1-py3.7.egg/komand/plugin.py\", line 311, in handle_step\n    output = self.start_step(input_message['body'], 'action', logger, log_stream, is_test, is_debug)\n  File \"/usr/local/lib/python3.7/site-packages/komand-1.0.1-py3.7.egg/komand/plugin.py\", line 419, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.7/site-packages/sentinelone_rapid7_plugin-3.1.0-py3.7.egg/komand_sentinelone/actions/threats_fetch_file/action.py\", line 23, in run\n    assistance=\"Password must have more than 10 characters and cannot contain whitespace.\"\nkomand.exceptions.PluginException: An error occurred during plugin execution!\n\nWrong password. Password must have more than 10 characters and cannot contain whitespace.\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/sentinelone:3.1.0 --debug run < tests/threats_fetch_file_bad.json
</summary>
</details>

<details>

```
{
  "body": {
    "error": "An error occurred during plugin execution!\n\nWrong password. Password must have more than 10 characters and cannot contain whitespace.",
    "log": "Connect: Connecting...\nToken: *************16c03\nrapid7/SentinelOne:3.1.0. Step name: threats_fetch_file\nAn error occurred during plugin execution!\n\nWrong password. Password must have more than 10 characters and cannot contain whitespace.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/komand-1.0.1-py3.7.egg/komand/plugin.py\", line 311, in handle_step\n    output = self.start_step(input_message['body'], 'action', logger, log_stream, is_test, is_debug)\n  File \"/usr/local/lib/python3.7/site-packages/komand-1.0.1-py3.7.egg/komand/plugin.py\", line 419, in start_step\n    output = func(params)\n  File \"/usr/local/lib/python3.7/site-packages/sentinelone_rapid7_plugin-3.1.0-py3.7.egg/komand_sentinelone/actions/threats_fetch_file/action.py\", line 23, in run\n    assistance=\"Password must have more than 10 characters and cannot contain whitespace.\"\nkomand.exceptions.PluginException: An error occurred during plugin execution!\n\nWrong password. Password must have more than 10 characters and cannot contain whitespace.\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/sentinelone:3.1.0 --debug run < tests/threats_fetch_file2_bad.json
</summary>
</details>

### Validate

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Plugin successfully validated!

----
[*] Total time elapsed: 2706.225ms

[*] Validating spec with js-yaml
[SUCCESS] Passes js-yaml spec check

[*] Validating markdown...
help.md:40: MD001 Header levels should only increment by one level at a time
help.md:569: MD012 Multiple consecutive blank lines
help.md:20: MD022 Headers should be surrounded by blank lines
help.md:37: MD031 Fenced code blocks should be surrounded by blank lines

A detailed description of the rules is available at https://github.com/markdownlint/mark [...]

2020-09-17 20:25 UTC, jschipp-r7 requested changes
Comments in review and need to pass `mdl` linting

```
[*] Validating markdown...
help.md:40: MD001 Header levels should only increment by one level at a time
help.md:569: MD012 Multiple consecutive blank lines
help.md:20: MD022 Headers should be surrounded by blank lines
help.md:37: MD031 Fenced code blocks should be surrounded by blank lines
```

2020-09-17 20:25 UTC, jschipp-r7 commented on sentinelone/plugin.spec.yaml
> +        type: string
This needs to be `password` type to mask it in the product

2020-09-17 20:25 UTC, jschipp-r7 commented on sentinelone/plugin.spec.yaml
> +        description: File of data to be imported into Anomali ThreatStream
```suggestion
        description: Base64 encoded threat file
```

2020-09-18 19:58 UTC, mrinehart-r7 requested changes

2020-09-18 19:58 UTC, mrinehart-r7 commented on sentinelone/help.md
> +* 3.1.0 - Add new action Threats Fetch File
```suggestion
* 3.1.0 - Add new action Fetch Threats File
```

2020-09-18 19:58 UTC, mrinehart-r7 commented on sentinelone/plugin.spec.yaml
> +    title: Threats Fetch File
```suggestion
    title: Fetch Threats File
```

2020-09-18 22:08 UTC, jschipp-r7 approved these changes

2020-09-18 22:10 UTC, merged