[] - Add CPE, Analyst Notes, and Related Entities to Recorded Future Lookup Vuln
rapid7/insightconnect-plugins pull request #683
Opened 2020-09-24 19:40 UTC by jmcadams-r7

## Proposed Changes

Add CVE, Analyst Notes, and Related Entities to Recorded Future Lookup Vuln

## Validation: 
```
BOS-X280-6057:recorded_future jmcadams$ icon-validate .
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Plugin successfully validated!

----
[*] Total time elapsed: 1355.097ms
```

## Testing: 
```
BOS-X280-6057:recorded_future jmcadams$ ./run.sh -R tests/lookup_vulnerability.json -j
Running: cat tests/lookup_vulnerability.json | docker run --rm   -i rapid7/recorded_future:2.0.1  run | grep -- ^\{ | jq -r '.body | try(.log | split("\n") | .[]),.output'
rapid7/Recorded Future:2.0.1. Step name: lookup_vulnerability
Requesting query path_info=vulnerability/OjOAdZ
Starting new HTTPS connection (1): api.recordedfuture.com:443
https://api.recordedfuture.com:443 "GET /v2/vulnerability/OjOAdZ?fields=analystNotes%2CcommonNames%2Ccpe%2Ccvss%2Ccvssv3%2Centity%2CintelCard%2Cmetrics%2CnvdDescription%2CnvdDescription%2Crawrisk%2CrelatedEntities%2CrelatedLinks%2Crisk%2Ctimestamps&app_id=rfapi-python%2F2.6.0 HTTP/1.1" 200 None
rapid7/Recorded Future:2.0.1. Step name: lookup_vulnerability

{
  "data": {
    "relatedLinks": [
      "http://www.securitytracker.com/id/1032899",
      "https://docs.microsoft.com/en-us/security-updates/securitybulletins/2015/ms15-070"
    ],
    "analystNotes": [
      {
        "source": {
          "id": "VKz42X",
          "name": "Insikt Group",
          "type": "Source"
        },
        "attributes": {
          "validated_on": "2018-07-16T04:00:00.000Z",
          "published": "2018-07-16T04:00:00.000Z",
          "text": "Russia’s vulnerability database is highly focused. However, it is incomplete, slow, and likely intended to support the control of the Russian state over technology companies and users. Generally, Russia publishes only 10 percent of known vulnerabilities, is on average 83 days slower than China’s National Vulnerability Database (CNNVD), 50 days slower than the U.S. NVD, and incomplete in the few technologies it does cover.\n\nRussia’s vulnerability database is run by the Federal Service for Technical and Export Control of Russia (FSTEC). FSTEC is the military organization responsible for protecting state secrets and supporting counterintelligence and counterespionage operations.\nFSTEC’s vulnerability database is also known as the BDU (Банк данных угроз безопасности информации). The BDU has published only 11,036 vulnerabilities of the 107,901 CVEs reported by NVD (approximately 10 percent).\nFSTEC has published 61 percent of vulnerabilities exploited by Russian state-sponsored threat groups. This is substantially above the norm of 10 percent; however, the data is insufficient to determine the influence of Russian intelligence services on FSTEC publication.\nFSTEC populates the BDU database with vulnerabilities that primarily present a threat to Russian state information systems. This gives researchers information on which technologies, hardware, and software are used on Russian government networks.",
          "labels": [
            {
              "id": "WlBq1z",
              "name": "CTA-2018-0713",
              "type": "UserLabel"
            }
          ],
          "topic": {
            "id": "TXSFt1",
            "name": "Cyber Threat Analysis",
            "type": "Topic",
            "description": "Long form analysis with original Recorded Future research/analyst comment."
          },
          "title": "Pavlov’s Digital House: Russia Focuses Inward for Vulnerability Analysis",
          "note_entities": [
            {
              "id": "IO4cCT",
              "name": "Pavlov",
              "type": "Organization"
            },
            {
              "id": "JV_A38",
              "name": "FSTEC Russia",
              "type": "Organization"
            },
            {
              "id": "B_lfs",
              "name": "The Government of the Russian Federation",
              "type": "Organization"
            },
            {
              "id": "B_Fb9",
              "name": "Russia",
              "type": "Country"
            },
            {
              "id": "BFStwf",
              "name": "Vulnerability Analysis",
              "type": "Technology"
            }
          ],
          "context_entities": [
            {
              "id": "S0gC8p",
              "name": "CVE-2017-0143",
              "type": "CyberVulnerability",
              "description": "The SMBv1 server in Microsoft Windows Vista SP2; Windows Server 2008 SP2 and R2 SP1; Windows 7 SP1; Windows 8.1; Windows Server 2012 Gold and R2; Windows RT 8.1; and Windows 10 Gold, 1511, and 1607; and Windows Server 2016 allows remote attackers to execute arbitrary code via crafted packets, aka \"Windows SMB Remote Code Execution Vulnerability.\" This vulnerability is different from those described in CVE-2017-0144, CVE-2017-0145, CVE-2017-0146, and CVE-2017-0148."
            },
            {
              "id": "KU4MsD",
              "name": "CVE-2013-3906",
              "type": "CyberVulnerability",
              "description": "GDI+ in Microsoft Windows Vista SP2 and Server 2008 SP2; Office 2003 SP3, 2007 SP3, and 2010 SP1 and SP2; Office Compatibility Pack SP3; and Lync 2010, 2010 Attendee, 2013, and Basic 2013 allows remote attackers to execute arbitrary code via a crafted TIFF image, as demonstrated by an image in a Word document, and exploited in the wild in October and November 2013."
            },
            {
              "id": "SDM9sy",
              "name": "CVE-2016-7228",
              "type": "CyberVulnerability",
              "description": "Microsoft Excel 2007 SP3, Excel 2010 SP2, Excel 2013 SP1, Excel 2013 RT SP1, Excel 2016, Excel for Mac 2011, Excel 2016 for Mac, and Office Compatibility Pack SP3 allow remote attackers to execute arbitrary code via a crafted Office document, aka \"Microsoft Office Memory Corruption Vulnerability.\""
            },
            {
              "id": "TMSSAw",
              "name": "CVE-2017-0263",
              "type": "CyberVulnerability",
              "description": "The kernel-mode drivers in Microsoft Windows Server 2008 SP2 and R2 SP1, Windows 7 SP1, Windows 8.1, Windows Server 2012 Gold and R2, Windows RT 8.1, Windows 10 Gold, 1511, 1607, 1703, and Windows Server 2016 allow local users to gain privileges via a crafted application, aka \"Win32k Elevation of Privilege Vulnerability.\""
            },
            {
              "id": "B_lfs",
              "name": "The Government of the Russian Federation",
              "type": "Organization"
            },
            {
              "id": "SDNWTA",
              "name": "CVE-2016-7255",
              "type": "CyberVulnerability",
              "description": "The kernel-mode drivers in Microsoft Windows Vista SP2, Windows Server 2008 SP2 and R2 SP1, Windows 7 SP1, Windows 8.1, Windows Server 2012 Gold and R2, Windows RT 8.1, Windo [...]

2020-09-24 21:14 UTC, mrinehart-r7 requested changes
Needs analystNotes typed

2020-09-24 21:14 UTC, mrinehart-r7 commented on recorded_future/help.md
> +  "api_key": "9de5069c5afe602b2ea0a04b66beb2c0"
```suggestion
  "api_key": {"secretKey": "9de5069c5afe602b2ea0a04b66beb2c0"}
```

2020-09-28 14:27 UTC, jschipp-r7 approved these changes

2020-09-28 14:37 UTC, jschipp-r7 approved these changes

2020-09-28 14:37 UTC, jschipp-r7 commented on recorded_future/help.md
> +* 2.0.1 - Add CPE, Analyst Notes, and Related Entities to Lookup Vulnerability output
```suggestion
* 2.0.1 - Add CPE, Analyst Notes, and Related Entities to Lookup Vulnerability action output
```

2020-09-28 14:37 UTC, jschipp-r7 approved these changes

2020-09-28 14:49 UTC, merged