[SOAR-2925] - Recorded future Lookup Alert
rapid7/insightconnect-plugins pull request #698
Opened 2020-10-02 18:46 UTC by jmcadams-r7

## Proposed Changes

This PR adds Lookup Alert to the Recorded Future plugin

## Validation: 
```
APAC-P50-4714:recorded_future jmcadams$ icon-validate .
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Plugin successfully validated!

----
[*] Total time elapsed: 989.042ms
```

## Testing: 
```
APAC-P50-4714:recorded_future jmcadams$ ./run.sh -R tests/lookup_alert.json -j
Running: cat tests/lookup_alert.json | docker run --rm   -i rapid7/recorded_future:2.1.0  run | grep -- ^\{ | jq -r '.body | try(.log | split("\n") | .[]),.output'
rapid7/Recorded Future:2.1.0. Step name: lookup_alert
Requesting query path_info=alert/fhS1El
Starting new HTTPS connection (1): api.recordedfuture.com:443
https://api.recordedfuture.com:443 "GET /v2/alert/fhS1El?app_id=rfapi-python%2F2.6.0 HTTP/1.1" 200 None
rapid7/Recorded Future:2.1.0. Step name: lookup_alert

{
  "alert": {
    "review": {
      "status": "no-action"
    },
    "entities": [
      {
        "entity": {
          "id": "faymwJ",
          "name": "CVE-2015-4719",
          "type": "CyberVulnerability",
          "description": "The client API authentication mechanism in Pexip Infinity before 10 allows remote attackers to gain privileges via a crafted request."
        },
        "risk": {
          "criticalityLabel": "High",
          "documents": [
            {
              "references": [
                {
                  "fragment": "CVE-2015-4719 (infinity).",
                  "entities": [
                    {
                      "id": "faymwJ",
                      "name": "CVE-2015-4719",
                      "type": "CyberVulnerability",
                      "description": "The client API authentication mechanism in Pexip Infinity before 10 allows remote attackers to gain privileges via a crafted request."
                    }
                  ],
                  "language": "eng"
                }
              ],
              "source": {
                "id": "Z3TZAQ",
                "name": "Sesin at",
                "type": "Source"
              },
              "url": "https://www.sesin.at/2020/10/02/cve-2015-4719-infinity/",
              "title": "CVE-2015-4719 (infinity)"
            },
            {
              "references": [
                {
                  "fragment": "New post from https://t.co/uXvPWJy6tj (CVE-2015-4719 (infinity)) has been published on https://t.co/Aw7GbAXNJr.",
                  "entities": [
                    {
                      "id": "faymwJ",
                      "name": "CVE-2015-4719",
                      "type": "CyberVulnerability",
                      "description": "The client API authentication mechanism in Pexip Infinity before 10 allows remote attackers to gain privileges via a crafted request."
                    },
                    {
                      "id": "url:https://www.sesin.at/2020/10/02/cve-2015-4719-infinity/",
                      "name": "https://www.sesin.at/2020/10/02/cve-2015-4719-infinity/",
                      "type": "URL"
                    },
                    {
                      "id": "url:https://www.sesin.at/",
                      "name": "https://www.sesin.at/",
                      "type": "URL"
                    }
                  ],
                  "language": "eng"
                }
              ],
              "source": {
                "id": "BV5",
                "name": "Twitter",
                "type": "Source"
              },
              "url": "https://twitter.com/WolfgangSesin/statuses/1311902525512126464",
              "title": "New post from https://t.co/uXvPWJy6tj (CVE-2015-4719 (infinity)) has been published on https://t.co/Aw7GbAXNJr"
            }
          ],
          "evidence": [
            {
              "timestamp": "2020-09-25T07:17:09.000Z",
              "criticalityLabel": "Low",
              "evidenceString": "8 sightings on 8 sources including: SecurityDatabase Alerts Monitor Last 100 Alerts, vulmon.com, @NetHaxBot, @VulmonFeeds, @VulnSME. Most recent tweet: New/Modified vulnerability published September 23, 2020 at 07:15PM on the NVD: CVE-2015-4719 https://t.co/oso1bdme0I The client API authentication mechanism in Pexip Infinity before 10 allows remote attackers to gain privileges via a crafted request. Most recent link (Sep 25, 2020): https://twitter.com/SecRiskRptSME/statuses/1309391474354802688",
              "rule": "Linked to Recent Cyber Exploit",
              "criticality": 1
            },
            {
              "timestamp": "2020-10-02T00:25:00.000Z",
              "criticalityLabel": "High",
              "evidenceString": "1 sighting on 1 source: Recorded Future Vulnerability Analysis. CVSS v3.1 Score (8.3) calculated using NIST reported CVSS Base Score (9.8) and Recorded Future Temporal Metrics. Base vector string: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H. Temporal vector string: E:U/RL:X/RC:U. Most recent link (Oct 2, 2020): https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-4719",
              "rule": "NIST Severity: High",
              "criticality": 3
            }
          ],
          "criticality": 3
        },
        "trend": {},
        "documents": []
      }
    ],
    "url": "https://app.recordedfuture.com/live/sc/notification/?id=fhS1El",
    "rule": {
      "url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScJA%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+Vulnerabilities%2C+New+Exploit+Chatter%22%7D&state.bNavbar=false",
      "name": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter",
      "id": "feScJA"
    },
    "triggered": "2020-10-02T06:55:23.996Z",
    "id": "fhS1El",
    "counts": {
      "references": 2,
      "entities": 1,
      "documents": 2
    },
    "title": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter - ... is n...",
    "type": "ENTITY"
  }
}
```

2020-10-02 18:48 UTC, jmcadams-r7 commented on recorded_future/help.md
> +```
I'm adding the example.

2020-10-02 18:48 UTC, mhofert-r7 requested changes

2020-10-02 18:48 UTC, mhofert-r7 commented on recorded_future/help.md
> +```
Missing example output

2020-10-02 19:44 UTC, mrinehart-r7 requested changes

2020-10-02 19:44 UTC, mrinehart-r7 commented on recorded_future/help.md
> +  "api_key": "9de5069c5afe602b2ea0a04b66beb2c0"
The old version was correct

2020-10-05 17:10 UTC, mrinehart-r7 approved these changes

2020-10-05 17:10 UTC, merged