[SOAR-3090] - RecordedFuture get new alerts
rapid7/insightconnect-plugins pull request #708
Opened 2020-10-09 17:46 UTC by jmcadams-r7

## Proposed Changes

This PR adds the Get New Alerts trigger to Recorded Future

## Validation: 
```
rmt-mbp-5357:recorded_future jmcadams$ icon-validate .
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Plugin successfully validated!

----
[*] Total time elapsed: 1244.374ms
```

## Testing
```
rmt-mbp-5357:recorded_future jmcadams$ ./run.sh -R tests/get_new_alerts.json
Running: cat tests/get_new_alerts.json | docker run --rm   -i rapid7/recorded_future:2.2.0 --debug run
This is a trigger ^C to continue
rapid7/Recorded Future:2.2.0. Step name: get_new_alerts
Requesting query path_info=alert/search
Starting new HTTPS connection (1): api.recordedfuture.com:443
https://api.recordedfuture.com:443 "GET /v2/alert/search?triggered=%5B2020-10-08T17%3A40%3A06.295570%2C%29&app_id=rfapi-python%2F2.6.0 HTTP/1.1" 200 None
{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fna0en", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScI-%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+New+Critical+or+Pre+NVD+Vulnerabilities%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities", "id": "feScI-"}, "triggered": "2020-10-09T16:08:33.041Z", "id": "fna0en", "title": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities - ... i...", "type": "ENTITY"}}, "log": "rapid7/Recorded Future:2.2.0. Step name: get_new_alerts\n"}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fnbTO7", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScJA%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+Vulnerabilities%2C+New+Exploit+Chatter%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter", "id": "feScJA"}, "triggered": "2020-10-09T16:08:21.948Z", "id": "fnbTO7", "title": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter - ... is n...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fnB1Lq", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScI-%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+New+Critical+or+Pre+NVD+Vulnerabilities%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities", "id": "feScI-"}, "triggered": "2020-10-09T07:23:30.713Z", "id": "fnB1Lq", "title": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities - ... i...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fmwpYj", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScJA%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+Vulnerabilities%2C+New+Exploit+Chatter%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter", "id": "feScJA"}, "triggered": "2020-10-09T02:35:39.841Z", "id": "fmwpYj", "title": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter - ... is n...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fmv7NE", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScJA%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+Vulnerabilities%2C+New+Exploit+Chatter%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter", "id": "feScJA"}, "triggered": "2020-10-09T00:53:31.680Z", "id": "fmv7NE", "title": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter - ... is n...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fmv7Jg", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScI-%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+New+Critical+or+Pre+NVD+Vulnerabilities%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities", "id": "feScI-"}, "triggered": "2020-10-08T22:42:10.588Z", "id": "fmv7Jg", "title": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities - ... i...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fmyroN", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScI-%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+New+Critical+or+Pre+NVD+Vulnerabilities%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities", "id": "feScI-"}, "triggered": "2020-10-08T22:36:15.079Z", "id": "fmyroN", "title": "Global Vulnerability Risk, New Critical or Pre NVD Vulnerabilities - ... i...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app.recordedfuture.com/live/sc/notification/?id=fmyroL", "rule": {"url": "https://app.recordedfuture.com/live/sc/ViewIdkobra_view_report_item_alert_editor?view_opts=%7B%22reportId%22%3A%22feScJA%22%2C%22bTitle%22%3Atrue%2C%22title%22%3A%22Global+Vulnerability+Risk%2C+Vulnerabilities%2C+New+Exploit+Chatter%22%7D&state.bNavbar=false", "name": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter", "id": "feScJA"}, "triggered": "2020-10-08T22:35:13.641Z", "id": "fmyroL", "title": "Global Vulnerability Risk, Vulnerabilities, New Exploit Chatter - ... is n...", "type": "ENTITY"}}, "log": ""}, "type": "trigger_event", "version": "v1"}{"body": {"meta": {}, "output": {"alert": {"review": {"status": "no-action"}, "url": "https://app. [...]

2020-10-09 19:13 UTC, ncramer-r7 commented on recorded_future/plugin.spec.yaml
> +        description: Frequency
```suggestion
        description: Frequency (in seconds)
```

2020-10-09 19:14 UTC, ncramer-r7 requested changes
Looks like MoreSOAR just updated this plugin to 3.0.0, regen and bump the version -- all the code looks good to me

2020-10-12 13:55 UTC, ncramer-r7 submitted a review, later dismissed

2020-10-12 15:23 UTC, jschipp-r7 approved these changes

2020-10-12 15:43 UTC, jschipp-r7 approved these changes

2020-10-12 16:11 UTC, merged