[] - Obsolete the Storage Plugin
rapid7/insightconnect-plugins pull request #712
Opened 2020-10-14 19:32 UTC by jmcadams-r7

## Description: 

This PR marks the Storage plugin as obsolete.

2020-10-14 19:43 UTC, jschipp-r7 requested changes
Missing obsolescence messaging and documentation updates.

2020-10-14 19:46 UTC, mhofert-r7 approved these changes

2020-10-15 14:32 UTC, jschipp-r7 submitted a review, later dismissed

2020-10-15 14:33 UTC, jschipp-r7 commented on storage/help.md
> +[Custom Loop Variables](https://docs.rapid7.com/insightconnect/loop-step/)
```suggestion
* [Custom Loop Variables](https://docs.rapid7.com/insightconnect/loop-step/)  
```

2020-10-15 14:33 UTC, jschipp-r7 approved these changes

2020-10-15 14:33 UTC, merged