Fix host parsing issue in connection
rapid7/insightconnect-plugins pull request #715
Opened 2020-10-15 20:23 UTC by mhofert-r7

## Proposed Changes

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://komand.github.io/python/style.html)

- [ ] For dependencies, pin [OS package](https://komand.github.io/python/style.html#dockerfile) and [Python package](https://komand.github.io/python/style.html#requirements-txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://komand.github.io/python/sdk.html#sdk-versions) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://komand.github.io/python/error_handling.html#plugin-exceptions) and [ConnectionTestException](https://komand.github.io/python/error_handling.html#connection-exceptions)
- [ ] For logging, use [self.logger](https://komand.github.io/python/sdk.html#logging)
- [ ] For docs, use [changelog style](https://komand.github.io/python/style.html#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://komand.github.io/python/style.html#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR.
4. Add UI screenshot of the workflow used for testing
5. Add UI screenshot of the job output used for testing
6. Add UI screenshot of the artifact (See rules in UI Checklist) used for testing

2020-10-15 20:43 UTC, jmcadams-r7 approved these changes

2020-10-15 21:02 UTC, ncramer-r7 approved these changes

2020-10-19 20:40 UTC, mrinehart-r7 requested changes

2020-10-19 20:40 UTC, mrinehart-r7 commented on active_directory_ldap/komand_active_directory_ldap/connection/connection.py
> +    def host_formater(self, host: str) -> str:
```suggestion
    def host_formatter(self, host: str) -> str:
```

2020-10-19 20:40 UTC, mrinehart-r7 commented on active_directory_ldap/komand_active_directory_ldap/connection/connection.py
> +                                              data=host)
```suggestion
        colons = host.count(':')
        if colons > 0:
            self.logger.info('Port was provided in hostname, using value from Port field instead')
            host = host.split(':')
            if colons == 1:
                host = host[0]
            elif colons == 2:
                host = f'{host[0]}:{host[1]}'
            else:
                raise ConnectionTestException(cause=f'There are too many colons ({colons}) in the host name ({host}).',
                                              assistance='Check that the host name is correct',
                                              data=host)
```

2020-10-19 21:06 UTC, mrinehart-r7 requested changes

2020-10-19 21:06 UTC, mrinehart-r7 commented on active_directory_ldap/komand_active_directory_ldap/connection/connection.py
> +        host = self.host_formater(host)
```suggestion
        host = self.host_formatter(host)
```

2020-10-19 21:14 UTC, mrinehart-r7 requested changes

2020-10-19 21:14 UTC, mrinehart-r7 commented on active_directory_ldap/help.md
> +* 4.0.2 - Fix issue were some host names were being incorrectly parsed
```suggestion
* 4.0.2 - Fix issue where some host names were being incorrectly parsed
```

2020-10-19 21:42 UTC, mrinehart-r7 approved these changes

2020-10-20 00:11 UTC, jmcadams-r7 approved these changes

2020-10-20 14:58 UTC, merged