Microsoft Teams new actions Add Group Owner and Add Member to Channel
rapid7/insightconnect-plugins pull request #730
Opened 2020-10-30 16:50 UTC by dsliwinski-r7

### Proposed Changes

Microsoft Teams new actions Add Group Owner and Add Member to Channel

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://komand.github.io/python/style.html)

- [ ] For dependencies, pin [OS package](https://komand.github.io/python/style.html#dockerfile) and [Python package](https://komand.github.io/python/style.html#requirements-txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://komand.github.io/python/sdk.html#sdk-versions) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://komand.github.io/python/error_handling.html#plugin-exceptions) and [ConnectionTestException](https://komand.github.io/python/error_handling.html#connection-exceptions)
- [ ] For logging, use [self.logger](https://komand.github.io/python/sdk.html#logging)
- [ ] For docs, use [changelog style](https://komand.github.io/python/style.html#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://komand.github.io/python/style.html#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Time Now: 1603996655.5130122\nTime Ago: 0\nRefreshing auth token\nUpdating Auth Token...\nGetting token from: https://login.microsoftonline.com/5c824599-dc8c-4d31-96fb-3b886d4f8f10/oauth2/token\nAuthentication was successful, token is: ******************gO14w\nDetected Permissions: Agreement.Read.All Agreement.ReadWrite.All AgreementAcceptance.Read AgreementAcceptance.Read.All AppCatalog.ReadWrite.All AuditLog.Read.All Bookings.Manage.All Bookings.Read.All Bookings.ReadWrite.All BookingsAppointment.ReadWrite.All Calendars.Read Calendars.Read.Shared Calendars.ReadWrite Calendars.ReadWrite.Shared Contacts.Read Contacts.Read.Shared Contacts.ReadWrite Contacts.ReadWrite.Shared Device.Command Device.Read DeviceManagementApps.Read.All DeviceManagementApps.ReadWrite.All DeviceManagementConfiguration.Read.All DeviceManagementConfiguration.ReadWrite.All DeviceManagementManagedDevices.PrivilegedOperations.All DeviceManagementManagedDevices.Read.All DeviceManagementManagedDevices.ReadWrite.All DeviceManagementRBAC.Read.All DeviceManagementRBAC.ReadWrite.All DeviceManagementServiceConfig.Read.All DeviceManagementServiceConfig.ReadWrite.All Directory.AccessAsUser.All Directory.ReadWrite.All EAS.AccessAsUser.All EduAdministration.Read EduAdministration.ReadWrite EduAssignments.Read EduAssignments.ReadBasic EduAssignments.ReadWrite EduAssignments.ReadWriteBasic EduRoster.Read EduRoster.ReadBasic EduRoster.ReadWrite email Files.Read Files.Read.All Files.Read.Selected Files.ReadWrite Files.ReadWrite.All Files.ReadWrite.AppFolder Files.ReadWrite.Selected Financials.ReadWrite.All Group.Read.All Group.ReadWrite.All IdentityProvider.Read.All IdentityProvider.ReadWrite.All IdentityRiskEvent.Read.All Mail.Read Mail.Read.Shared Mail.ReadWrite Mail.ReadWrite.Shared Mail.Send Mail.Send.Shared MailboxSettings.Read MailboxSettings.ReadWrite Member.Read.Hidden Notes.Create Notes.Read Notes.Read.All Notes.ReadWrite Notes.ReadWrite.All Notes.ReadWrite.CreatedByApp offline_access openid People.Read People.Read.All PrivilegedAccess.ReadWrite.AzureAD PrivilegedAccess.ReadWrite.AzureResources profile Reports.Read.All SecurityEvents.Read.All SecurityEvents.ReadWrite.All Sites.FullControl.All Sites.Manage.All Sites.Read.All Sites.ReadWrite.All Subscription.Read.All Tasks.Read Tasks.Read.Shared Tasks.ReadWrite Tasks.ReadWrite.Shared User.Export.All User.Invite.All User.Read.All User.ReadWrite.All UserActivity.ReadWrite.CreatedByApp UserTimelineActivity.Write.CreatedByApp\nrapid7/Microsoft Teams:3.1.0. Step name: add_group_owner\nTime Now: 1603996656.280106\nTime Ago: 1603996656.2779598\nToken is valid, not refreshing.\nGetting group ID with: https://graph.microsoft.com/v1.0/5c824599-dc8c-4d31-96fb-3b886d4f8f10/groups?$filter=displayName eq 'Komand-Test-Everyone'\nTime Now: 1603996656.847883\nTime Ago: 1603996656.2779598\nToken is valid, not refreshing.\nGetting user information from:\nhttps://graph.microsoft.com/v1.0/5c824599-dc8c-4d31-96fb-3b886d4f8f10/users?$filter=userPrincipalName eq 'jschipp@komanddev.onmicrosoft.com'\nGetting user information return code:200\nAdding user to group owners with: https://graph.microsoft.com/beta/groups/7af08a76-01fe-4a1d-bfa1-84d2b5509cdd/owners/$ref.\nTime Now: 1603996657.4816673\nTime Ago: 1603996656.2779598\nToken is valid, not refreshing.\nUser was added successfully.\n",
    "meta": {},
    "output": {
      "success": true
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/microsoft_teams:3.1.0 --debug run < tests/add_group_owner.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Time Now: 1603996661.2215118\nTime Ago: 0\nRefreshing auth token\nUpdating Auth Token...\nGetting token from: https://login.microsoftonline.com/5c824599-dc8c-4d31-96fb-3b886d4f8f10/oauth2/token\nAuthentication was successful, token is: ******************iQ0RQ\nDetected Permissions: Agreement.Read.All Agreement.ReadWrite.All AgreementAcceptance.Read AgreementAcceptance.Read.All AppCatalog.ReadWrite.All AuditLog.Read.All Bookings.Manage.All Bookings.Read.All Bookings.ReadWrite.All BookingsAppointment.ReadWrite.All Calendars.Read Calendars.Read.Shared Calendars.ReadWrite Calendars.ReadWrite.Shared Contacts.Read Contacts.Read.Shared Contacts.ReadWrite Contacts.ReadWrite.Shared Device.Command Device.Read DeviceManagementApps.Read.All DeviceManagementApps.ReadWrite.All DeviceManagementConfiguration.Read.All DeviceManagementConfiguration.ReadWrite.All DeviceManagementManagedDevices.PrivilegedOperations.All DeviceManagementManagedDevices.Read.All DeviceManagementManagedDevices.ReadWrite.All DeviceManagementRBAC.Read.All DeviceManagementRBAC.ReadWrite.All DeviceManagementServiceConfig.Read.All DeviceManagementServiceConfig.ReadWrite.All Directory.AccessAsUser.All Directory.ReadWrite.All EAS.AccessAsUser.All EduAdministration.Read EduAdministration.ReadWrite EduAssignments.Read EduAssignments.ReadBasic EduAssignments.ReadWrite EduAssignments.ReadWriteBasic EduRoster.Read EduRoster.ReadBasic EduRoster.ReadWrite email Files.Read Files.Read.All Files.Read.Selected Files.ReadWrite Files.ReadWrite.All Files.ReadWrite.AppFolder Files.ReadWrite.Selected Financials.ReadWrite.All Group.Read.All Group.ReadWrite.All IdentityProvider.Read.All IdentityProvider.ReadWrite.All IdentityRiskEvent.Read.All Mail.Read Mail.Read.Shared Mail.ReadWrite Mail.ReadWrite.Shared Mail.Send Mail.Send.Shared MailboxSettings.Read MailboxSettings.ReadWrite Member.Read.Hidden Notes.Create Notes.Read Notes [...]

2020-11-02 17:46 UTC, jschipp-r7 commented on microsoft_teams/help.md
> +This action is used to add a user to the group's owners, the owners are a set of non-admin users who are allowed to modify the group object.
```suggestion
This action is used to add a user to a group's list of owners, the owners are a set of non-admin users who are allowed to modify the group object.
```

2020-11-02 17:47 UTC, jschipp-r7 commented on microsoft_teams/plugin.spec.yaml
> +    description: Add a user to the group's owners, the owners are a set of non-admin users who are allowed to modify the group object
```suggestion
    description: Add a user to the group's list of owners. The owners are a set of non-admin users who are allowed to modify the group object
```

2020-11-02 17:50 UTC, jschipp-r7 requested changes

2020-11-02 17:50 UTC, jschipp-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +            cause=f"Unable to add user to channel:\nUser:{user_id}\nChannel:{channel_id}.",
Is there an error response for a user that is already added? if so, we can check that and still succeed if the user is already in the channel. And fail for other unknowns

2020-11-02 17:50 UTC, jschipp-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +        cause=f"Unexpected response from server when adding user to group owners. Response code: {result.status_code}.",
Is there an error response for a user that is an owner of the group? if so, we can check that and still succeed if the user is already and owner. And fail for other unknowns

2020-11-02 18:01 UTC, mhofert-r7 reviewed
add Jon's changes and I will approve

2020-11-02 18:18 UTC, mrinehart-r7 requested changes

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/plugin.spec.yaml
> +    description: Add a user to the group's owners, the owners are a set of non-admin users who are allowed to modify the group object
```suggestion
    description: Add a user to the group's list of owners
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/action.py
> +                channels[0].get("id"),
```suggestion
                channels[0].get("id"),
```
try/except for IndexError and handle the instance where the `.get()` returns a None value (if the API response is malformed).

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/action.py
> +                get_user_info(self.logger, self.connection, params.get(Input.MEMBER_LOGIN)).get("id")
```suggestion
                get_user_info(self.logger, self.connection, params.get(Input.MEMBER_LOGIN)).get("id")
```
Handle the instance where the `.get()` returns a None value

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +        cause=f"The server returned an unexpected result while deleting group.\nGroup name: {group_name}",
```suggestion
        cause=f"The server returned an unexpected result while deleting the '{group_name}' group.",
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +        assistance="Please contact Rapid7 support with the following information",
```suggestion
        assistance="Please contact Rapid7 support with the following information:",
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +                          assistance="Please contact Rapid7 support with the following error information.",
```suggestion
                          assistance="Please contact Rapid7 support with the following error information:",
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +                          assistance="Please contact Rapid7 support with the following error information.",
```suggestion
                          assistance="Please contact Rapid7 support with the following error information:",
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +                          assistance="Please contact Rapid7 support with the following error information.",
```suggestion
                          assistance="Please contact Rapid7 support with the following error information:",
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +                              assistance="Please contact Rapid7 support with the following information.",
```suggestion
                              assistance="Please contact Rapid7 support with the following information:",
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +def add_user_to_channel(logger: Logger, connection: komand.connection, group_id: str, channel_id: str,
```suggestion
def add_user_to_channel(logger: Logger, connection: komand.connection.Connection, group_id: str, channel_id: str,
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +def add_user_to_owners(logger: Logger, connection: komand.connection, group_id: str, user_id: str) -> bool:
```suggestion
def add_user_to_owners(logger: Logger, connection: komand.connection.Connection, group_id: str, user_id: str) -> bool:
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +    logger.info(f"Adding user to group owners with: {endpoint}.")
```suggestion
    logger.info(f"Adding user to group owners with: {endpoint}")
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +    logger.info(f"Adding user to channel with: {endpoint}.")
```suggestion
    logger.info(f"Adding user to channel with: {endpoint}")
```

2020-11-02 18:18 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
> +        assistance="Please contact Rapid7 support with the following error information.",
```suggestion
        assistance="Please contact Rapid7 support with the following error information:",
```

2020-11-04 19:57 UTC, mrinehart-r7 requested changes

2020-11-04 19:57 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/actions/add_group_owner/action.py
> +                cause="User not exist.",
```suggestion
                cause="The specified user does not exist.",
```

2020-11-04 19:57 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/action.py
> +                    cause="Channel not exist.",
```suggestion
                    cause="The specified channel does not exist.",
```

2020-11-04 19:57 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/action.py
> +                    cause="User not exist.",
```suggestion
                    cause="The specified user does not exist.",
```

2020-11-04 19:57 UTC, mrinehart-r7 commented on microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/action.py
> +                cause="Channel not exist.",
```suggestion
                cause="The specified channel does not exist.",
```

2020-11-06 20:02 UTC, mrinehart-r7 approved these changes

2020-11-06 20:02 UTC, merged