Datetime plugin new action Get Future Time
rapid7/insightconnect-plugins pull request #734
Opened 2020-11-04 12:35 UTC by dsliwinski-r7

## Proposed Changes

Datetime plugin new action Get Future Time

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://komand.github.io/python/style.html)

- [ ] For dependencies, pin [OS package](https://komand.github.io/python/style.html#dockerfile) and [Python package](https://komand.github.io/python/style.html#requirements-txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://komand.github.io/python/sdk.html#sdk-versions) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://komand.github.io/python/error_handling.html#plugin-exceptions) and [ConnectionTestException](https://komand.github.io/python/error_handling.html#connection-exceptions)
- [ ] For logging, use [self.logger](https://komand.github.io/python/sdk.html#logging)
- [ ] For docs, use [changelog style](https://komand.github.io/python/style.html#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://komand.github.io/python/style.html#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-10-20T12:14:36.0Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_days.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T12:09:26.9Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_default.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T12:09:29.1Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_empty.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T13:59:31.3Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_hours.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T21:59:33.5Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_hours_Asia_Hong_Kong.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T13:59:36.1Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_hours_Etc_GMT.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T13:59:38.4Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_hours_Europe_London.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-11-04T03:59:40.7Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_hours_US_Hawaii.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-07-22T22:19:33.0Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_minutes.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2021-01-04T12:14:36.0Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_months.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-10-06T12:01:00.0Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_seconds.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Datetime:2.2.0. Step name: get_future_time\n",
    "meta": {},
    "output": {
      "timestamp": "2020-03-12T12:14:36.0Z"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/datetime:2.2.0 --debug run < tests/get_future_time_weeks.json
</summary>
</details>

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing va [...]

2020-11-04 16:29 UTC, jschipp-r7 requested changes

2020-11-04 16:29 UTC, jschipp-r7 commented on datetime/plugin.spec.yaml
> +        description: Timestamp used for calculating a new delta timestamp
We should  allow both `now` and empty to use the current time and document that here and in the help.md

2020-11-04 16:29 UTC, jschipp-r7 commented on datetime/plugin.spec.yaml
> +        type: date
Date will need to be a RFC3339 compliant timestamp - I didn't verify but want to call it out in case you didn't know

2020-11-04 16:29 UTC, jschipp-r7 commented on datetime/plugin.spec.yaml
> +        description: The amount of time units used for the calculation
```suggestion
        description: The amount of time units to add to the base timestamp to get the future time
```

2020-11-04 16:29 UTC, jschipp-r7 commented on datetime/plugin.spec.yaml
> +        description: Units of time used for the calculation
```suggestion
        description: Units of time used for the future timestamp calculation
```

2020-11-04 16:30 UTC, jschipp-r7 commented on datetime/help.md
> +This action is used to calculate a new delta timestamp from parameters and a timestamp.
Document the default base timestamp behavior here. And also describe an example

2020-11-04 19:49 UTC, mrinehart-r7 approved these changes

2020-11-06 20:11 UTC, mrinehart-r7 approved these changes

2020-11-06 22:04 UTC, jschipp-r7 approved these changes

2020-11-06 22:06 UTC, jschipp-r7 requested changes

2020-11-06 22:06 UTC, jschipp-r7 commented on datetime/plugin.spec.yaml
> +        type: string
Use the `date` type which is a RFC3339 string

2020-11-06 22:06 UTC, jschipp-r7 commented on datetime/plugin.spec.yaml
> +        example: 22 Jul 2020 21:20:33
Should use a RFC3339 timestamp

2020-11-09 17:38 UTC, mhofert-r7 submitted a review, later dismissed

2020-11-11 19:48 UTC, mrinehart-r7 approved these changes

2020-11-11 19:50 UTC, mrinehart-r7 approved these changes

2020-11-11 19:51 UTC, merged