Fix decoding URL in action URL Decode in Proofpoint URL Defense plugin
rapid7/insightconnect-plugins pull request #764
Opened 2020-12-15 21:54 UTC by r7-kszczepanskagorna

## Proposed Changes

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://komand.github.io/python/style.html)

- [ ] For dependencies, pin [OS package](https://komand.github.io/python/style.html#dockerfile) and [Python package](https://komand.github.io/python/style.html#requirements-txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://komand.github.io/python/sdk.html#sdk-versions) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://komand.github.io/python/error_handling.html#plugin-exceptions) and [ConnectionTestException](https://komand.github.io/python/error_handling.html#connection-exceptions)
- [ ] For logging, use [self.logger](https://komand.github.io/python/sdk.html#logging)
- [ ] For docs, use [changelog style](https://komand.github.io/python/style.html#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://komand.github.io/python/style.html#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "rapid7/Proofpoint URL Defense:1.2.2. Step name: url_decode\nURL has been decoded\n",
    "meta": {},
    "output": {
      "decoded": true,
      "decoded_url": "http://www.example.org/url"
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_url_defense:1.2.2 --debug run < tests/url_decode2.json
</summary>
</details>

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator ExampleInputValidator
[*] Plugin failed validation! The following validation errors occurred:

Validator "VersionPinValidator" failed!
        Cause: All Python dependencies must be version pinned. Please update all modules in requirements.txt with a specific version pin e.g. lxml==3.7.1

----
[*] Total time elapsed: 991.958ms

[*] Validating spec with js-yaml
[SUCCESS] Passes js-yaml spec check

[*] Validating markdown...
[SUCCESS] Passes markdown linting

[*] Validating python files for style...
./unit_test/test_url_decode.py:5:1: E402 module level import not at top of file
./unit_test/test_url_decode.py:6:1: E402 module level import not at top of file
./unit_test/test_url_decode.py:7:1: E402 module level import not at top of file
./unit_test/test_url_decode.py:8:1: E402 module level import not at top of file
./unit_test/test_url_decode.py:9:1: E402 module level import not at top of file
./unit_test/test_url_decode.py:26:9: F841 local variable 'e' is assigned to but never used
./unit_test/test_url_decode.py:29:1: W293 blank line contains whitespace
./unit_test/test_url_decode.py:30:110: W291 trailing whitespace
./unit_test/test_url_decode.py:36:9: E303 too many blank lines (2)
./unit_test/test_url_decode.py:66:9: F841 local variable 'e' is assigned to but never used
./unit_test/test_url_decode.py:70:110: W291 trailing whitespace
./unit_test/test_url_decode.py:84:1: W391 blank line at end of file
[FAIL] Fails flake8 linting

[*] Validating python files for security vulnerabilities...
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.7.3
Run started:2020-12-15 21:47:13.637404

Test results:
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: '*'
   Severity: Low   Confidence: Medium
   Location: ./komand_proofpoint_url_defense/util/proofpoint_decoder.py:80
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b105_hardcoded_password_string.html
79              def replace_token(token):
80                  if token == '*':
81                      character = self.dec_bytes[self.current_marker]

--------------------------------------------------

Code scanned:
        Total lines of code: 270
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 1.0
                Medium: 0.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 1.0
                High: 0.0
Files skipped (0):
[FAIL] Fails bandit security checks

[*] Checking for typos with Misspell...
[SUCCESS] Passes Misspell check

```

<summary>
make validate
</summary>
</details>

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Execut [...]

2020-12-15 22:18 UTC, jschipp-r7 commented on proofpoint_url_defense/help.md
> +* 1.2.2 - Fix decoding URL in action URL Decode
```suggestion
* 1.2.2 - Decode URLs which contain hxxp as the protocol in action URL Decode
```

2020-12-15 22:32 UTC, jschipp-r7 requested changes
Getting a unicode character in the output when testing with a URL. URL sanitized:

<img width="410" alt="Screen Shot 2020-12-15 at 4 31 57 PM" src="https://user-images.githubusercontent.com/30870727/102280634-2560ad80-3ef3-11eb-92f6-33ab49468ee2.png">

2020-12-21 19:25 UTC, mrinehart-r7 approved these changes

2020-12-21 21:27 UTC, jschipp-r7 approved these changes

2020-12-21 21:29 UTC, merged