Okta - Fix issue where trigger get only 1000 users
rapid7/insightconnect-plugins pull request #772
Opened 2021-01-04 00:10 UTC by r7-mgorny

## Proposed Changes

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run with limit set to 2

<details>

```
INFO[0000] Running command:  docker run --rm -i rapid7/okta:3.5.1 --debug run < tests/users_added_removed_from_group.json
Connect: Connecting...
rapid7/Okta:3.5.1. Step name: users_added_removed_from_group
Starting new HTTPS connection (1): dev-114295-admin.oktapreview.com:443
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?limit=2 HTTP/1.1" 200 None
Starting new HTTPS connection (1): dev-114295.oktapreview.com:443
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a7&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a8&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a9&limit=2 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?after=11aaaaaaaaaaaaaaa1a4&limit=2 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a7&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a8&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a9&limit=2 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?after=11aaaaaaaaaaaaaaa1a4&limit=2 HTTP/1.1" 200 None
Loop complete, sleeping for 30...
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a7&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a8&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a9&limit=2 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?after=11aaaaaaaaaaaaaaa1a4&limit=2 HTTP/1.1" 200 None
Loop complete, sleeping for 30...

```

<summary>
Waiting for change data
</summary>
</details>

<details>

```
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a7&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a8&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a9&limit=2 HTTP/1.1" 200 None
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a2/users?after=11aaaaaaaaaaaaaaa1a4&limit=2 HTTP/1.1" 200 None
Users added, sending to orchestrator.
{"body": {"meta": {}, "output": {"users_added_from_groups": [{"group_name": "mc-cool", "group_id": "11aaaaaaaaaaaaaaa1a2", "users": [{"id": "11aaaaaaaaaaaaaaa1a5", "status": "ACTIVE", "created": "2021-01-03T23:14:42.000Z", "activated": "2021-01-03T23:14:42.000Z", "statusChanged": "2021-01-03T23:14:42.000Z", "lastUpdated": "2021-01-03T23:14:42.000Z", "passwordChanged": "2021-01-03T23:14:42.000Z", "type": {"id": "11aaaaaaaaaaaaaaa1a6"}, "profile": {"firstName": "Mateusz", "lastName": "Test4", "login": "user4@rapid7.com", "email": "user4@rapid7.com"}, "credentials": {"password": {}, "emails": [{"value": "user4@rapid7.com", "status": "VERIFIED", "type": "PRIMARY"}, {"status": "VERIFIED", "type": "SECONDARY"}], "provider": {"type": "OKTA", "name": "OKTA"}}, "_links": {"self": {"href": "https://dev-114295.oktapreview.com/api/v1/users/11aaaaaaaaaaaaaaa1a5"}}}]}], "users_removed_from_groups": []}, "log": "Connect: Connecting...\nrapid7/Okta:3.5.1. Step name: users_added_removed_from_group\nLoop complete, sleeping for 30...\nLoop complete, sleeping for 30...\nUsers added, sending to orchestrator.\n"}, "type": "trigger_event", "version": "v1"}
Loop complete, sleeping for 30...

```

<summary>
After add first user
</summary>
</details>

<details>

```
https://dev-114295-admin.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/11aaaaaaaaaaaaaaa1a1/users?after=11aaaaaaaaaaaaaaa1a7&limit=2 HTTP/1.1" 200 None
https://dev-114295.oktapreview.com:443 "GET /api/v1/groups/ [...]

2021-01-04 16:25 UTC, jschipp-r7 commented on okta/help.md
> +* 3.5.2 - Fix issue where trigger get only 1000 users
```suggestion
* 3.5.2 - Fix issue where Monitor User Groups trigger would be limited to 1000 users
```

2021-01-04 16:26 UTC, jschipp-r7 approved these changes

2021-01-04 16:29 UTC, mhofert-r7 requested changes

2021-01-04 16:29 UTC, mhofert-r7 commented on okta/help.md
> +```
Can We add examples here?

2021-01-05 23:45 UTC, jschipp-r7 approved these changes

2021-01-05 23:45 UTC, merged