SOAR_3246_Document_Maximum_Size
rapid7/insightconnect-plugins pull request #777
Opened 2021-01-08 20:33 UTC by emilykim-r7

# Description

Describe the proposed changes:

  - Add line into help.md documenting what the maximum size is for AttackerKB

2021-01-08 22:05 UTC, jmcadams-r7 requested changes

2021-01-08 22:05 UTC, jmcadams-r7 commented on rapid7_attackerkb/help.md
> +* 1.0.3 - Add maximum size into help.md
```suggestion
* 1.0.3 - Update to add the maximum size into help documentation
```

The style guide is very prescriptive about log lines.

2021-01-08 22:14 UTC, ncramer-r7 requested changes
Does this refer to the `size` attribute in the Search Assessment and Search Vulnerabilities? Either way, I don't think the update belongs in the Key Features section...maybe instead in the descriptions of the actions that use the size field?

2021-01-11 15:26 UTC, jmcadams-r7 approved these changes

2021-01-11 22:06 UTC, jschipp-r7 requested changes

2021-01-11 22:06 UTC, jschipp-r7 commented on rapid7_attackerkb/help.md
> +[Rapid7's AttackerKB](http://attackerkb.com/) is a knowledge base of vulnerabilities and informed opinions on what makes them valuable (or not) targets for exploitation. The maximum size value is 500
Should be documented in the size input's description

2021-01-11 22:06 UTC, jschipp-r7 commented on rapid7_attackerkb/plugin.spec.yaml
>        size:
Document in the description field below

2021-01-12 20:21 UTC, jmcadams-r7 approved these changes

2021-01-13 15:06 UTC, ncramer-r7 approved these changes

2021-01-13 18:42 UTC, jschipp-r7 approved these changes

2021-01-13 18:43 UTC, merged