[SOAR-4206, SOAR-4207]Update Jira and abuseipdb to v4 Python plugin runtime
rapid7/insightconnect-plugins pull request #787
Opened 2021-01-22 19:52 UTC by gusingh-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Update Jira and Abuseipdb to v4 Python plugin runtime
  - Set cloud_ready to true

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR.
4. Add UI screenshot of the workflow used for testing
5. Add UI screenshot of the job output used for testing
6. Add UI screenshot of the artifact (See rules in UI Checklist) used for testing

2021-01-22 20:14 UTC, tschmidtke-r7 approved these changes
lgtm. One request though. In the interest of slowly removely `komand` references, can the `komand_jira` and `komand_abuseipdb` directories be renamed to have `icon_` as the prefix and then regenerate the plugins?

2021-01-22 21:47 UTC, norenstrakh-r7 submitted a review, later dismissed
LGTM 👍

2021-01-25 17:48 UTC, jschipp-r7 submitted a review, later dismissed

2021-01-25 18:00 UTC, zyoutz-r7 submitted a review, later dismissed
Let's get flagging in place and then this looks good 👍🏻

2021-01-25 20:21 UTC, mrinehart-r7 requested changes

2021-01-25 20:21 UTC, mrinehart-r7 commented on abuseipdb/help.md
> +  "credentials": "e73h82c63847f3ff1h5216b556edh153h30430d73bchhe680f70h1d8885fb8bb130b46c7767d6886"
Revert

2021-01-25 20:21 UTC, mrinehart-r7 commented on jira/Dockerfile
> +FROM rapid7/insightconnect-python-3-38-plugin:4
Can you use the slim SDK? IIRC it is 3-38-slim-plugin

2021-01-25 21:53 UTC, zyoutz-r7 commented on abuseipdb/Dockerfile
> +FROM rapid7/insightconnect-python-3-38-plugin:4
I think Mike caught this on the other one.  Are we able to keep using slim here?

2021-01-25 21:53 UTC, mrinehart-r7 submitted a review, later dismissed

2021-01-25 21:59 UTC, zyoutz-r7 approved these changes

2021-01-25 22:01 UTC, tschmidtke-r7 approved these changes

2021-01-25 22:02 UTC, merged