New actions in Palo Alto PAN-OS plugin
rapid7/insightconnect-plugins pull request #799
Opened 2021-01-31 19:54 UTC by dsliwinski-r7

## Proposed Changes

* Add new action Get Addresses from Group 
* Rename Add Address Object to Group action to Add Address Objects to Group and support adding a list of address objects

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting..\nKey obtained\nrapid7/Palo Alto Firewall:7.0.0. Step name: add_address_objects_to_group\n",
    "meta": {},
    "output": {
      "address_objects": [
        "1.1.1.1",
        "1.1.1.1-24",
        "1.2.3.4",
        "2.2.2.2",
        "2.2.4.5",
        "5.182.39.91",
        "8.8.8.8",
        "8.8.8.9",
        "8.8.8.10",
        "8.8.8.11",
        "12.22.41.56",
        "51.75.16.138",
        "94.23.206.122",
        "115.78.128.70",
        "116.196.108.9",
        "149.6.37.18",
        "198.160.1.1",
        "212.143.21.43",
        "213.32.77.242",
        "Bad IP",
        "blockme.com",
        "domain.com",
        "Flagged IPs",
        "IPv6",
        "Malicious IPs",
        "snake264.com",
        "test ip",
        "test1.com",
        "example1.com",
        "example2.com"
      ],
      "success": true
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/palo_alto_pan_os:7.0.0 --debug run < tests/add_address_objects_to_group.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting..\nKey obtained\nrapid7/Palo Alto Firewall:7.0.0. Step name: get_addresses_from_group\n",
    "meta": {},
    "output": {
      "all_addresses": [
        "1.1.1.1",
        "1.1.1.1/24",
        "1.2.3.4",
        "2.2.2.2",
        "2.2.4.5",
        "5.182.39.91",
        "8.8.8.8",
        "8.8.8.9",
        "8.8.8.10",
        "8.8.8.11",
        "12.22.41.56",
        "51.75.16.138",
        "94.23.206.122",
        "115.78.128.70",
        "116.196.108.9",
        "149.6.37.18",
        "198.160.1.1",
        "212.143.21.43",
        "213.32.77.242",
        "1.1.1.2",
        "blockme.com",
        "domain.com",
        "2001:0db8:85a3:0000:0000:8a2e:0370:7334",
        "snake264.com",
        "20.20.20.20",
        "test1.com",
        "example1.com",
        "example2.com"
      ],
      "fqdn_addresses": [
        "blockme.com",
        "domain.com",
        "snake264.com",
        "test1.com",
        "example1.com",
        "example2.com"
      ],
      "ipv4_addresses": [
        "1.1.1.1",
        "1.1.1.1/24",
        "1.2.3.4",
        "2.2.2.2",
        "2.2.4.5",
        "5.182.39.91",
        "8.8.8.8",
        "8.8.8.9",
        "8.8.8.10",
        "8.8.8.11",
        "12.22.41.56",
        "51.75.16.138",
        "94.23.206.122",
        "115.78.128.70",
        "116.196.108.9",
        "149.6.37.18",
        "198.160.1.1",
        "212.143.21.43",
        "213.32.77.242",
        "1.1.1.2",
        "20.20.20.20"
      ],
      "ipv6_addresses": [
        "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
      ],
      "success": true
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/palo_alto_pan_os:7.0.0 --debug run < tests/get_addresses_from_group.json
</summary>
</details>

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator ExceptionValidator
[*] Executing validator CredentialsValidator
[*] Executing validator PasswordValidator
[*] Executing validator PrintValidator
[*] Executing validator ConfidentialValidator
[*] Executing validator DockerValidator
[*] Executing validator URLValidator
WARNING: URLs found that return a 4xx code. Verify they are publicly accessible and if not, update with a working URL.
violation: plugin.spec.yaml[594]: https://www.example.com/test.txt
violation: plugin.spec.yaml[597]: https://www.example.com/test.txt
violation: help.md[996]: https://www.example.com/test.txt|None|https://www.example.com/test.txt|
[*] Plugin failed validation! The following validation errors occurred:

Validator "HelpValidator" failed! 
	Cause: Help section contains non-matching title in line: [PAN-OS](https://www.paloaltonetworks.com/documentation/80/pan-os) is the software that runs all Palo Alto Networks next-generation firewalls. This plugin utilizes the [PAN-OS API](https://www.paloaltonetworks.com/documentation/80/pan-os/xml-api) to provide programmatic management o [...]

2021-02-01 19:28 UTC, jschipp-r7 approved these changes

2021-02-02 23:32 UTC, jschipp-r7 requested changes
@dsliwinski-r7  Can we merge this PR with this one and do a single release? https://github.com/rapid7/insightconnect-plugins/pull/798/

Also, let's hold off on the title change on the `Add Address Object to Group` action. You did the write thing there but we don't want customers to have to create a new connection which is what a major version bump causes in the product today. We will eventually be fixing this and for now we want to avoid a title change where possible

If you can merge the two PRs and revert that Add Address Object to Group action, then test the actions again to make sure all code was updated cleanly, then I'll merge.

2021-02-04 19:41 UTC, mrinehart-r7 requested changes

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/help.md
> +This action adds an address objects to an address group. Supports IPv6.
```suggestion
This action adds address objects to an address group. Supports IPv6.
```

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/help.md
> +This action is used to get an addresses from an address group.
```suggestion
This action is used to get addresses from an address group.
```

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/help.md
> +* 7.0.0 - New action Get Addresses from Group | Rename Add Address Object to Group action to Add Address Objects to Group and support adding a list of address objects
```suggestion
* 7.0.0 - New action Get Addresses from Group | Rename 'Add Address Object to Group' action to 'Add Address Objects to Group' and support adding a list of address objects
```

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_address_objects_to_group/action.py
> +            if type(name) == str:
```suggestion
            if isinstance(name, str):
```

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_address_objects_to_group/action.py
> +                names.append(name.get("#text"))
What if `name.get("#text")` returns a None?

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/plugin.spec.yaml
> +    description: Adds an address objects to an address group. Supports IPv6
```suggestion
    description: Adds address objects to an address group. Supports IPv6
```

2021-02-04 19:41 UTC, mrinehart-r7 commented on palo_alto_pan_os/plugin.spec.yaml
> +    description: Get an addresses from an address group
```suggestion
    description: Get addresses from an address group
```

2021-02-08 20:34 UTC, jschipp-r7 commented
@dsliwinski-r7 @dmandyna-r7 can we get this PR updated?

2021-02-09 19:38 UTC, dsliwinski-r7 commented
Hi @jschipp-r7! Sorry for the delay. I updated this PR and merged with [#798](https://github.com/rapid7/insightconnect-plugins/pull/798).

2021-02-09 23:12 UTC, jschipp-r7 approved these changes

2021-02-09 23:13 UTC, jschipp-r7 commented
@dsliwinski-r7 Has it been tested again after the code changes? If not, can you post an updated PR assessment?

2021-02-09 23:43 UTC, dsliwinski-r7 commented
@jschipp-r7 Yes, it has been tested. The PR assessment is up to date.

2021-02-10 00:08 UTC, jschipp-r7 commented on palo_alto_pan_os/help.md
> +This action adds address objects to an address group. Supports IPv6.
```suggestion
This action adds address objects to an address group. This action supports FQDNs, IPv4 and IPv6 addresses.
```

2021-02-10 00:08 UTC, jschipp-r7 commented on palo_alto_pan_os/help.md
> +* 6.1.0 - Improve error handling for xpath elements and paths in `pa_os_request.py` | New action `Get Addresses from Group` | Support adding a list of address objects in `Add Address Object to Group`
```suggestion
* 6.1.0 - Improve error handling for xpath elements and paths in `pa_os_request.py` | New action Get Addresses from Group | Support adding a list of address objects in Add Address Object to Group action
```

2021-02-10 00:09 UTC, jschipp-r7 commented on palo_alto_pan_os/plugin.spec.yaml
> +    description: Adds address objects to an address group. Supports IPv6
```suggestion
    description: Adds address objects to an address group
```

2021-02-10 11:58 UTC, dsliwinski-r7 commented
@jschipp-r7 I updated the description in the plugin.spec.yaml.

2021-02-10 14:25 UTC, jschipp-r7 approved these changes

2021-02-10 14:28 UTC, jschipp-r7 requested changes
@dsliwinski-r7 there's one more in the validator, we need to replace the unicode apostrophe with an ASCII one and regen

```
Validator "EncodingValidator" failed! 
	Cause: A forbidden character was found in the 'description' field of the spec.yaml file: When enabled, the Address input will accept a IP, CIDR, or domain name to search across the available Address Objects in the system. This is useful when you don’t know the Address Object by its name
```

2021-02-10 15:34 UTC, dsliwinski-r7 commented
@jschipp-r7 done

2021-02-10 17:21 UTC, jschipp-r7 approved these changes

2021-02-10 17:35 UTC, merged