[MC-36] Added first version of `add_app_to_policy` action.
rapid7/insightconnect-plugins pull request #818
Opened 2021-02-19 21:00 UTC by tfranckiewicz-r7

## Proposed Changes

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment

You must validate your work to reviewers:

1. Run `make validate` and make sure everything passes
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. Copy (`icon-plugin ... | pbcopy`) and paste the output in **a new post** on this PR.
4. Add UI screenshot of the workflow used for testing
5. Add UI screenshot of the job output used for testing
6. Add UI screenshot of the artifact (See rules in UI Checklist) used for testing

2021-02-19 21:42 UTC, jschipp-r7 commented on microsoft_intune/help.md
> +This action is used to add application to a policy.
```suggestion
This action is used to add an application to a policy.
```

2021-02-19 21:45 UTC, jschipp-r7 requested changes
@tfranckiewicz-r7

2021-02-19 21:45 UTC, jschipp-r7 commented on microsoft_intune/plugin.spec.yaml
> +        example:
Need an example device name

2021-02-19 21:45 UTC, jschipp-r7 commented on microsoft_intune/help.md
> +```
Need JSON formatted example output from a real request. Sanitize any data that shouldn't be viewable publicly

2021-02-19 21:45 UTC, jschipp-r7 commented on microsoft_intune/plugin.spec.yaml
> +    title: Add application to a policy
Title style this, will need to regen after - and make sure it's reflected in help.md

```suggestion
    title: Add Application to a Policy
```

2021-02-19 21:45 UTC, jschipp-r7 commented on microsoft_intune/help.md
> +{
if all the inputs are `required: true` we should add the other two options in this JSON example

2021-03-15 20:47 UTC, jschipp-r7 commented
@tfranckiewicz-r7 there's a few merge conflicts here to fix

2021-07-06 14:45 UTC, jmcadams-r7 approved these changes

2021-07-06 17:00 UTC, mrinehart-r7 requested changes

2021-07-19 14:54 UTC, jmcadams-r7 requested changes
Validation failed, Need to regen the plugin and re-commit.

2021-10-21 18:16 UTC, mberezin-r7 commented on plugins/microsoft_intune/icon_microsoft_intune/actions/delete_app_from_policy/action.py
> +            return {Output.SUCCESS: False}
Do we want to add logging to this exception?

2021-10-21 18:18 UTC, mberezin-r7 commented on plugins/microsoft_intune/icon_microsoft_intune/util/api.py
> +        for item in managed_app_policies_with_apps["apps"]:
```suggestion
        for item in managed_app_policies_with_apps.get("apps"):
```
Prevents `KeyError` if "apps" not in `managed_app_policies_with_apps`

2021-10-21 18:20 UTC, mberezin-r7 commented on plugins/microsoft_intune/icon_microsoft_intune/util/api.py
> +        for item in managed_app_policies_with_apps["apps"]:
```suggestion
        for item in managed_app_policies_with_apps.get("apps"):
```
Prevents `KeyError` if "apps" not in `managed_app_policies_with_apps`

2021-10-21 18:21 UTC, mberezin-r7 commented on plugins/microsoft_intune/icon_microsoft_intune/util/api.py
> +            if item["mobileAppIdentifier"]["packageId"] != application_package_id:
We should verify that these keys exist in this structure. Where can we find documentation about this?

2021-10-21 18:22 UTC, mberezin-r7 commented on plugins/microsoft_intune/icon_microsoft_intune/util/api.py
> +        for item in managed_app_policies["value"]:
```suggestion
        for item in managed_app_policies.get("value"):
```
Prevent `KeyError` if `"value"` not in `managed_app_policies`

2021-10-21 18:23 UTC, mberezin-r7 commented on plugins/microsoft_intune/icon_microsoft_intune/util/api.py
> +        for item in managed_app_list["content"]["appList"]:
We should also verify that this structure is consistent and we can hardcode these as constants. In which case, we should use programatic constants.

2022-06-06 18:06 UTC, closed without merging