MC-320 - InsightVM - List Inactive Assets - New Input
rapid7/insightconnect-plugins pull request #824
Opened 2021-02-24 22:41 UTC by dmandyna-r7

## Proposed Changes

Adding a new not required input - `size` to set a number of assets to return. Also the action will now return 500 results as default.  

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

### Assessment
#### Plugin Validation

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
Input violations: Trigger -> "New Scans": Missing ["|status_filter|[]string|['Successful']|False|List of scan statuses to match for trigger; options include: Aborted, Successful, Running, Stopped, Failed, Paused, Unknown|None|None|"] in help.md
Input violations: Trigger -> "New Vulnerability Exception": Missing ["|status_filter|[]string|['Under Review']|False|List of vulnerability statuses to match against. Options include: Under Review and Approved|None|None|"] in help.md
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator ExceptionValidator
WARNING: Use of 'PluginException' or 'ConnectionTestException' is recommended when raising an exception.
violation: komand_rapid7_insightvm/util/resource_helpers.py: line,  115
[*] Executing validator CredentialsValidator
[*] Executing validator PasswordValidator
[*] Executing validator PrintValidator
[*] Executing validator ConfidentialValidator
[*] Executing validator DockerValidator
[*] Executing validator URLValidator
WARNING: URLs found that return a 4xx code. Verify they are publicly accessible and if not, update with a working URL.
violation: plugin.spec.yaml[1747]: https://insightvm.example.com:3780
violation: plugin.spec.yaml[1750]: https://insightvm.example.com:3780
violation: help.md[211]: https://example.com:3780/api/3/vulnerability_exceptions/1
violation: help.md[82]: https://example.com:3780/api/3/assets/234/vulnerabilities/flash_player-cve-2017-11305/solution
violation: help.md[94]: https://example.com:3780/api/3/solutions/adobe-flash-windows-upgrade-latest
violation: help.md[221]: https://example.com:3780/api/3/users/1
violation: help.md[245]: https://example.com:3780/api/3/users/1
violation: help.md[232]: https://example.com:3780/api/3/vulnerabilities/ssh-default-account-admin-password-admin
violation: help.md[98]: https://example.com:3780/api/3/solutions/adobe-flash-windows-upgrade-latest/prerequisites
violation: help.md[118]: https://example.com:3780/api/3/solutions/adobe-flash-upgrade-28-0-0-126-windows
violation: help.md[102]: https://example.com:3780/api/3/solutions/adobe-flash-windows-upgrade-latest/supersedes
violation: help.md[1248]: https://example.com:3780/...
violation: help.md[1252]: https://example.com:3780/...
[*] Plugin failed validation! The following validation errors occurred:

Validator "HelpInputOutputValidator" failed! 
        Cause: Help.md is not in sync with plugin.spec.yaml. Please regenerate help.md by running 'icon-plugin generate python --regenerate' to rectify violations.

Validator "ExampleInputValidator" failed! 
        Cause: All inputs should have example field in plugin.spec. 
In action "get_scan": input "scan_id", there is no example field.
In action "get_site_assets": input "site_id", there is no example field.
In action "get_scan_assets": input "scan_id", there is no example field.
In action "download_report": input "id", there is no example field.
In action "download_report": input "instance", there is no example field.
In action "list_reports": input "name", there is no example field.
In action "list_reports": input "sort", there is no example field.
In action "get_vulnerability_affected_assets": input "vulnerability_id", there is no example field.
In action "create_tag": input "name", there is no example field.
In action "create_tag": input "type", there is no example field.
In action "create_tag": input "color", there is no example field.
In action "create_tag": input "searchCriteria", there is no example field.
In action "delete_tag": input "id", there is no example field.
In action "get_tags": input "name", there is no example field.
In action "get_tags": input "type", there is no example field.
In action "get_tag": input "id", there is no example field.
In action "get_tag_sites": input "id", there is no example field.
In action "get_tag_assets": input "id", there is no example field.
In action "get_tag_asset_groups": input "id", there is no example field.
In action "remove_asset_tag": input "asset_id", there is no example field.
In action "remove_asset_tag": input "tag_id", there is n [...]

2021-02-24 22:43 UTC, dmandyna-r7 commented
<details>

```
{
  "body": {
    "log": "rapid7/Rapid7 InsightVM:4.9.0. Step name: list_inactive_assets\nUsing https://integrations-ivm-console.example.com:3780//api/3/assets/search ...\nFetching results from page 0\nFetching up to 1 resources from endpoint page 0 ...\nGot 1 resources from page 1 / 639\n1 results consumed, returning results\n",
    "meta": {},
    "output": {
      "assets": [
        {
          "addresses": [
            {
              "ip": "192.168.50.1",
              "mac": "00:50:56:94:FC:3A"
            }
          ],
          "assessedForPolicies": false,
          "assessedForVulnerabilities": true,
          "history": [
            {
              "date": "2020-03-20T02:16:10.384Z",
              "scanId": 60,
              "type": "SCAN",
              "version": 1
            },
            {
              "date": "2020-03-20T02:25:17.110Z",
              "scanId": 61,
              "type": "SCAN",
              "version": 2
            },
            {
              "date": "2020-04-28T16:20:47.506Z",
              "scanId": 106,
              "type": "SCAN",
              "version": 3
            },
            {
              "date": "2020-05-12T18:14:48.832Z",
              "scanId": 121,
              "type": "SCAN",
              "version": 4
            },
            {
              "date": "2020-05-12T18:20:54.345Z",
              "scanId": 122,
              "type": "SCAN",
              "version": 5
            },
            {
              "date": "2020-05-13T08:07:40.112Z",
              "scanId": 123,
              "type": "SCAN",
              "version": 6
            },
            {
              "date": "2020-05-13T13:23:12.542Z",
              "scanId": 125,
              "type": "SCAN",
              "version": 7
            },
            {
              "date": "2020-05-14T08:07:47.439Z",
              "scanId": 126,
              "type": "SCAN",
              "version": 8
            },
            {
              "date": "2020-05-15T08:07:22.427Z",
              "scanId": 128,
              "type": "SCAN",
              "version": 9
            },
            {
              "date": "2020-05-16T08:07:43.017Z",
              "scanId": 130,
              "type": "SCAN",
              "version": 10
            },
            {
              "date": "2020-05-17T08:07:38.614Z",
              "scanId": 132,
              "type": "SCAN",
              "version": 11
            },
            {
              "date": "2020-05-18T08:07:35.755Z",
              "scanId": 134,
              "type": "SCAN",
              "version": 12
            },
            {
              "date": "2020-05-18T20:34:27.893Z",
              "scanId": 136,
              "type": "SCAN",
              "version": 13
            },
            {
              "date": "2020-05-19T08:07:52.113Z",
              "scanId": 137,
              "type": "SCAN",
              "version": 14
            },
            {
              "date": "2020-05-20T08:07:50.207Z",
              "scanId": 139,
              "type": "SCAN",
              "version": 15
            },
            {
              "date": "2020-05-21T08:08:18.726Z",
              "scanId": 141,
              "type": "SCAN",
              "version": 16
            },
            {
              "date": "2020-05-22T08:10:07.743Z",
              "scanId": 143,
              "type": "SCAN",
              "version": 17
            },
            {
              "date": "2020-05-23T08:07:27.674Z",
              "scanId": 145,
              "type": "SCAN",
              "version": 18
            },
            {
              "date": "2020-05-24T08:07:33.358Z",
              "scanId": 147,
              "type": "SCAN",
              "version": 19
            },
            {
              "date": "2020-05-25T08:07:29.905Z",
              "scanId": 149,
              "type": "SCAN",
              "version": 20
            },
            {
              "date": "2020-05-26T08:07:58.534Z",
              "scanId": 151,
              "type": "SCAN",
              "version": 21
            },
            {
              "date": "2020-05-27T08:08:08.538Z",
              "scanId": 153,
              "type": "SCAN",
              "version": 22
            },
            {
              "date": "2020-05-28T08:07:50.503Z",
              "scanId": 155,
              "type": "SCAN",
              "version": 23
            },
            {
              "date": "2020-05-29T08:07:39Z",
              "scanId": 157,
              "type": "SCAN",
              "version": 24
            },
            {
              "date": "2020-05-30T08:07:32.527Z",
              "scanId": 159,
              "type": "SCAN",
              "version": 25
            },
            {
              "date": "2020-05-31T08:07:33.801Z",
              "scanId": 161,
              "type": "SCAN",
              "version": 26
            },
            {
              "date": "2020-06-01T08:09:59.089Z",
              "scanId": 163,
              "type": "SCAN",
              "version": 27
            },
            {
              "date": "2020-06-02T08:07:42.564Z",
              "scanId": 165,
              "type": "SCAN",
              "version": 28
            },
            {
              "date": "2020-06-03T08:07:40.431Z",
              "scanId": 167,
              "type": "SCAN",
              "version": 29
            },
            {
              "date": "2020-06-04T08:08:19.966Z",
              "scanId": 169,
              "type": "SCAN",
              "version": 30
            },
            {
              "date": "2020-06-05T08:08:05.957Z",
              "scanId": 171,
              "type": "SCAN",
              "version": 31
            },
            {
              "date": "2020-06-06T08:10:45.045Z",
              "scanId": 173,
              "type": "SCAN",
              "version": 32
            },
            {
              "date": "2020-06-07T08:09:25.258Z",
              "scanId": 175,
              "type": "SCAN",
              "version": 33
            },
            {
              "date": "2020-06-08T08:07:51.917Z",
              "scanId": 177,
              "type": "SCAN",
              "version": 34
            },
            {
              "date": "2020-06-09T08:09:01.170Z",
              "scanId": 179,
              "type": "SCAN",
              "version": 35
            },
            {
              "date": "2020-06-10T08:08:40.763Z",
              "scanId": 181,
              "type": "SCAN",
              "version": 36
            },
            {
              "date": "2020-06-11T08:09:01.837Z",
              "scanId": 183,
              "type": "SCAN",
              "version": 37
            },
            {
              "date": "2020-06-12T08:08:15.373Z",
              "scanId": 185,
              "type": "SCAN",
              "version": 38
            },
            {
              "date": "2020-06-13T08:08:11.350Z",
              "scanId": 187,
              "type": "SCAN",
              "version": 39
            },
            {
              "date": "2020-06-14T08:07:40.592Z",
              "scanId": 189,
              "type": "SCAN",
              "version": 40
            },
            {
              "date": "2020-06-15T08:07:02.456Z",
              "scanId": 191,
              "type": "SCAN",
              "version": 41
            },
            {
              "date": "2020-06-16T08:07:24Z",
              "scanId": 193,
              "type": "SCAN",
              "version": 42
            },
            {
              "date": "2020-06-17T08:07:20.972Z",
              "scanId": 195,
              "type": "SCAN",
              "version": 43
            },
            {
              "date": "2020-06-25T08:07:05.626Z",
              "scanId": 220,
              "type": "SCAN",
              "version": 44
            },
            {
              "date": "2020-06-25T15:36:44 [...]

2021-02-24 22:43 UTC, dmandyna-r7 commented
<details>

```
{
  "body": {
    "log": "rapid7/Rapid7 InsightVM:4.9.0. Step name: list_inactive_assets\nUsing https://integrations-ivm-console.example.com:3780//api/3/assets/search ...\nFetching results from page 0\nFetching up to 5 resources from endpoint page 0 ...\nGot 5 resources from page 1 / 128\n5 results consumed, returning results\n",
    "meta": {},
    "output": {
      "assets": [
        {
          "addresses": [
            {
              "ip": "192.168.50.1",
              "mac": "00:50:56:94:FC:3A"
            }
          ],
          "assessedForPolicies": false,
          "assessedForVulnerabilities": true,
          "history": [
            {
              "date": "2020-03-20T02:16:10.384Z",
              "scanId": 60,
              "type": "SCAN",
              "version": 1
            },
            {
              "date": "2020-03-20T02:25:17.110Z",
              "scanId": 61,
              "type": "SCAN",
              "version": 2
            },
            {
              "date": "2020-04-28T16:20:47.506Z",
              "scanId": 106,
              "type": "SCAN",
              "version": 3
            },
            {
              "date": "2020-05-12T18:14:48.832Z",
              "scanId": 121,
              "type": "SCAN",
              "version": 4
            },
            {
              "date": "2020-05-12T18:20:54.345Z",
              "scanId": 122,
              "type": "SCAN",
              "version": 5
            },
            {
              "date": "2020-05-13T08:07:40.112Z",
              "scanId": 123,
              "type": "SCAN",
              "version": 6
            },
            {
              "date": "2020-05-13T13:23:12.542Z",
              "scanId": 125,
              "type": "SCAN",
              "version": 7
            },
            {
              "date": "2020-05-14T08:07:47.439Z",
              "scanId": 126,
              "type": "SCAN",
              "version": 8
            },
            {
              "date": "2020-05-15T08:07:22.427Z",
              "scanId": 128,
              "type": "SCAN",
              "version": 9
            },
            {
              "date": "2020-05-16T08:07:43.017Z",
              "scanId": 130,
              "type": "SCAN",
              "version": 10
            },
            {
              "date": "2020-05-17T08:07:38.614Z",
              "scanId": 132,
              "type": "SCAN",
              "version": 11
            },
            {
              "date": "2020-05-18T08:07:35.755Z",
              "scanId": 134,
              "type": "SCAN",
              "version": 12
            },
            {
              "date": "2020-05-18T20:34:27.893Z",
              "scanId": 136,
              "type": "SCAN",
              "version": 13
            },
            {
              "date": "2020-05-19T08:07:52.113Z",
              "scanId": 137,
              "type": "SCAN",
              "version": 14
            },
            {
              "date": "2020-05-20T08:07:50.207Z",
              "scanId": 139,
              "type": "SCAN",
              "version": 15
            },
            {
              "date": "2020-05-21T08:08:18.726Z",
              "scanId": 141,
              "type": "SCAN",
              "version": 16
            },
            {
              "date": "2020-05-22T08:10:07.743Z",
              "scanId": 143,
              "type": "SCAN",
              "version": 17
            },
            {
              "date": "2020-05-23T08:07:27.674Z",
              "scanId": 145,
              "type": "SCAN",
              "version": 18
            },
            {
              "date": "2020-05-24T08:07:33.358Z",
              "scanId": 147,
              "type": "SCAN",
              "version": 19
            },
            {
              "date": "2020-05-25T08:07:29.905Z",
              "scanId": 149,
              "type": "SCAN",
              "version": 20
            },
            {
              "date": "2020-05-26T08:07:58.534Z",
              "scanId": 151,
              "type": "SCAN",
              "version": 21
            },
            {
              "date": "2020-05-27T08:08:08.538Z",
              "scanId": 153,
              "type": "SCAN",
              "version": 22
            },
            {
              "date": "2020-05-28T08:07:50.503Z",
              "scanId": 155,
              "type": "SCAN",
              "version": 23
            },
            {
              "date": "2020-05-29T08:07:39Z",
              "scanId": 157,
              "type": "SCAN",
              "version": 24
            },
            {
              "date": "2020-05-30T08:07:32.527Z",
              "scanId": 159,
              "type": "SCAN",
              "version": 25
            },
            {
              "date": "2020-05-31T08:07:33.801Z",
              "scanId": 161,
              "type": "SCAN",
              "version": 26
            },
            {
              "date": "2020-06-01T08:09:59.089Z",
              "scanId": 163,
              "type": "SCAN",
              "version": 27
            },
            {
              "date": "2020-06-02T08:07:42.564Z",
              "scanId": 165,
              "type": "SCAN",
              "version": 28
            },
            {
              "date": "2020-06-03T08:07:40.431Z",
              "scanId": 167,
              "type": "SCAN",
              "version": 29
            },
            {
              "date": "2020-06-04T08:08:19.966Z",
              "scanId": 169,
              "type": "SCAN",
              "version": 30
            },
            {
              "date": "2020-06-05T08:08:05.957Z",
              "scanId": 171,
              "type": "SCAN",
              "version": 31
            },
            {
              "date": "2020-06-06T08:10:45.045Z",
              "scanId": 173,
              "type": "SCAN",
              "version": 32
            },
            {
              "date": "2020-06-07T08:09:25.258Z",
              "scanId": 175,
              "type": "SCAN",
              "version": 33
            },
            {
              "date": "2020-06-08T08:07:51.917Z",
              "scanId": 177,
              "type": "SCAN",
              "version": 34
            },
            {
              "date": "2020-06-09T08:09:01.170Z",
              "scanId": 179,
              "type": "SCAN",
              "version": 35
            },
            {
              "date": "2020-06-10T08:08:40.763Z",
              "scanId": 181,
              "type": "SCAN",
              "version": 36
            },
            {
              "date": "2020-06-11T08:09:01.837Z",
              "scanId": 183,
              "type": "SCAN",
              "version": 37
            },
            {
              "date": "2020-06-12T08:08:15.373Z",
              "scanId": 185,
              "type": "SCAN",
              "version": 38
            },
            {
              "date": "2020-06-13T08:08:11.350Z",
              "scanId": 187,
              "type": "SCAN",
              "version": 39
            },
            {
              "date": "2020-06-14T08:07:40.592Z",
              "scanId": 189,
              "type": "SCAN",
              "version": 40
            },
            {
              "date": "2020-06-15T08:07:02.456Z",
              "scanId": 191,
              "type": "SCAN",
              "version": 41
            },
            {
              "date": "2020-06-16T08:07:24Z",
              "scanId": 193,
              "type": "SCAN",
              "version": 42
            },
            {
              "date": "2020-06-17T08:07:20.972Z",
              "scanId": 195,
              "type": "SCAN",
              "version": 43
            },
            {
              "date": "2020-06-25T08:07:05.626Z",
              "scanId": 220,
              "type": "SCAN",
              "version": 44
            },
            {
              "date": "2020-06-25T15:36:44 [...]

2021-02-24 22:43 UTC, dmandyna-r7 commented
<details>

```
{
  "body": {
    "log": "rapid7/Rapid7 InsightVM:4.9.0. Step name: list_inactive_assets\nUsing https://integrations-ivm-console.example.com:3780//api/3/assets/search ...\nFetching results from page 0\nFetching up to 1 resources from endpoint page 0 ...\nGot 1 resources from page 1 / 639\n1 results consumed, returning results\n",
    "meta": {},
    "output": {
      "assets": [
        {
          "addresses": [
            {
              "ip": "192.168.50.1",
              "mac": "00:50:56:94:FC:3A"
            }
          ],
          "assessedForPolicies": false,
          "assessedForVulnerabilities": true,
          "history": [
            {
              "date": "2020-03-20T02:16:10.384Z",
              "scanId": 60,
              "type": "SCAN",
              "version": 1
            },
            {
              "date": "2020-03-20T02:25:17.110Z",
              "scanId": 61,
              "type": "SCAN",
              "version": 2
            },
            {
              "date": "2020-04-28T16:20:47.506Z",
              "scanId": 106,
              "type": "SCAN",
              "version": 3
            },
            {
              "date": "2020-05-12T18:14:48.832Z",
              "scanId": 121,
              "type": "SCAN",
              "version": 4
            },
            {
              "date": "2020-05-12T18:20:54.345Z",
              "scanId": 122,
              "type": "SCAN",
              "version": 5
            },
            {
              "date": "2020-05-13T08:07:40.112Z",
              "scanId": 123,
              "type": "SCAN",
              "version": 6
            },
            {
              "date": "2020-05-13T13:23:12.542Z",
              "scanId": 125,
              "type": "SCAN",
              "version": 7
            },
            {
              "date": "2020-05-14T08:07:47.439Z",
              "scanId": 126,
              "type": "SCAN",
              "version": 8
            },
            {
              "date": "2020-05-15T08:07:22.427Z",
              "scanId": 128,
              "type": "SCAN",
              "version": 9
            },
            {
              "date": "2020-05-16T08:07:43.017Z",
              "scanId": 130,
              "type": "SCAN",
              "version": 10
            },
            {
              "date": "2020-05-17T08:07:38.614Z",
              "scanId": 132,
              "type": "SCAN",
              "version": 11
            },
            {
              "date": "2020-05-18T08:07:35.755Z",
              "scanId": 134,
              "type": "SCAN",
              "version": 12
            },
            {
              "date": "2020-05-18T20:34:27.893Z",
              "scanId": 136,
              "type": "SCAN",
              "version": 13
            },
            {
              "date": "2020-05-19T08:07:52.113Z",
              "scanId": 137,
              "type": "SCAN",
              "version": 14
            },
            {
              "date": "2020-05-20T08:07:50.207Z",
              "scanId": 139,
              "type": "SCAN",
              "version": 15
            },
            {
              "date": "2020-05-21T08:08:18.726Z",
              "scanId": 141,
              "type": "SCAN",
              "version": 16
            },
            {
              "date": "2020-05-22T08:10:07.743Z",
              "scanId": 143,
              "type": "SCAN",
              "version": 17
            },
            {
              "date": "2020-05-23T08:07:27.674Z",
              "scanId": 145,
              "type": "SCAN",
              "version": 18
            },
            {
              "date": "2020-05-24T08:07:33.358Z",
              "scanId": 147,
              "type": "SCAN",
              "version": 19
            },
            {
              "date": "2020-05-25T08:07:29.905Z",
              "scanId": 149,
              "type": "SCAN",
              "version": 20
            },
            {
              "date": "2020-05-26T08:07:58.534Z",
              "scanId": 151,
              "type": "SCAN",
              "version": 21
            },
            {
              "date": "2020-05-27T08:08:08.538Z",
              "scanId": 153,
              "type": "SCAN",
              "version": 22
            },
            {
              "date": "2020-05-28T08:07:50.503Z",
              "scanId": 155,
              "type": "SCAN",
              "version": 23
            },
            {
              "date": "2020-05-29T08:07:39Z",
              "scanId": 157,
              "type": "SCAN",
              "version": 24
            },
            {
              "date": "2020-05-30T08:07:32.527Z",
              "scanId": 159,
              "type": "SCAN",
              "version": 25
            },
            {
              "date": "2020-05-31T08:07:33.801Z",
              "scanId": 161,
              "type": "SCAN",
              "version": 26
            },
            {
              "date": "2020-06-01T08:09:59.089Z",
              "scanId": 163,
              "type": "SCAN",
              "version": 27
            },
            {
              "date": "2020-06-02T08:07:42.564Z",
              "scanId": 165,
              "type": "SCAN",
              "version": 28
            },
            {
              "date": "2020-06-03T08:07:40.431Z",
              "scanId": 167,
              "type": "SCAN",
              "version": 29
            },
            {
              "date": "2020-06-04T08:08:19.966Z",
              "scanId": 169,
              "type": "SCAN",
              "version": 30
            },
            {
              "date": "2020-06-05T08:08:05.957Z",
              "scanId": 171,
              "type": "SCAN",
              "version": 31
            },
            {
              "date": "2020-06-06T08:10:45.045Z",
              "scanId": 173,
              "type": "SCAN",
              "version": 32
            },
            {
              "date": "2020-06-07T08:09:25.258Z",
              "scanId": 175,
              "type": "SCAN",
              "version": 33
            },
            {
              "date": "2020-06-08T08:07:51.917Z",
              "scanId": 177,
              "type": "SCAN",
              "version": 34
            },
            {
              "date": "2020-06-09T08:09:01.170Z",
              "scanId": 179,
              "type": "SCAN",
              "version": 35
            },
            {
              "date": "2020-06-10T08:08:40.763Z",
              "scanId": 181,
              "type": "SCAN",
              "version": 36
            },
            {
              "date": "2020-06-11T08:09:01.837Z",
              "scanId": 183,
              "type": "SCAN",
              "version": 37
            },
            {
              "date": "2020-06-12T08:08:15.373Z",
              "scanId": 185,
              "type": "SCAN",
              "version": 38
            },
            {
              "date": "2020-06-13T08:08:11.350Z",
              "scanId": 187,
              "type": "SCAN",
              "version": 39
            },
            {
              "date": "2020-06-14T08:07:40.592Z",
              "scanId": 189,
              "type": "SCAN",
              "version": 40
            },
            {
              "date": "2020-06-15T08:07:02.456Z",
              "scanId": 191,
              "type": "SCAN",
              "version": 41
            },
            {
              "date": "2020-06-16T08:07:24Z",
              "scanId": 193,
              "type": "SCAN",
              "version": 42
            },
            {
              "date": "2020-06-17T08:07:20.972Z",
              "scanId": 195,
              "type": "SCAN",
              "version": 43
            },
            {
              "date": "2020-06-25T08:07:05.626Z",
              "scanId": 220,
              "type": "SCAN",
              "version": 44
            },
            {
              "date": "2020-06-25T15:36:44 [...]

2021-02-24 22:45 UTC, dmandyna-r7 commented
Plugin Assessment results are attached as comments, the the output was too long to put in the PR description.
Also plugin validation is failing due to `Cause: Help.md is not in sync with plugin.spec.yaml. Please regenerate help.md by running 'icon-plugin generate python --regenerate' to rectify violations.`
I've tried re-generating the help.md, but that didn't resolve the issue.

2021-02-24 23:13 UTC, jschipp-r7 commented
@dmandyna-r7 There's a merge conflict

2021-02-25 14:30 UTC, jmcadams-r7 submitted a review, later dismissed

2021-02-25 21:07 UTC, jschipp-r7 commented
@dmandyna-r7 - There's a merge conflict

2021-02-25 21:08 UTC, jschipp-r7 commented
@dmandyna-r7 - Need to fix the conflict

2021-02-25 21:16 UTC, dmandyna-r7 commented
@jschipp-r7 Conflict resolved 🙂

2021-02-25 22:34 UTC, jschipp-r7 commented
@dmandyna-r7 Needs a few updates to pass the new linter checks (apply `black` formatting tool) and validator checks

2021-02-26 10:15 UTC, dmandyna-r7 commented
@jschipp-r7 I've applied the black formatting now. 

Regarding the validator check, the docker validator seems to be failing, due to the use of `pendulum` module in Dockerfile.

`RUN pip install pendulum==2.0.5`

It seems that it's a dependency for maya which is used in one of the actions.

2021-03-02 22:43 UTC, mrinehart-r7 submitted a review, later dismissed

2021-03-08 17:58 UTC, jschipp-r7 approved these changes

2021-03-08 17:59 UTC, jschipp-r7 requested changes
@dmandyna-r7 failing on 

```
Validator "DockerValidator" failed! 
	Cause: The plugin is either broken or the image might not be built.Please try 'icon-plugin build image' to rebuild the image.'icon-plugin run -c bash' will open a bash shell on the build container.
```

2021-03-12 16:11 UTC, dmandyna-r7 commented
Hey @mrinehart-r7  / @jschipp-r7 
I've downgraded the `maya` version to 0.5.0 - we are only using one function in one action, and there was no breaking changes between the 2 versions. The docker is not building successfully, the only validator that's failing is the example validator as a lot of inputs are missing `example: xxx`.

2021-03-17 18:54 UTC, mrinehart-r7 commented
@dmandyna-r7 ugh, yeah Maya is reliant on Pendulum and that project has been having some build issues since I believe around last year. Would it be possible for you to just get rid of Maya usage in the plugin and use something like datetime instead?

2021-03-19 19:02 UTC, dmandyna-r7 commented
<details>

```
{
  "body": {
    "log": "rapid7/Rapid7 InsightVM:4.9.0. Step name: get_expiring_vulnerability_exceptions\n",
    "meta": {},
    "output": {
      "exceptions": [
        {
          "expires": "2020-08-19T06:59:59.999Z",
          "id": 8,
          "links": [
            {
              "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerability_exceptions/8",
              "rel": "self"
            }
          ],
          "review": {
            "comment": "Vulnerability Exception was rejected via InsightConnect by .",
            "date": "2020-05-19T01:06:59.313Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/1",
                "id": 1,
                "rel": "Reviewer"
              }
            ],
            "name": "nxadmin",
            "user": 1
          },
          "scope": {
            "id": 18,
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerabilities/msft-cve-2018-8207",
                "id": "msft-cve-2018-8207",
                "rel": "Vulnerability"
              },
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/assets/18",
                "id": 18,
                "rel": "Asset"
              }
            ],
            "type": "asset",
            "vulnerability": "msft-cve-2018-8207"
          },
          "state": "rejected",
          "submit": {
            "comment": "User cannot update this software package for fear of breaking Super Important Business App. Reassess in 3 months.",
            "date": "2020-05-19T00:59:03.872145Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/3",
                "id": 3,
                "rel": "Submitter"
              }
            ],
            "name": "sonofengle",
            "reason": "acceptable risk",
            "user": 3
          }
        },
        {
          "expires": "2020-08-19T06:59:59.999Z",
          "id": 6,
          "links": [
            {
              "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerability_exceptions/6",
              "rel": "self"
            }
          ],
          "review": {
            "comment": "Vulnerability Exception was rejected via InsightConnect by .",
            "date": "2020-05-19T00:53:01.282Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/1",
                "id": 1,
                "rel": "Reviewer"
              }
            ],
            "name": "nxadmin",
            "user": 1
          },
          "scope": {
            "id": 18,
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerabilities/msft-cve-2018-8396",
                "id": "msft-cve-2018-8396",
                "rel": "Vulnerability"
              },
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/assets/18",
                "id": 18,
                "rel": "Asset"
              }
            ],
            "type": "asset",
            "vulnerability": "msft-cve-2018-8396"
          },
          "state": "rejected",
          "submit": {
            "comment": "User cannot update this software package for fear of breaking Super Important Business App. Reassess in 3 months.",
            "date": "2020-05-19T00:51:23.746616Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/3",
                "id": 3,
                "rel": "Submitter"
              }
            ],
            "name": "sonofengle",
            "reason": "acceptable risk",
            "user": 3
          }
        },
        {
          "expires": "2020-08-19T06:59:59.999Z",
          "id": 7,
          "links": [
            {
              "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerability_exceptions/7",
              "rel": "self"
            }
          ],
          "review": {
            "comment": "Vulnerability Exception was rejected via InsightConnect by .",
            "date": "2020-05-19T00:59:13.286Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/1",
                "id": 1,
                "rel": "Reviewer"
              }
            ],
            "name": "nxadmin",
            "user": 1
          },
          "scope": {
            "id": 18,
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerabilities/msft-cve-2018-0904",
                "id": "msft-cve-2018-0904",
                "rel": "Vulnerability"
              },
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/assets/18",
                "id": 18,
                "rel": "Asset"
              }
            ],
            "type": "asset",
            "vulnerability": "msft-cve-2018-0904"
          },
          "state": "rejected",
          "submit": {
            "comment": "User cannot update this software package for fear of breaking Super Important Business App. Reassess in 3 months.",
            "date": "2020-05-19T00:56:08.406554Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/3",
                "id": 3,
                "rel": "Submitter"
              }
            ],
            "name": "sonofengle",
            "reason": "acceptable risk",
            "user": 3
          }
        }
      ]
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/rapid7_insightvm:4.9.0 --debug run < tests/get_expiring_vulnerability_exceptions_1.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "rapid7/Rapid7 InsightVM:4.9.0. Step name: get_expiring_vulnerability_exceptions\n",
    "meta": {},
    "output": {
      "exceptions": [
        {
          "expires": "2020-08-19T06:59:59.999Z",
          "id": 8,
          "links": [
            {
              "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerability_exceptions/8",
              "rel": "self"
            }
          ],
          "review": {
            "comment": "Vulnerability Exception was rejected via InsightConnect by .",
            "date": "2020-05-19T01:06:59.313Z",
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/users/1",
                "id": 1,
                "rel": "Reviewer"
              }
            ],
            "name": "nxadmin",
            "user": 1
          },
          "scope": {
            "id": 18,
            "links": [
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/vulnerabilities/msft-cve-2018-8207",
                "id": "msft-cve-2018-8207",
                "rel": "Vulnerability"
              },
              {
                "href": "https://integrations-ivm-console.vuln.lax.rapid7.com:3780/api/3/assets/18",
                "id": 18,
                "rel": "Asset"
              }
            ],
            "type": "asset",
            "vulnerability": "msft-cve-2018-8207"
          },
          "state": "rejected",
          "submit": {
            "comment": "User cannot update this software package for fear of breaking Super Important Business App. Reassess in 3 months.",
            "date": "2020-05-19T00:59:03.872145Z",
            "links": [ [...]

2021-03-19 19:16 UTC, dmandyna-r7 commented
Hey @mrinehart-r7
I've removed the use of maya in the plugin with datetime. We can now build/make it, but the validator is failing on `ExampleInputValidator`.

2021-03-19 19:46 UTC, mrinehart-r7 approved these changes

2021-03-19 19:49 UTC, mrinehart-r7 approved these changes

2021-03-25 20:30 UTC, merged