New plugin - EasyVista
rapid7/insightconnect-plugins pull request #883
Opened 2021-04-15 18:44 UTC by dsliwinski-r7

## Proposed Changes

### Description

Describe the proposed changes:

  -

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/EasyVista:1.0.0. Step name: close_ticket\n",
    "meta": {},
    "output": {
      "result": {
        "href_hyperlink": "https://example.easyvista.com/api/v1/50005/requests/I210413_000004",
        "reference_number": "I210413_000004"
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/easyvista:1.0.0 --debug run < tests/close_ticket.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/EasyVista:1.0.0. Step name: create_ticket\n",
    "meta": {},
    "output": {
      "result": {
        "href_hyperlink": "https://example.easyvista.com/api/v1/50005/requests/I210413_000012",
        "reference_number": "I210413_000012"
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/easyvista:1.0.0 --debug run < tests/create_ticket.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/EasyVista:1.0.0. Step name: search_tickets\n",
    "meta": {},
    "output": {
      "results": {
        "HREF": "https://example.easyvista.com/api/v1/50005/requests?search=recipient.last_name:employee2",
        "record_count": "2",
        "records": [
          {
            "CATALOG_REQUEST": {
              "CATALOG_REQUEST_PATH": "Incidents/Test_Catalog",
              "CODE": "Test1",
              "HREF": "https://example.easyvista.com/api/v1/50005/catalog-requests/5218",
              "SD_CATALOG_ID": "5218",
              "TITLE_EN": "Test_Catalog"
            },
            "COMMENT": {
              "HREF": "https://example.easyvista.com/api/v1/50005/requests/I210408_000005/comment"
            },
            "DEPARTMENT": {
              "DEPARTMENT_CODE": "",
              "DEPARTMENT_EN": "-",
              "DEPARTMENT_ID": "5",
              "DEPARTMENT_LABEL": "",
              "DEPARTMENT_PATH": "",
              "HREF": "https://example.easyvista.com/api/v1/50005/departments/5"
            },
            "HREF": "https://example.easyvista.com/api/v1/50005/requests/I210408_000005",
            "KNOWNERROR": {
              "KNOWNERROR_PATH": "",
              "KNOWN_PROBLEMS_ID": "",
              "KP_NUMBER": "",
              "QUESTION_EN": ""
            },
            "LOCATION": {
              "CITY": "",
              "HREF": "https://example.easyvista.com/api/v1/50005/locations/6",
              "LOCATION_CODE": "",
              "LOCATION_EN": "-",
              "LOCATION_ID": "6",
              "LOCATION_PATH": ""
            },
            "MAX_RESOLUTION_DATE_UT": "",
            "RECIPIENT": {
              "BEGIN_OF_CONTRACT": "2020-12-29",
              "CELLULAR_NUMBER": " -",
              "DEPARTMENT_PATH": "",
              "EMPLOYEE_ID": "6",
              "E_MAIL": "user@example.com",
              "LAST_NAME": "employee2",
              "LOCATION_PATH": "",
              "PHONE_NUMBER": " -"
            },
            "REQUESTOR": {
              "BEGIN_OF_CONTRACT": "2020-12-29",
              "CELLULAR_NUMBER": " -",
              "DEPARTMENT_PATH": "",
              "EMPLOYEE_ID": "5",
              "E_MAIL": "user@example.com",
              "LAST_NAME": "employee1",
              "LOCATION_PATH": "",
              "PHONE_NUMBER": " -"
            },
            "REQUEST_ID": "7",
            "RFC_NUMBER": "I210408_000005",
            "STATUS": {
              "HREF": "https://example.easyvista.com/api/v1/50005/status/12",
              "STATUS_EN": "In progress",
              "STATUS_GUID": "{6E554FC1-1A5D-47E4-B303-CD98A8767AEC}",
              "STATUS_ID": "12"
            },
            "SUBMIT_DATE_UT": "2021-04-08T15:09:31.000Z"
          },
          {
            "CATALOG_REQUEST": {
              "CATALOG_REQUEST_PATH": "Incidents/Test_Catalog",
              "CODE": "Test1",
              "HREF": "https://example.easyvista.com/api/v1/50005/catalog-requests/5218",
              "SD_CATALOG_ID": "5218",
              "TITLE_EN": "Test_Catalog"
            },
            "COMMENT": {
              "HREF": "https://example.easyvista.com/api/v1/50005/requests/I210413_000002/comment"
            },
            "DEPARTMENT": {
              "DEPARTMENT_CODE": "1",
              "DEPARTMENT_EN": "Customer 1",
              "DEPARTMENT_ID": "6",
              "DEPARTMENT_LABEL": "",
              "DEPARTMENT_PATH": "Customer 1",
              "HREF": "https://example.easyvista.com/api/v1/50005/departments/6"
            },
            "HREF": "https://example.easyvista.com/api/v1/50005/requests/I210413_000002",
            "KNOWNERROR": {
              "KNOWNERROR_PATH": "",
              "KNOWN_PROBLEMS_ID": "",
              "KP_NUMBER": "",
              "QUESTION_EN": ""
            },
            "LOCATION": {
              "CITY": "",
              "HREF": "https://example.easyvista.com/api/v1/50005/locations/6",
              "LOCATION_CODE": "",
              "LOCATION_EN": "-",
              "LOCATION_ID": "6",
              "LOCATION_PATH": ""
            },
            "MAX_RESOLUTION_DATE_UT": "",
            "RECIPIENT": {
              "BEGIN_OF_CONTRACT": "2020-12-29",
              "CELLULAR_NUMBER": " -",
              "DEPARTMENT_PATH": "",
              "EMPLOYEE_ID": "6",
              "E_MAIL": "user@example.com",
              "LAST_NAME": "employee2",
              "LOCATION_PATH": "",
         [...]

2021-04-15 19:49 UTC, jmcadams-r7 requested changes
Really good code...just some minor nit picks on descriptions.

2021-04-15 19:49 UTC, jmcadams-r7 commented on easyvista/plugin.spec.yaml
> +        description: Comment explaining the updating of the ticket
```suggestion
        description: Comment that explains the reason for the update
```

2021-04-15 19:49 UTC, jmcadams-r7 commented on easyvista/plugin.spec.yaml
> +        description: Identifier of the object attributed by an external application
```suggestion
        description: Identifier of the object used by an external application
```

2021-04-15 19:49 UTC, jmcadams-r7 commented on easyvista/plugin.spec.yaml
> +        description: Comment explaining the closing of the ticket
```suggestion
        description: Comment that explains why the ticket was closed.
```

2021-04-15 19:52 UTC, jmcadams-r7 commented on easyvista/icon_easyvista/util/api.py
> +            url=self.base_url + endpoint,
You don't need to fix this, but next time you might want to use

```urllib.parse.urljoin(self.base_url, endpoint)```

Then you don't have to be careful with the trailing or leading `/ `

2021-04-15 20:24 UTC, mrinehart-r7 requested changes

2021-04-15 20:24 UTC, mrinehart-r7 commented on easyvista/plugin.spec.yaml
> +    description: Close the EasyVista ticket
```suggestion
    description: Close an EasyVista ticket
```

2021-04-15 20:24 UTC, mrinehart-r7 commented on easyvista/plugin.spec.yaml
> +    description: Search the EasyVista tickets
```suggestion
    description: Search for EasyVista tickets
```

2021-04-15 20:24 UTC, mrinehart-r7 commented on easyvista/plugin.spec.yaml
> +        description: Search query, if empty, returns all tickets
```suggestion
        description: Search query. Returns all tickets if left empty
```

2021-04-15 20:24 UTC, mrinehart-r7 commented on easyvista/help.md
> +This action is used to search the EasyVista tickets.
Can you include a link to the search filters with this? https://wiki.easyvista.com/xwiki/bin/view/Documentation/REST+API+-+Options+for+Fields#SearchFilterOptions

2021-04-15 20:33 UTC, jschipp-r7 commented on easyvista/plugin.spec.yaml
> +    example: https://example.easyvista.com
If a user provides a trailing path or extra space or newline we should strip it.

Sometimes users will copy/paste from browser and not think about it:

`https://example.easyvista.com/home`
`https://example.easyvista.com    `

2021-04-15 20:35 UTC, jschipp-r7 commented on easyvista/plugin.spec.yaml
> +  hostname:
The example looks like a URL rather than a hostname. If so, we should rename this to `url` and update the description and title.

2021-04-21 16:17 UTC, jmcadams-r7 approved these changes

2021-04-21 16:31 UTC, mrinehart-r7 approved these changes

2021-04-21 16:32 UTC, merged