[MC-500] Fix issues with `threat_type` and `threat_status` inputs in Proofpoint Tap plugin
rapid7/insightconnect-plugins pull request #926
Opened 2021-05-29 16:32 UTC by dsliwinski-r7

## Proposed Changes

Fix issues with `threat_type` and `threat_status` inputs in Proofpoint Tap plugin

### Description

Add `all` value to `threat_type` and `threat_status` enum inputs in Get Blocked Clicks, Get Permitted Clicks, Get Blocked Messages, Get Delivered Threats, Get All Threats actions
Ticket: MC-500

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.1. Step name: get_all_threats\n",
    "meta": {},
    "output": {
      "results": {
        "clicksBlocked": [],
        "clicksPermitted": [],
        "messagesBlocked": [
          {
            "GUID": "dW6_95qHad3zsRiW0D1-wwav1PdRJyN_",
            "QID": "38gq638ykc-1",
            "ccAddresses": [],
            "cluster": "proofpointdemo_cloudadminuidemo_hosted",
            "completelyRewritten": false,
            "fromAddress": [
              "user@example.com"
            ],
            "headerFrom": "\"Amazon.co.jp\" \u003cuser@example.com\u003e",
            "id": "37858ca1-8812-5267-7596-98c8361013c0",
            "impostorScore": 0,
            "malwareScore": 0,
            "messageID": "\u003cuser@example.com\u003e",
            "messageParts": [
              {
                "contentType": "text/html",
                "disposition": "inline",
                "filename": "text.html",
                "md5": "4de830b8b047410a77e5bd9509b047ff",
                "oContentType": "text/html",
                "sha256": "a8b74a69355540183273d215184719..."
              },
              {
                "contentType": "text/plain",
                "disposition": "inline",
                "filename": "text.txt",
                "md5": "bf1215c913e2c8d339fffe56ae30dd08",
                "oContentType": "text/plain",
                "sha256": "9a485598f1d5086b5bef1bb456580d..."
              }
            ],
            "messageSize": 45824,
            "messageTime": "2021-05-13T15:56:29.000Z",
            "modulesRun": [
              "av",
              "spf",
              "spam",
              "dmarc",
              "urldefense"
            ],
            "phishScore": 100,
            "policyRoutes": [
              "default_inbound",
              "allow_relay",
              "firewallsafe",
              "internalnet"
            ],
            "quarantineFolder": "Phish",
            "quarantineRule": "phish",
            "recipient": [
              "user@example.com"
            ],
            "replyToAddress": [],
            "sender": "user@example.com",
            "senderIP": "208.86.203.10",
            "spamScore": 100,
            "subject": "=?UTF-8?B?44CQ44GK5a6i5qeY54++5Zyo5Yip55So44Gn44GN44G+44Gb44KT44CR?=",
            "threatsInfoMap": [
              {
                "classification": "phish",
                "threat": "134.122.177.43/ap/signin",
                "threatID": "700c044a4b2d5b1448f62aea91a93ed...",
                "threatStatus": "active",
                "threatTime": "2021-05-13T13:02:56.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              },
              {
                "classification": "phish",
                "threat": "http://134.122.177.43/ap/signin?openid.pape.max_auth_age=0\u0026openid.return_to=https%!A(MISSING)%!F(MISSING)%!F(MISSING)www.amazon.co.jp%!F(MISSING)%!F(MISSING)ref_%!D(MISSING)nav_em_hd_re_signin\u0026openid.identity=http%!A(MISSING)%!F(MISSING)%!F(MISSING)specs.openid.net%!F(MISSING)auth%!F(MISSING)2.0%!F(MISSING)identifier_select\u0026openid.assoc_handle=jpflex\u0026openid.mode=checkid_setup\u0026key=a@b.c\u0026openid.claimed_id=http%!A(MISSING)%!F(MISSING)%!F(MISSING)specs.openid.net%!F(MISSING)auth%!F(MISSING)2.0%!F(MISSING)identifier_select\u0026openid.ns=http%!A(MISSING)%!F(MISSING)%!F(MISSING)specs.openid.net%!F(MISSING)auth%!F(MISSING)2.0\u0026\u0026ref_=nav_em_hd_clc_signin",
                "threatID": "7d004975253288284f695b5eb77...",
                "threatStatus": "active",
                "threatTime": "2021-05-13T13:02:08.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              },
              {
                "classification": "phish",
                "threat": "http://134.122.177.43/ap/signin?openid.pape.max_auth_age=0\u0026openid.return_to=https://www.amazon.co.jp/?ref_=nav_em_hd_re_signin\u0026openid.identity=http://specs.openid.net/auth/2.0/identifier_select\u0026openid.assoc_handle=jpflex\u0026openid.mode=checkid_setup\u0026key=a@b.c\u0026openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select\u0026openid.ns=http://specs.openid.net/auth/2.0\u0026\u0026ref_=nav_em_hd_clc_signin",
                "threatID": "1d1fcd1358d8ec4917999bdf9e662...",
                "threatStatus": "active",
                "threatTime": "2021-05-13T13:02:16.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              }
            ],
            "toAddresses": [
              "user@example.com"
            ],
            "xmailer": "Foxmail 7, 0, 1, 91[cn]"
          },
          {
            "GUID": "ByGtTC-xX5nZwnCMPfjOZoQQhtnehHpl",
            "QID": "38gpjm92kv-1",
            "ccAddresses": [],
            "cluster": "proofpointdemo_cloudadminuidemo_hosted",
            "completelyRewritten": false,
            "fromAddress": [
              "user@example.com"
            ],
            "headerFrom": "\"DocuSign Electronic Signature and Invoice\" \u003cuser@example.com\u0 [...]

2021-06-02 18:32 UTC, jmcadams-r7 requested changes

2021-06-02 18:32 UTC, jmcadams-r7 commented on proofpoint_tap/setup.py
> +      version="2.0.1",
It's a major version bump. You're requiring inputs that weren't required before.

2021-06-02 19:37 UTC, mrinehart-r7 requested changes
Version needs to be bumped to 3.0.0 due to the change in optional inputs to required inputs.

2021-06-03 14:32 UTC, dsliwinski-r7 commented
## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:3.0.0. Step name: get_all_threats\n",
    "meta": {},
    "output": {
      "results": {
        "clicksBlocked": [],
        "clicksPermitted": [],
        "messagesBlocked": [
          {
            "GUID": "newB3SUHJFH9IVE07bMdjVoOrrnKE8fo",
            "QID": "38vxe8b9vt-1",
            "ccAddresses": [],
            "cluster": "proofpointdemo_cloudadminuidemo_hosted",
            "completelyRewritten": false,
            "fromAddress": [
              "user@example.com"
            ],
            "headerFrom": "\"MyJCB\" \u003cuser@example.com\u003e",
            "id": "b474661b-2516-db5f-af2e-7d2833966f6b",
            "impostorScore": 0,
            "malwareScore": 0,
            "messageID": "\u003cuser@example.com\u003e",
            "messageParts": [
              {
                "contentType": "text/plain",
                "disposition": "inline",
                "filename": "text.txt",
                "md5": "fa4ee9e92ceed56ba04bce6bf00ccb13",
                "oContentType": "text/plain",
                "sha256": "aa267897525bd19d62127a7c8e4b..."
              },
              {
                "contentType": "text/html",
                "disposition": "inline",
                "filename": "text.html",
                "md5": "42aa926ac511d907f8c7f910b44535da",
                "oContentType": "text/html",
                "sha256": "dd787c5c65f8ea9ea5f78e8ce89bbb6..."
              }
            ],
            "messageSize": 21595,
            "messageTime": "2021-06-02T11:04:16.000Z",
            "modulesRun": [
              "av",
              "spf",
              "spam",
              "dmarc",
              "urldefense"
            ],
            "phishScore": 100,
            "policyRoutes": [
              "default_inbound",
              "allow_relay",
              "firewallsafe",
              "internalnet"
            ],
            "quarantineFolder": "Phish",
            "quarantineRule": "phish",
            "recipient": [
              "user@example.com"
            ],
            "replyToAddress": [],
            "sender": "hkmyasq@jcb.co.jp",
            "senderIP": "208.86.203.10",
            "spamScore": 100,
            "subject": "=?utf-8?B?44CQ6YeN6KaB44Gq44GK55+l44KJ44Gb44CR44CQTXlKQ0LjgJHjgZTliKnnlKjnoro=?=\r\n\t=?utf-8?B?6KqN44Gu44GK6aGY44GE?=",
            "threatsInfoMap": [
              {
                "classification": "phish",
                "threat": "my-jcb-jp.top",
                "threatID": "ad96286b011e69b493660f7673d...",
                "threatStatus": "active",
                "threatTime": "2021-06-02T01:21:09.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              },
              {
                "classification": "phish",
                "threat": "http://www.my-jcb-jp.top/",
                "threatID": "d36472bf0cf16481040d26642c016...",
                "threatStatus": "active",
                "threatTime": "2021-06-02T01:32:58.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              },
              {
                "classification": "phish",
                "threat": "www.my-jcb-jp.top/",
                "threatID": "76ed0111c0cf04da3af391390b53956...",
                "threatStatus": "active",
                "threatTime": "2021-06-02T04:25:25.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              },
              {
                "classification": "phish",
                "threat": "https://www.my-jcb-jp.top/",
                "threatID": "99e8d1786ef7bd7de78232add61562...",
                "threatStatus": "active",
                "threatTime": "2021-06-02T01:19:07.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              }
            ],
            "toAddresses": [
              "user@example.com"
            ],
            "xmailer": "Microsoft Outlook Express 6.00.2900.5512"
          },
          {
            "GUID": "AZ79e3f1BLiNYsovudQ2OIa1IoXYtLIC",
            "QID": "38wjq6j36w-1",
            "ccAddresses": [],
            "cluster": "proofpointdemo_cloudadminuidemo_hosted",
            "completelyRewritten": false,
            "fromAddress": [
              "user@example.com"
            ],
            "headerFrom": "\"=?UTF-8?B?4pyJIA==?=freepochta.info\" \u003cuser@example.com\u003e",
            "id": "2e113098-8a4c-3f43-8a6b-33a6bc3e3f18",
            "impostorScore": 0,
            "malwareScore": 0,
            "messageID": "\u003cuser@example.com\u003e",
            "messageParts": [
              {
                "contentType": "text/plain",
                "disposition": "inline",
                "filename": "text.txt",
                "md5": "7d283d69c9aa3a20bbb21c3baabddc8e",
                "oContentType": "text/plain",
                "sha256": "ab3f03f1f681df8e20ba5245..."
              },
              {
                "contentType": "text/html",
                "disposition": "inline",
                "filename": "text.html",
                "md5": "76f69ae253661e854910daec660cd469",
                "oContentType": "text/html",
                "sha256": "4a3200307ebc1838c8a611acfd20c1..."
              }
            ],
            "messageSize": 26591,
            "messageTime": "2021-06-02T10:55:13.000Z",
            "modulesRun": [
              "av",
              "spf",
              "spam",
              "dmarc",
              "urldefense"
            ],
            "phishScore": 100,
            "policyRoutes": [
              "default_inbound",
              "allow_relay",
              "firewallsafe",
              "internalnet"
            ],
            "quarantineFolder": "Phish",
            "quarantineRule": "phish",
            "recipient": [
              "user@example.com"
            ],
            "replyToAddress": [],
            "sender": "user@example.com",
            "senderIP": "208.86.203.10",
            "spamScore": 100,
            "subject": "MAILBOX SHUTDOWN PROCESS - BLACKLIST SUMMARY",
            "threatsInfoMap": [
              {
                "classification": "phish",
                "threat": "cphost-3f6ea.web.app/",
                "threatID": "66ac3078f604e0bd06957862feaf88d4...",
                "threatStatus": "active",
                "threatTime": "2021-06-01T14:14:45.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              },
              {
                "classification": "phish",
                "threat": "cphost-3f6ea.web.app",
                "threatID": "2b09ae8c68cac2cf819f0f92465c3...",
                "threatStatus": "active",
                "threatTime": "2021-06-01T10:23:59.000Z",
                "threatType": "url",
                "threatUrl": "https://threatinsight.proofpoint.com/e65934ff-e650..."
              }
            ],
            "toAddresses": [
              "user@example.com"
            ]
          },
          {
            "GUID": "_5jDhouY9pMNv9DJdp1LaF5Ppslcz3o-",
            "QID": "38wjq6j2t7-1",
            "ccAddresses": [],
            "cluster": "proofpointdemo_cloudadminuidemo_hosted",
            "completelyRewritten": false,
            "fromAddress": [
              "user@example.com"
            ],
            "headerFrom": "\"=?UTF-8?B?4pyJIA==?=wwwfreemail.info\" \u003cuser@example.com\u003e",
            "id": "53c09eca-86e3-61cb-155d-09376bba36ef",
            "impostorScore": 0,
            "malwareScore": 0,
            "messageID": "\u003cuser@example.com\u003e",
            "messageParts": [
              {
            [...]

2021-06-04 14:09 UTC, jmcadams-r7 approved these changes

2021-06-16 16:57 UTC, mrinehart-r7 requested changes

2021-06-16 16:57 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/help.md
> +* 3.0.0 - Add `all` value to `threat_type` and `threat_status` enum inputs in Get Blocked Clicks, Get Permitted Clicks, Get Blocked Messages, Get Delivered Threats, Get All Threats actions
```suggestion
* 3.0.0 - Add `all` value to Threat Type and Threat Status inputs in Get Blocked Clicks, Get Permitted Clicks, Get Blocked Messages, Get Delivered Threats, Get All Threats actions
```

2021-06-16 16:57 UTC, mrinehart-r7 approved these changes

2021-06-16 17:00 UTC, lmilby-r7 approved these changes

2021-06-16 17:00 UTC, merged