Adding decoding URls with quotable encoding in URL Decode action in Proofpoint TAP plugin
rapid7/insightconnect-plugins pull request #931
Opened 2021-05-31 18:05 UTC by r7-kszczepanskagorna

## Proposed Changes

### Description
Adding decoding URls with quotable encoding in URL Decode action in Proofpoint TAP plugin
Tickect MC-515

### Testing

Any testing information goes here.

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.0. Step name: url_decode\n",
    "meta": {},
    "output": {
      "results": {
        "urls": [
          {
            "decodedUrl": "http://www.bouncycastle.org/",
            "encodedUrl": "https://urldefense.proofpoint.com/v1/url?u=http://www.bouncycastle.org/\u0026amp;k=oIvRg1%!B(MISSING)dGAgOoM1BIlLLqw%!D(MISSING)%!D(MISSING)%!A(MISSING)\u0026amp;r=IKM5u8%!B(MISSING)%!F(MISSING)%!F(MISSING)i8EBhWOS%!B(MISSING)qGbTqCC%!B(MISSING)rMqWI%!F(MISSING)VfEAEsQO%!F(MISSING)0Y%!D(MISSING)%!A(MISSING)\u0026amp;m=Ww6iaHO73mDQpPQwOwfLfN8WMapqHyvtu8jM8SjqmVQ%!D(MISSING)%!A(MISSING)\u0026amp;s=d3583cfa53dade97025bc6274c6c8951dc29fe0f38830cf8e5a447723b9f1c9a\"",
            "success": true
          },
          {
            "decodedUrl": "https://google.com:443/search?q=a+test\u0026gs=ps",
            "encodedUrl": "https://urldefense.com/v3/__https://google.com:443/search?q=a*test\u0026gs=ps__;Kw!-612Flbf0JvQ3kNJkRi5Jg!Ue6tQudNKaShHg93trcdjqDP8se2ySE65jyCIe2K1D_uNjZ1Lnf6YLQERujngZv9UWf66ujQIQ$",
            "success": true
          }
        ]
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:2.0.1 --debug run < tests/url_decode.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.0. Step name: url_decode\n",
    "meta": {},
    "output": {
      "results": {
        "urls": [
          {
            "decodedUrl": "http://www.adobe.com",
            "encodedUrl": "https://urldefense.proofpoint.com/v2/url?u=http-3A__www.adobe.com\u0026d=DwMFAg\u0026c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM\u0026r=qz5Nye49FfyB5hGQyu28CmCl4j-JuT-5fRrqkD5GgOM\u0026m=QyWbhzT6tTSmG0PkgURbBDFXWsffEz6VJtOFlHPGs5A\u0026s=rK9Hy_NPWtw6vwc7yG4zoBSWS_nOtkzg4pbYpJGfFb0\u0026e=",
            "success": true
          }
        ]
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:2.0.1 --debug run < tests/url_decode_quotable.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.0. Step name: url_decode\n",
    "meta": {},
    "output": {
      "results": {
        "urls": [
          {
            "decodedUrl": "http://www.bouncycastle.org/",
            "encodedUrl": "https://urldefense.proofpoint.com/v1/url?u=http://www.bouncycastle.org/\u0026amp;k=oIvRg1%!B(MISSING)dGAgOoM1BIlLLqw%!D(MISSING)%!D(MISSING)%!A(MISSING)\u0026amp;r=IKM5u8%!B(MISSING)%!F(MISSING)%!F(MISSING)i8EBhWOS%!B(MISSING)qGbTqCC%!B(MISSING)rMqWI%!F(MISSING)VfEAEsQO%!F(MISSING)0Y%!D(MISSING)%!A(MISSING)\u0026amp;m=Ww6iaHO73mDQpPQwOwfLfN8WMapqHyvtu8jM8SjqmVQ%!D(MISSING)%!A(MISSING)\u0026amp;s=d3583cfa53dade97025bc6274c6c8951dc29fe0f38830cf8e5a447723b9f1c9a\"",
            "success": true
          },
          {
            "decodedUrl": "https://google.com:443/search?q=a+test\u0026gs=ps",
            "encodedUrl": "https://urldefense.com/v3/__https://google.com:443/search?q=a*test\u0026gs=ps__;Kw!-612Flbf0JvQ3kNJkRi5Jg!Ue6tQudNKaShHg93trcdjqDP8se2ySE65jyCIe2K1D_uNjZ1Lnf6YLQERujngZv9UWf66ujQIQ$",
            "success": true
          }
        ]
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:2.0.1 --debug run < tests/url_decode_no_connection.json
</summary>
</details>

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
Input violations: Action -> "Get Blocked Clicks": Missing ["|time_start|string|None|False|The start of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T21:00:00Z. If left empty, it will be calculated from the 'time_end' parameter. If the 'time_end' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 21:00:00|", "|time_end|string|None|False|The end of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T22:00:00Z. If left empty, it will be calculated from th [...]

2021-05-31 18:33 UTC, r7-kszczepanskagorna commented
Hey :) HelpInputOutputValidator fails because of the date format in the examples. I did not change that examples to the one suggested by the validator because it will be incorrect.

2021-06-02 18:14 UTC, mrinehart-r7 requested changes

2021-06-02 18:14 UTC, mrinehart-r7 commented on proofpoint_tap/help.md
> +* 2.0.1 - Adding decoding URls with quotable encoding in URL Decode action
```suggestion
* 2.0.1 - Adding decoding URLs with quotable encoding in URL Decode action
```

2021-06-02 18:14 UTC, mrinehart-r7 commented on proofpoint_tap/komand_proofpoint_tap/actions/url_decode/action.py
> +            except UnicodeDecodeError as _:
```suggestion
            except UnicodeDecodeError:
```
No need to use _ to ignore catching the exception variable

2021-06-04 14:06 UTC, jmcadams-r7 submitted a review, later dismissed

2021-06-09 17:01 UTC, r7-kszczepanskagorna commented
## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.1. Step name: url_decode\n",
    "meta": {},
    "output": {
      "results": {
        "urls": [
          {
            "decodedUrl": "http://www.bouncycastle.org/",
            "encodedUrl": "https://urldefense.proofpoint.com/v1/url?u=http://www.bouncycastle.org/\u0026amp;k=oIvRg1%!B(MISSING)dGAgOoM1BIlLLqw%!D(MISSING)%!D(MISSING)%!A(MISSING)\u0026amp;r=IKM5u8%!B(MISSING)%!F(MISSING)%!F(MISSING)i8EBhWOS%!B(MISSING)qGbTqCC%!B(MISSING)rMqWI%!F(MISSING)VfEAEsQO%!F(MISSING)0Y%!D(MISSING)%!A(MISSING)\u0026amp;m=Ww6iaHO73mDQpPQwOwfLfN8WMapqHyvtu8jM8SjqmVQ%!D(MISSING)%!A(MISSING)\u0026amp;s=d3583cfa53dade97025bc6274c6c8951dc29fe0f38830cf8e5a447723b9f1c9a\"",
            "success": true
          },
          {
            "decodedUrl": "https://google.com:443/search?q=a+test\u0026gs=ps",
            "encodedUrl": "https://urldefense.com/v3/__https://google.com:443/search?q=a*test\u0026gs=ps__;Kw!-612Flbf0JvQ3kNJkRi5Jg!Ue6tQudNKaShHg93trcdjqDP8se2ySE65jyCIe2K1D_uNjZ1Lnf6YLQERujngZv9UWf66ujQIQ$",
            "success": true
          }
        ]
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:2.0.1 --debug run < tests/url_decode.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.1. Step name: url_decode\n",
    "meta": {},
    "output": {
      "results": {
        "urls": [
          {
            "decodedUrl": "http://www.adobe.com",
            "encodedUrl": "https://urldefense.proofpoint.com/v2/url?u=http-3A__www.adobe.com\u0026d=DwMFAg\u0026c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM\u0026r=qz5Nye49FfyB5hGQyu28CmCl4j-JuT-5fRrqkD5GgOM\u0026m=QyWbhzT6tTSmG0PkgURbBDFXWsffEz6VJtOFlHPGs5A\u0026s=rK9Hy_NPWtw6vwc7yG4zoBSWS_nOtkzg4pbYpJGfFb0\u0026e=",
            "success": true
          }
        ]
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:2.0.1 --debug run < tests/url_decode2.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint TAP:2.0.1. Step name: url_decode\n",
    "meta": {},
    "output": {
      "results": {
        "urls": [
          {
            "decodedUrl": "http://www.bouncycastle.org/",
            "encodedUrl": "https://urldefense.proofpoint.com/v1/url?u=http://www.bouncycastle.org/\u0026amp;k=oIvRg1%!B(MISSING)dGAgOoM1BIlLLqw%!D(MISSING)%!D(MISSING)%!A(MISSING)\u0026amp;r=IKM5u8%!B(MISSING)%!F(MISSING)%!F(MISSING)i8EBhWOS%!B(MISSING)qGbTqCC%!B(MISSING)rMqWI%!F(MISSING)VfEAEsQO%!F(MISSING)0Y%!D(MISSING)%!A(MISSING)\u0026amp;m=Ww6iaHO73mDQpPQwOwfLfN8WMapqHyvtu8jM8SjqmVQ%!D(MISSING)%!A(MISSING)\u0026amp;s=d3583cfa53dade97025bc6274c6c8951dc29fe0f38830cf8e5a447723b9f1c9a\"",
            "success": true
          },
          {
            "decodedUrl": "https://google.com:443/search?q=a+test\u0026gs=ps",
            "encodedUrl": "https://urldefense.com/v3/__https://google.com:443/search?q=a*test\u0026gs=ps__;Kw!-612Flbf0JvQ3kNJkRi5Jg!Ue6tQudNKaShHg93trcdjqDP8se2ySE65jyCIe2K1D_uNjZ1Lnf6YLQERujngZv9UWf66ujQIQ$",
            "success": true
          }
        ]
      }
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:2.0.1 --debug run < tests/url_decode_no_connection.json
</summary>
</details>
<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../../tools/Makefiles/Helpers.mk ../../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator LoggingValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
Input violations: Action -> "Get Blocked Clicks": Missing ["|time_start|string|None|False|The start of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T21:00:00Z. If left empty, it will be calculated from the 'time_end' parameter. If the 'time_end' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 21:00:00|", "|time_end|string|None|False|The end of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T22:00:00Z. If left empty, it will be calculated from the 'time_start' parameter. If the 'time_start' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 22:00:00|"] in help.md
Input violations: Action -> "Get Permitted Clicks": Missing ["|time_start|string|None|False|The start of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T21:00:00Z. If left empty, it will be calculated from the 'time_end' parameter. If the 'time_end' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 21:00:00|", "|time_end|string|None|False|The end of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T22:00:00Z. If left empty, it will be calculated from the 'time_start' parameter. If the 'time_start' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 22:00:00|"] in help.md
Input violations: Action -> "Get Blocked Messages": Missing ["|time_start|string|None|False|The start of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T21:00:00Z. If left empty, it will be calculated from the 'time_end' parameter. If the 'time_end' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 21:00:00|", "|time_end|string|None|False|The end of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T22:00:00Z. If left empty, it will be calculated from the 'time_start' parameter. If the 'time_start' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 22:00:00|"] in help.md
Input violations: Action -> "Get Delivered Threats": Missing ["|time_start|string|None|False|The start of the data retrieval period as ISO8601-formatted date e.g 2021-04-20T21:00:00Z. If left empty, it will be calculated from the 'time_end' parameter. If the 'time_end' parameter is empty, data from one hour before the current API server time will be returned. The minimum time range is thirty seconds. The maximum time range is one hour|None|2021-04-20 21:00:00|", "|time_end|string|N [...]

2021-06-14 20:07 UTC, mrinehart-r7 requested changes

2021-06-14 20:07 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/help.md
> +* 2.0.1 - Adding decoding URLs with quotable encoding in URL Decode action
```suggestion
* 2.0.1 - Fix decoding URLs with quotable encoding in URL Decode action
```

2021-06-15 13:36 UTC, gusingh-r7 requested changes
Need to remove proofpoint_tap from the root directory.

2021-06-15 15:54 UTC, mrinehart-r7 approved these changes

2021-06-15 15:58 UTC, mrinehart-r7 commented
> Need to remove proofpoint_tap from the root directory.

Removed it

2021-06-15 15:58 UTC, mrinehart-r7 submitted a review, later dismissed

2021-06-15 16:03 UTC, gusingh-r7 submitted a review, later dismissed
LGTM except for a couple of validator failures.

2021-07-04 19:18 UTC, r7-kszczepanskagorna commented
## Assessment
### Run

<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator CloudReadyValidator
[*] Executing validator UnapprovedKeywordsValidator
318
[*] Executing validator ExceptionValidator
[*] Executing validator CredentialsValidator
[*] Executing validator PasswordValidator
[*] Executing validator PrintValidator
[*] Executing validator ConfidentialValidator
violation: help.md, line: 718
violation: help.md, line: 724
[*] Executing validator DockerValidator
[*] Executing validator URLValidator
WARNING: URLs found that return a 4xx code. Verify they are publicly accessible and if not, update with a working URL.
violation: plugin.spec.yaml[838]: https://threatinsight.proofpoint.com/5d1ce8c6-1234-6789-ef71-f39=98c3e92e3/settings/privileges?linkOrigin=3Dnotif\
violation: plugin.spec.yaml[838]: https://threatinsight.proofpoint.com/5d1ce8c6-1234-6789=-ef71-f3998c3e92e3/threat/email/6b5ebcb1a7fb7e19bad6d8e02a2a5e169320b1f8a75=9e7db48f3da6f4e798a39?linkOrigin=3Dnotif
violation: plugin.spec.yaml[838]: https://threatinsight.proofpoint.com/5d1ce8c6-1234-6789-ef71-f39=98c3e92e3/threat/email/6b5ebcb1a7fb7e19bad6d8e02a2a5e169320b1f8a759e7db48f3=da6f4e798a39?linkOrigin=3Dnotif\
violation: help.md[270]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[346]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[357]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[509]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[521]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[582]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[700]: https://threatinsight.proofpoint.com/e65934ff-e650...
violation: help.md[742]: https://threatinsight.proofpoint.com/v7l34e70-a2ec-a214-bc4d-acd68a33dba2/threat/email/9c22af77f29f5eb007403455b7896906b479995b6444e421d6093e683f593e4?linkOrigin=notif
violation: help.md[135]: https://urldefense.proofpoint.com/v1/url?u=http://www.example.com/&amp
[*] Plugin failed validation! The following validation errors occurred:

Validator "ConfidentialValidator" failed!
        Cause: Please use 'user@example.com' when including emails. The above items violated this.


----
[*] Total time elapsed: 74064.37599999999ms
```

<summary>
icon-validate --all .
</summary>
</details>

<details>

```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../../tools/Makefiles/Helpers.mk ../../tools/Makefiles/Colors.mk
--
[*] Running validators
[*] Validating plugin at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing validator RequiredValidator
[*] Executing validator VersionValidator
[*] Executing validator DockerfileParentValidator
[*] Executing validator ProfanityValidator
[*] Executing validator AcronymValidator
[*] Executing validator JSONValidator
[*] Executing validator OutputValidator
[*] Executing validator RegenerationValidator
[*] Executing validator HelpInputOutputValidator
[*] Executing validator SupportValidator
[*] Executing validator RuntimeValidator
[*] Executing validator VersionPinValidator
[*] Executing validator EncodingValidator
[*] Executing validator ExampleInputValidator
[*] Executing validator CloudReadyValidator
[*] Executing validator UnapprovedKeywordsValidator
318
[*] Plugin successfully validated!

----
[*] Total time elapsed: 4344.187ms
```

<summary>
make validate
</summary>
</details>

2021-07-06 14:54 UTC, jmcadams-r7 approved these changes

2021-07-06 15:07 UTC, mrinehart-r7 approved these changes

2021-07-06 15:07 UTC, merged