Soar 5963 Convert Type Unit Tests
rapid7/insightconnect-plugins pull request #952
Opened 2021-06-23 19:15 UTC by aholland-r7

## Proposed Changes

### Description

Added unit tests for string_to_object and string_to_float actions. Also noticed errors in the help.md and so fixed.

### Testing

No plugin functionality changes, but all tests run and passed

2021-06-23 20:10 UTC, jmcadams-r7 requested changes

2021-06-23 20:10 UTC, jmcadams-r7 commented on plugins/type_converter/unit_test/test_string_to_float.py
> +        with self.assertRaises(PluginException):
Split these into a new test. Call it like "test_<action>_negative_tests"

2021-06-23 20:10 UTC, jmcadams-r7 commented on plugins/type_converter/unit_test/test_string_to_object.py
> +        with self.assertRaises(PluginException):
Split into their own tests.

2021-06-24 18:42 UTC, aholland-r7 commented on plugins/type_converter/plugin.spec.yaml
> +        example: 'Rapid7 Insightconnect'
```suggestion
        example: 'Rapid7 InsightConnect'
```

2021-06-24 18:42 UTC, aholland-r7 commented on plugins/type_converter/help.md
> +  'rapid7':'value'}"
```suggestion
  "input": "{'object':['rapid','7'], 'rapid7':'value'}"
```

2021-06-24 18:42 UTC, aholland-r7 commented on plugins/type_converter/help.md
> +  "rapid7": "value"}'
```suggestion
  "output": "{'object': ['rapid', '7'], 'rapid7': 'value'}"
```

2021-06-24 18:42 UTC, aholland-r7 commented on plugins/type_converter/help.md
> +  'rapid7':'value'}"
```suggestion
  "input": {
    "object": ["rapid", "7"],
    "rapid7": "value"
  }
```

2021-06-24 18:42 UTC, aholland-r7 commented on plugins/type_converter/unit_test/test_string_to_float.py
> +
Add a _very_ large number (22 digit)

2021-06-24 18:42 UTC, aholland-r7 commented on plugins/type_converter/unit_test/test_string_to_object.py
> +            test_action.run(working_params)
empty string test, or just a space

2021-06-29 15:44 UTC, jmcadams-r7 submitted a review, later dismissed

2021-06-29 17:26 UTC, mrinehart-r7 approved these changes

2021-06-29 17:28 UTC, mberezin-r7 approved these changes
LGTM

2021-06-29 17:30 UTC, merged