Add pagination in Query and Query Griup Membership actions in Active Directory LDAP plugin
rapid7/insightconnect-plugins pull request #956
Opened 2021-06-26 18:00 UTC by r7-kszczepanskagorna

## Proposed Changes

### Description

Add pagination in Query and Query Griup Membership actions in Active Directory LDAP plugin
Ticket - [MC-535] 
Valid Unit Tests are in PR #925

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connecting to https://example.com\nFailed to connect to the server with NTLM, attempting to connect with basic auth\nConnected!\nrapid7/Active Directory https://example.com Step name: query\nEscaped query: (objectclass=*)\n",
    "meta": {},
    "output": {
      "count": 10,
      "results": [
        {
          "attributes": {
            "cn": [
              "ship_crew"
            ],
            "createTimestamp": "2021-03-11 13:28:53+00:00",
            "creatorsName": "cn=admin,dc=planetexpress,dc=com",
            "entryCSN": [
              "https://example.com"
            ],
            "entryDN": "cn=ship_crew,ou=people,dc=planetexpress,dc=com",
            "entryUUID": "77adb9c0-16b9-103b-86e9-bf7e5461059d",
            "groupType": 2147483650,
            "hasSubordinates": false,
            "member": [
              "cn=Philip J. Fry,ou=people,dc=planetexpress,dc=com",
              "cn=Turanga Leela,ou=people,dc=planetexpress,dc=com",
              "cn=Bender Bending Rodríguez,ou=people,dc=planetexpress,dc=com"
            ],
            "modifiersName": "cn=admin,dc=planetexpress,dc=com",
            "modifyTimestamp": "2021-03-11 13:28:53+00:00",
            "objectClass": [
              "Group",
              "top"
            ],
            "structuralObjectClass": "Group",
            "subschemaSubentry": "cn=Subschema"
          },
          "dn": "cn=ship_crew,ou=people,dc=planetexpress,dc=com"
        },
        {
          "attributes": {
            "cn": [
              "admin_staff"
            ],
            "createTimestamp": "2021-03-11 13:28:53+00:00",
            "creatorsName": "cn=admin,dc=planetexpress,dc=com",
            "entryCSN": [
              "https://example.com"
            ],
            "entryDN": "cn=admin_staff,ou=people,dc=planetexpress,dc=com",
            "entryUUID": "77aae984-16b9-103b-86e8-bf7e5461059d",
            "groupType": 2147483650,
            "hasSubordinates": false,
            "member": [
              "cn=Hubert J. Farnsworth,ou=people,dc=planetexpress,dc=com",
              "cn=Hermes Conrad,ou=people,dc=planetexpress,dc=com"
            ],
            "modifiersName": "cn=admin,dc=planetexpress,dc=com",
            "modifyTimestamp": "2021-03-11 13:28:53+00:00",
            "objectClass": [
              "Group",
              "top"
            ],
            "structuralObjectClass": "Group",
            "subschemaSubentry": "cn=Subschema"
          },
          "dn": "cn=admin_staff,ou=people,dc=planetexpress,dc=com"
        },
        {
          "attributes": {
            "cn": [
              "John A. Zoidberg"
            ],
            "createTimestamp": "2021-03-11 13:28:53+00:00",
            "creatorsName": "cn=admin,dc=planetexpress,dc=com",
            "description": [
              "Decapodian"
            ],
            "displayName": "Zoidberg",
            "employeeType": [
              "Doctor"
            ],
            "entryCSN": [
              "https://example.com"
            ],
            "entryDN": "cn=John A. Zoidberg,ou=people,dc=planetexpress,dc=com",
            "entryUUID": "77a96c30-16b9-103b-86e7-bf7e5461059d",
            "givenName": [
              "John"
            ],
            "hasSubordinates": false,
            "jpegPhoto": [
              {
                "encoded": "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCAEYAVcDAREAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAAAAECBQYHBAMI/8QAHAEBAAEFAQEAAAAAAAAAAAAAAAECBAUGBwMI/9oADAMBAAIQAxAAAAH6c9LUSsBIhJCGVQyqlqPOrzbNLKqGzFOt8tScTvMDZbDy+V52e1hP5DVb/mufTntZNEk2YZVQAAAESosSoANmEmABYlYmxY3OOiVSsEEmGzSh510NmGTT5zR510Y/iN8rmE6O+KwDnubRMlh/DzjRdh5RJXVlK+fjKU+DaqQAAIlwDokg5IAyYAEQJseMzjlTokSIahs0pMedVLKqWTSyaMtx+20zX+rBy5XB+2d1n1yGJkMxr/vV5gASuO8dFx+NDzqpJgAACJfEviQQUQRCSbMJMWXFZ98VKlRBqlswk0sqp86obNPjNHztq/a/bwy3FufPLFtGkPQAAAB7WcavicSDJhlVIIASBYLEuiXCxLZhkw2aSQWXFZ50VOSJENmGqUmPOqllVLJprSvE6eg92w6nJ32LAA46PTmsslyYPZvHWty8q/C27nxzXPDCNmGzDJhJgAZVLZPph0FiXxLolkw2YSYALJi866KliVSiEmGzCI866WzSyacjzPvF5SgAj7TIc2H2Dh17bevFZz0orAAfe6/rW18UlPS1STZpAAZVKxCwBQAIkmAQCy4vOiVgqUQkhDJhlVKTHnNGPZ244chRx295H4DaW6jv3t4XIcNdt1U+3pFYBxV29w2fj2m5PU0QgTANkkysQDKpbJ9J0QosAQCxYzOOiVABBsw2qlBsx5VedPu/XLMllObnXX/e3ugAAjfSz7Kbj2p9ADyrt9K2/hdrusM4bJs0oNqlslgysgsFHQWmFG1ShY8XmVSsFSiEEmEmEGTQ2aWV0Zjj9speudaBvrZTVzg5X1sMmNC8r6r2uf66fazX2q0D0tbsifyunXzJ6q+JQ86qUmA8q5dAGVGyBYOg6HlWCyYrLqkFSiAQbNLZpRDZhlVFep98d0/vr4rlb7V/ofMc1CrKmUXGHa72fkrtfp/YuMh7mfX+Il7iyIJMJMAg2qViA865bIFH0EkyoE/jMo6JckSiAbNKISTZpSYbNLKo+edR7p1W+VZNFoyOndM+YVfzu/Gw20OS81ycrtYj1tNr2nkXTNIAgDKpSQMqAALBRBJBOY7IrEqlYIATDZpSYSYQbLy9KMP1bsPPj9qAPCry5avHrp9/an0AIj1sLzsXK9My+lgCSZVLJJIAAAAAAAlbO/fSfSWKlEEml [...]

2021-06-27 22:40 UTC, jschipp-r7 commented on plugins/active_directory_ldap/help.md
> +* 5.2.2 - Add pagination in actions Query and Query Group Membership
```suggestion
* 5.2.2 - Add automatic pagination in actions Query and Query Group Membership
```

2021-06-27 22:41 UTC, jschipp-r7 approved these changes

2021-06-28 20:58 UTC, mrinehart-r7 requested changes

2021-06-28 20:58 UTC, mrinehart-r7 commented on plugins/active_directory_ldap/help.md
> +* 5.2.2 - Add automatic pagination in actions Query and Query Group Membership
```suggestion
* 5.2.2 - Add automatic pagination in Query Group Membership and Query actions
```

2021-06-28 20:59 UTC, mrinehart-r7 commented
@r7-kszczepanskagorna can you provide screenshots of this being tested in-product?

2021-07-04 23:46 UTC, r7-kszczepanskagorna commented
![query](https://user-images.githubusercontent.com/65252060/124402806-db2a0700-dd32-11eb-8a6b-257948a825e9.png)
![query group membership](https://user-images.githubusercontent.com/65252060/124402808-dd8c6100-dd32-11eb-8a39-29fcfdbf5982.png)
![query group membership2](https://user-images.githubusercontent.com/65252060/124402812-df562480-dd32-11eb-8384-60d5345e7844.png)

2021-07-06 14:59 UTC, mrinehart-r7 approved these changes

2021-07-15 18:26 UTC, jmcadams-r7 approved these changes

2021-07-15 18:26 UTC, merged