Add Fetch Forensics action with unit test in Proofpoint TAP plugin
rapid7/insightconnect-plugins pull request #958
Opened 2021-06-27 23:31 UTC by r7-kszczepanskagorna

## Proposed Changes

### Description
Add Fetch Forensics action with unit test in Proofpoint TAP plugin
Tickets: [MC-424][MC-588] 

## PR Requirements

Developers, verify you have completed the following items by checking them off:

### Testing

#### Unit Tests

Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests

- [ ] Unit tests written for any new or updated code

#### In-Product Tests

If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests should be done:

- [ ] Screenshot of job output with the plugin changes
- [ ] Screenshot of the changed connection, actions, or triggers input within the InsightConnect workflow builder

### Style

Review the [style guide](https://docs.rapid7.com/insightconnect/style-guide/)

- [ ] For dependencies, pin [OS package](https://docs.rapid7.com/insightconnect/style-guide/#dockerfile) and [Python package](https://docs.rapid7.com/insightconnect/style-guide/#requirements.txt) versions
- [ ] For security, set least privileged account with ``USER nobody`` in the ``Dockerfile`` when possible
- [ ] For size, use the [slim SDK images](https://docs.rapid7.com/insightconnect/sdk-guide/#sdk-guide) when possible: ``komand/python-3-37-slim-plugin`` and ``komand/python-3-37-plugin``
- [ ] For error handling, use of [PluginException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations/#plugin-exceptions) and [ConnectionTestException](https://docs.rapid7.com/insightconnect/error-handling-in-integrations#connection-exceptions)
- [ ] For logging, use [self.logger](https://docs.rapid7.com/insightconnect/sdk-guide/#logging)
- [ ] For docs, use [changelog style](https://docs.rapid7.com/insightconnect/style-guide/#changelog)
- [ ] For docs, validate markdown with ``make validate`` which calls ``mdl`` to lint ``help.md``

### Functional Checklist
- [ ] Work fully completed
- [ ] Functional
  - [ ] Any new actions/triggers include JSON [test files](https://docs.rapid7.com/insightconnect/style-guide/#tests) in the `tests/` directory created with `icon-plugin run -c sample $action > tests/$action.json`
  - [ ] Tests should all pass unless it's a negative test. Negative tests have a naming convention of `tests/$action_bad.json`
  - [ ] Unsuccessful tests should fail by raising an exception causing the plugin to die and an object should be returned on successful test
  - [ ] Add functioning test results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -T tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at end)
  - [ ] Add functioning run results to PR, sanitize any output if necessary
    * Single action/trigger `icon-plugin run -R tests/example.json --debug --jq`
    * All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format at end)

## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint https://example.com Step name: fetch_forensics\n",
    "meta": {},
    "output": {
      "generated": "https://example.com",
      "reports": [
        {
          "forensics": [
            {
              "display": "Malicious content dropped during execution",
              "engine": "iee",
              "malicious": true,
              "note": "Malicious content dropped during execution",
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "behavior",
              "what": {
                "rule": "behavior_9de5069c5afe602b2ea0a04b66beb2c0"
              }
            },
            {
              "display": "Sample creates outbound HTTP requests",
              "engine": "iee",
              "malicious": false,
              "note": "Sample creates outbound HTTP requests",
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "behavior",
              "what": {
                "rule": "behavior_9de5069c5afe606beb2c0",
                "url": "https://example.com"
              }
            },
            {
              "display": "Sample creates outbound HTTP requests",
              "engine": "iee",
              "malicious": false,
              "note": "Sample creates outbound HTTP requests",
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "behavior",
              "what": {
                "rule": "behavior_9de5069c5afe602b2b2c0",
                "url": "https://example.com"
              }
            },
            {
              "display": "URL: https://example.com",
              "engine": "iee",
              "malicious": false,
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "url",
              "what": {
                "url": "https://example.com"
              }
            },
            {
              "display": "File img_desktop_background_game[1].jpg created",
              "engine": "iee",
              "malicious": false,
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "file",
              "what": {
                "path": "C:\\Users\\user\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\N6XTLFY7\\img_desktop_background_game[1].jpg",
                "sha256": "30f800f97aeaa8d62bdf3a6fb2b068038f8521461e5050",
                "size": 229269
              }
            },
            {
              "display": "Sample creates outbound HTTP requests",
              "engine": "iee",
              "malicious": false,
              "note": "Sample creates outbound HTTP requests",
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "behavior",
              "what": {
                "rule": "behavior_9de5069c5afe602b6beb2c0",
                "url": "https://example.com"
              }
            },
            {
              "display": "URL: https://example.com",
              "engine": "iee",
              "malicious": false,
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "url",
              "what": {
                "url": "https://example.com"
              }
            },
            {
              "display": "URL: https://example.com",
              "engine": "iee",
              "malicious": false,
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "url",
              "what": {
                "url": "https://example.com"
              }
            },
            {
              "display": "URL: https://example.com",
              "engine": "iee",
              "malicious": false,
              " [...]

2021-06-27 23:41 UTC, jschipp-r7 requested changes

2021-06-27 23:41 UTC, jschipp-r7 commented on plugins/proofpoint_tap/plugin.spec.yaml
> +      title: Cnames
```suggestion
      title: Canonical Names
```

2021-06-27 23:41 UTC, jschipp-r7 commented on plugins/proofpoint_tap/plugin.spec.yaml
> +      description: Optional, an array of cnames which were associated with the hostname
```suggestion
      description: Optional, an array of CNAMEs which were associated with the hostname
```

2021-06-27 23:41 UTC, jschipp-r7 commented on plugins/proofpoint_tap/plugin.spec.yaml
> +    description: Fetch Forensics allows to pull detailed forensic evidences about individual threats or campaigns
```suggestion
    description: Fetch Forensics allows users to pull detailed forensic evidence about individual threats or campaigns
```

2021-06-27 23:41 UTC, jschipp-r7 commented on plugins/proofpoint_tap/help.md
> +This action is used to fetch Forensics allows to pull detailed forensic evidences about individual threats or campaigns.
```suggestion
This action is used to fetch forensic evidence about individual threats or campaigns.
```

2021-06-28 17:45 UTC, mrinehart-r7 requested changes

2021-06-28 17:45 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/action.py
> +                cause="Required only one parameter.",
```suggestion
                cause="Both Campaign ID and Threat ID were provided.",
```

2021-06-28 17:45 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/action.py
> +                assistance="One of the following two parameters are required: Campaign ID or Threat ID.",
```suggestion
                assistance="Only one of the following two parameters can be used: Campaign ID or Threat ID.",
```

2021-06-28 17:45 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/action.py
> +                assistance="Please enter Threat ID or Campaign ID.",
```suggestion
                cause="One of the following inputs must be provided.",
                assistance="Please enter either Threat ID or Campaign ID.",
```

2021-06-28 17:45 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/plugin.spec.yaml
> +      title: IPs
```suggestion
      title: Resolved IP Addresses
```
Seems like a more descriptive title based off the description

2021-06-28 17:45 UTC, mrinehart-r7 commented on plugins/proofpoint_tap/plugin.spec.yaml
> +      title: IP
```suggestion
      title: Remote IP Address
```

2021-06-28 22:22 UTC, r7-kszczepanskagorna commented
## Assessment
### Run

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint https://example.com Step name: fetch_forensics\n",
    "meta": {},
    "output": {
      "generated": "https://example.com",
      "reports": [
        {
          "forensics": [
            {
              "display": "Malicious content dropped during execution",
              "engine": "iee",
              "malicious": true,
              "note": "Malicious content dropped during execution",
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "behavior",
              "what": {
                "rule": "behavior_9de5069c5afb2c0"
              }
            },
            {
              "display": "Sample creates outbound HTTP requests",
              "engine": "iee",
              "malicious": false,
              "note": "Sample creates outbound HTTP requests",
              "platforms": [
                {
                  "name": "Win10",
                  "os": "win",
                  "version": "win10"
                }
              ],
              "time": 0,
              "type": "behavior",
              "what": {
                "rule": "behavior_9de5069c5afe60c0",
                "url": "https://example.com"
              }
            },

    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:3.1.0 --debug run < tests/fetch_forensics_campain_id.json
</summary>
</details>



<details>

```
{
  "body": {
    "error": "An error occurred during plugin execution!\n\nBoth Campaign ID and Threat ID were provided. Only one of the following two parameters can be used: Campaign ID or Threat ID.",
    "log": "Connect: Connecting...\nrapid7/Proofpoint https://example.com Step name: fetch_forensics\nAn error occurred during plugin execution!\n\nBoth Campaign ID and Threat ID were provided. Only one of the following two parameters can be used: Campaign ID or Threat ID.\nTraceback (most recent call last):\n  File \"/usr/local/lib/https://example.com\", line 326, in handle_step\n    output = https://example.com\n  File \"/usr/local/lib/https://example.com\", line 476, in start_step\n    output = func(params)\n  File \"/usr/local/lib/https://example.com\", line 28, in run\n    raise PluginException(\https://example.com An error occurred during plugin execution!\n\nBoth Campaign ID and Threat ID were provided. Only one of the following two parameters can be used: Campaign ID or Threat ID.\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:3.1.0 --debug run < tests/fetch_forensics_campain_id_and_threat_id_bad.json
</summary>
</details>

<details>

```
{
  "body": {
    "error": "An error occurred during plugin execution!\n\nOne of the following inputs must be provided. Please enter either Threat ID or Campaign ID.",
    "log": "Connect: Connecting...\nrapid7/Proofpoint https://example.com Step name: fetch_forensics\nAn error occurred during plugin execution!\n\nOne of the following inputs must be provided. Please enter either Threat ID or Campaign ID.\nTraceback (most recent call last):\n  File \"/usr/local/lib/https://example.com\", line 326, in handle_step\n    output = https://example.com\n  File \"/usr/local/lib/https://example.com\", line 476, in start_step\n    output = func(params)\n  File \"/usr/local/lib/https://example.com\", line 33, in run\n    raise PluginException(\https://example.com An error occurred during plugin execution!\n\nOne of the following inputs must be provided. Please enter either Threat ID or Campaign ID.\n",
    "meta": {},
    "status": "error"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:3.1.0 --debug run < tests/fetch_forensics_no_campain_id_and_no_threat_id_bad.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint https://example.com Step name: fetch_forensics\n",
    "meta": {},
    "output": {
      "generated": "https://example.com",
      "reports": [
        {
          "forensics": [],
          "id": "30f800f97aeaa8d62bdf3a6fb0",
          "name": "https://example.com",
          "scope": "THREAT",
          "threatStatus": "active"
        }
      ]
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:3.1.0 --debug run < tests/fetch_forensics_threat_id.json
</summary>
</details>

<details>

```
{
  "body": {
    "log": "Connect: Connecting...\nrapid7/Proofpoint https://example.com Step name: fetch_forensics\n",
    "meta": {},
    "output": {
      "generated": "https://example.com",
      "reports": [
        {
          "forensics": [
            {
              "display": "Screenshot",
              "engine": "static",
              "malicious": true,
              "note": "Screenshot",
              "platforms": [
                {
                  "name": "static",
                  "os": "static",
                  "version": "0"
                }
              ],
              "time": 0,
              "type": "screenshot",
              "what": {
                "url": "https://example.com"
              }
            },
            {
              "display": "redirect chain for https://example.com",
              "engine": "static",
              "malicious": true,
              "platforms": [
                {
                  "name": "static",
                  "os": "static",
                  "version": "0"
                }
              ],
              "time": 0,
              "type": "redirect_chain",
              "what": {
                "url": "https://example.com"
              }
            },
            {
              "display": "Malicious URL seen: https://example.com",
              "engine": "static",
              "malicious": true,
              "note": "Malicious geofenced URL leads to malware",
              "platforms": [
                {
                  "name": "static",
                  "os": "static",
                  "version": "0"
                }
              ],
              "time": 0,
              "type": "url",
              "what": {
                "rule": "65255288-22ad-11eb-b",
                "url": "https://example.com"
              }
            },
            {
              "display": "Screenshot",
              "engine": "static",
              "malicious": true,
              "note": "Screenshot",
              "platforms": [
                {
                  "name": "static",
                  "os": "static",
                  "version": "0"
                }
              ],
              "time": 0,
              "type": "screenshot",
              "what": {
                "url": "https://example.com"
              }
            }
          ],
          "id": "30f800f97aeaa8d62bdf3a",
          "name": "https://example.com",
          "scope": "THREAT",
          "threatStatus": "active"
        }
      ]
    },
    "status": "ok"
  },
  "type": "action_event",
  "version": "v1"
}

```

<summary>
docker run --rm -i rapid7/proofpoint_tap:3.1.0 --debug run < tests/fetch_forensics_threat_id_campaing_forensics_false.json
</summary>
</details>


<details>

```
[*] Validating plugin with all validators at .

[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValida [...]

2021-06-29 16:01 UTC, mrinehart-r7 commented
Validator failure looks like a false positive

2021-06-29 16:07 UTC, mrinehart-r7 approved these changes

2021-06-29 19:49 UTC, jschipp-r7 approved these changes

2021-06-29 19:52 UTC, jschipp-r7 commented
> Validator failure looks like a false positive

We should get a ticket in for the failure if it's something we can fix.

2021-06-29 19:53 UTC, merged