SOAR-6189 Prospector Update
rapid7/insightconnect-plugins pull request #971
Opened 2021-07-14 16:53 UTC by aholland-r7

## Proposed Changes

### Description

Updated prospector (Static Code Workflow) to including pylint and pyflakes, as well as change to only run on changed plugins.

### Testing

No official tests for prospector other than the fact that works to find errors
Not a plugin action, so no need for unit tests

2021-07-14 16:55 UTC, jmcadams-r7 approved these changes

2021-07-15 14:14 UTC, jmcadams-r7 submitted a review, later dismissed

2021-07-15 16:46 UTC, mberezin-r7 approved these changes
LGTM!

2021-07-15 18:03 UTC, jmcadams-r7 submitted a review, later dismissed

2021-07-15 18:12 UTC, jmcadams-r7 requested changes
Needs to work with cortext_xdr changes. Add verbosity to the output (show the diff output so we know what's going to be tested.)

2021-07-19 14:43 UTC, merged