[No Ticket] - String Operations - Replace
rapid7/insightconnect-plugins pull request #976
Opened 2021-07-20 19:10 UTC by jmcadams-r7

## Proposed Changes
This PR adds the Replace function to the string Plugin

## Testing: 
```
RMT-MBP-5357:string jmcadams$ ./run.sh -R tests/replace.json -j
Running: cat tests/replace.json | docker run --rm   -i rapid7/string:1.4.0  run | grep -- ^\{ | jq -r '.body | try(.log | split("\n") | .[]),.output'
rapid7/String Operations:1.3.1. Step name: replace
in_string: {"id":"R1155","title":"Account Executive, Commercial Accounts","location":"US - MA - Boston"}
{"id":"R2226","title":"Account Executive, Commercial Accounts","location":"US - TX - Austin"}
find_string: id
find_string: ID
rapid7/String Operations:1.3.1. Step name: replace
in_string: {"id":"R1155","title":"Account Executive, Commercial Accounts","location":"US - MA - Boston"}
{"id":"R2226","title":"Account Executive, Commercial Accounts","location":"US - TX - Austin"}
find_string: id
find_string: ID

{
  "result_string": "{\"ID\":\"R1155\",\"title\":\"Account Executive, Commercial Accounts\",\"location\":\"US - MA - Boston\"}\n{\"ID\":\"R2226\",\"title\":\"Account Executive, Commercial Accounts\",\"location\":\"US - TX - Austin\"}"
}
```

## Workflow:

2021-07-21 16:55 UTC, mrinehart-r7 approved these changes

2021-07-22 18:31 UTC, mrinehart-r7 requested changes

2021-07-22 18:31 UTC, mrinehart-r7 commented on plugins/string/plugin.spec.yaml
> +        required: false
```suggestion
        required: true
```
Check to make sure an empty string validates fine in product

2021-07-22 18:31 UTC, mrinehart-r7 commented on plugins/string/komand_string/actions/replace/action.py
> +            replace_string = ""
```suggestion
        replace_string = params.get(Input.REPLACEMENT_VALUE, "")
```

2021-07-22 18:31 UTC, mrinehart-r7 commented on plugins/string/komand_string/actions/replace/action.py
> +        self.logger.info(f"find_string: {replace_string}")
```suggestion
        self.logger.info(f"replace_string: {replace_string}")
```

2021-07-22 18:32 UTC, mrinehart-r7 submitted a review, later dismissed

2021-07-22 18:36 UTC, mrinehart-r7 approved these changes

2021-07-22 18:37 UTC, aholland-r7 approved these changes

2021-07-22 18:37 UTC, pmara-r7 approved these changes
reviewed as a team

2021-07-23 14:59 UTC, merged